import json

with open("proyectorData.json", "r", encoding="utf-8") as f:
    db = json.load(f)

turismo_data = {
    "1": [
        [
            {"title": "Turismo: Proyecto Producto Turístico (Semana 1)", "sub": "1/10 - Bitácora y Misión Emprendedora", "content": "📅 <b>Fecha:</b> Hoy<br>📌 <b>Título:</b> 'Ideación de un Producto Turístico: ¿Bien o Servicio?'<br>🎯 <b>Meta:</b> Definir una idea de producto turístico innovador (artesanía, producto gastronómico o experiencia/ruta guiada) para desarrollarlo en un ciclo intensivo de 3 semanas.", "icon": "ph-suitcase", "timer": 300, "customHtml": ""},
            {"title": "El Desafío: Crear un Producto Real para el Turista", "sub": "2/10 - Oportunidad en la Región", "content": "<b>Observa tu entorno:</b><br>Miles de visitantes llegan a nuestra región buscando llevarse algo especial o vivir una experiencia inolvidable.<br>Tienes dos caminos para elegir:<br>• 📦 <b>Un BIEN (Producto Tangible):</b> Café especial con historia, dulce/mermelada artesanal, artesanía con identidad o kit del caminante ecológico.<br>• 🧭 <b>Un SERVICIO (Experiencia/Intangible):</b> Tour fotográfico de atardeceres, ruta de leyendas del pueblo, taller vivencial campesino o caminata de avistamiento de aves.", "icon": "ph-lightbulb-filament", "timer": 300, "customHtml": ""},
            {"title": "¿Qué Hace que un Producto Turístico sea Exitoso?", "sub": "3/10 - Las 3 Claves del Éxito", "content": "1. 🌿 <b>Identidad Local:</b> Rescata las tradiciones, la naturaleza o la cultura de la región.<br>2. ✨ <b>Propuesta de Valor Única:</b> No vende solo 'un objeto' o 'un paseo', vende una <b>emoción o recuerdo memorable</b>.<br>3. 🎯 <b>Público Objetivo Claro:</b> ¿A quién va dirigido? (Familias con niños, parejas jóvenes aventureras, extranjeros o ecoturistas).", "icon": "ph-seal-check", "timer": 300, "customHtml": ""},
            {"title": "Cuadro Comparativo: Bien Tangible vs. Servicio Turístico", "sub": "4/10 - Modelo de Elección", "content": "<div style='display:grid; grid-template-columns:1fr 1fr; gap:12px; margin-top:10px;'><div style='background:#FEF3C7; padding:12px; border-radius:8px; border:2px solid #F59E0B;'><b>📦 BIEN TURÍSTICO (Objeto)</b><br>• Se puede tocar y empacar.<br>• El turista se lo lleva a su casa.<br>• <i>Ejemplos:</i> Artesanías en guadua, snacks típicos, llaveros tallados, café de origen.</div><div style='background:#ECFDF5; padding:12px; border-radius:8px; border:2px solid #10B981;'><b>🧭 SERVICIO TURÍSTICO (Experiencia)</b><br>• Se vive y se siente en el momento.<br>• Requiere guianza o atención.<br>• <i>Ejemplos:</i> Ruta ecológica, cata de café guiada, recorrido nocturno de mitos.</div></div>", "icon": "ph-arrows-left-right", "timer": 300, "customHtml": ""},
            {"title": "⏱️ Reto en el Cuaderno: Ficha de Nacimiento del Producto", "sub": "5/10 - Creación Individual/Parejas", "content": "<b>Diseña en tu cuaderno la Ficha Oficial de tu Producto Turístico:</b><br><br>1. 🏷️ <b>Nombre Comercial del Producto:</b> (Creativo y sonoro).<br>2. 📦 <b>Tipo de Producto:</b> ¿Es un Bien Tangible o un Servicio de Experiencia?<br>3. 💡 <b>¿En qué consiste?:</b> Describe en 3 líneas qué es y qué problema o deseo soluciona al turista.<br>4. 👥 <b>¿Quién es tu Turista Ideal?:</b> (Edad, intereses y gustos).<br>5. 🎨 <b>Boceto del Logotipo / Símbolo:</b> Dibuja un logo sencillo con lápices de colores.<br><br>✍️ <i>¡Utiliza regla y decora la ficha con un marco profesional!</i>", "icon": "ph-pencil-line", "timer": 300, "customHtml": ""},
            {"title": "Estudio de Caso: De una Naranja a un Tour Mundial", "sub": "6/10 - Inspiración Real", "content": "Una finca tradicional no ganaba suficiente vendiendo naranjas por bulto a $500 pesos. Decidieron crear el <i>'Tour Cítrico y Taller de Mermeladas'</i> donde los turistas cosechan sus naranjas y preparan su dulce. ¡Ahora cobran $50.000 por turista!", "icon": "ph-sparkle", "timer": 300, "customHtml": ""},
            {"title": "Taller de Validación en Parejas: Focus Group", "sub": "7/10 - Coevaluación", "content": "Preséntale tu idea a tu compañero de al lado en 1 minuto:<br>• ¿Pagarías por este producto si fueras un turista de visita?<br>• ¿Qué sugerencia le harías para mejorarlo o hacerlo más llamativo?<br>Anota en tu cuaderno el consejo que te dio tu compañero.", "icon": "ph-users", "timer": 300, "customHtml": ""},
            {"title": "Pregunta de Razonamiento Comercial", "sub": "8/10 - Pensamiento Emprendedor", "content": "¿Por qué un turista está dispuesto a pagar 5 veces más por una taza de café servida con una historia campesina en un mirador que por un café servido en un vaso plástico sin explicación?", "icon": "ph-coffee", "timer": 300, "customHtml": ""},
            {"title": "Plenaria: La Lluvia de Productos Turísticos", "sub": "9/10 - Socialización", "content": "Compartimos 5 ideas de productos del salón y el docente valida su viabilidad técnica para las próximas 2 semanas.", "icon": "ph-chalkboard-teacher", "timer": 300, "customHtml": ""},
            {"title": "Síntesis y Sello de Avance (Fase 1/3)", "sub": "10/10 - Cierre de Clase", "content": "✔️ <b>Producto Definido:</b> Idea de Bien o Servicio seleccionada con nombre y logotipo.<br>✔️ <b>Evidencia Sellada:</b> Ficha de Nacimiento del Producto aprobada en el cuaderno.<br><br>🌟 ¡Fase 1 completada! En la Semana 2 fabricaremos el prototipo y costeo.", "icon": "ph-check-circle", "timer": 300, "customHtml": ""}
        ]
    ],
    "2": [
        [
            {"title": "Turismo: Prototipado y Costeo (Semana 2)", "sub": "1/10 - Bitácora y Fabricación", "content": "📅 <b>Fecha:</b> Hoy<br>📌 <b>Título:</b> 'Diseño del Prototipo, Empaque/Itinerario y Costos'<br>🎯 <b>Meta:</b> Construir el prototipo visual del bien (muestra, empaque y etiqueta) o el mapa de ruta del servicio, calculando cuánto cuesta producirlo y a qué precio venderlo.", "icon": "ph-hammer", "timer": 300, "customHtml": ""},
            {"title": "De la Idea a la Realidad: El Prototipo", "sub": "2/10 - Fase de Construcción", "content": "<b>Un prototipo es la primera versión de tu producto para mostrar a los clientes:</b><br>• Si elegiste un <b>BIEN:</b> Diseñamos su empaque ecológico, su etiqueta informativa (ingredientes, origen, historia) y tamaño de porción.<br>• Si elegiste un <b>SERVICIO:</b> Diseñamos el mapa del recorrido con sus 4 paradas clave, la duración de cada parada y los materiales necesarios.", "icon": "ph-package", "timer": 300, "customHtml": ""},
            {"title": "Finanzas Básicas: Costo de Producción vs. Precio de Venta", "sub": "3/10 - Sin Matemáticas Complejas", "content": "Para no perder dinero en tu emprendimiento:<br>1. <b>Costo de Materiales:</b> Suma lo que gastas en ingredientes, empaque o insumos.<br>2. <b>Mano de Obra:</b> El valor de tu tiempo y trabajo de preparación.<br>3. <b>Ganancia Justa (Margen):</b> Lo que ganas para reinvertir y crecer.<br><b>Precio al Turista = Costos + Tu Ganancia Justa.</b>", "icon": "ph-coins", "timer": 300, "customHtml": ""},
            {"title": "Esquema del Prototipo: Etiqueta o Mapa de Ruta", "sub": "4/10 - Modelo Visual", "content": "<div style='background:#EFF6FF; border-left:4px solid #3B82F6; padding:12px; border-radius:8px; margin-top:10px;'>📦 <b>Si es un BIEN:</b> Tu etiqueta debe tener: Nombre, Eslogan, '100% Artesanal Colombiano', Ingredientes/Materiales y un código QR ficticio.<br><br>🧭 <b>Si es un SERVICIO:</b> Tu mapa debe tener: Punto de Encuentro ➔ Estación 1 (Sensorial) ➔ Estación 2 (Histórica) ➔ Estación 3 (Degustación/Fotografía) ➔ Cierre con Souvenir.</div>", "icon": "ph-map-pin", "timer": 300, "customHtml": ""},
            {"title": "⏱️ Reto en el Cuaderno: Plano del Prototipo y Tabla de Costos", "sub": "5/10 - Creación y Dibujo", "content": "<b>Dibuja en tu cuaderno en una página completa:</b><br><br>• 🎨 <b>Diseño Gráfico (Mitad Superior):</b><br>- Si es un Bien: Dibuja el empaque tridimensional con su etiqueta frontal a todo color.<br>- Si es un Servicio: Dibuja el mapa del sendero/tour con las 4 estaciones señaladas con íconos.<br><br>• 💰 <b>Tabla de Costos (Mitad Inferior):</b><br>- Materiales principales: $________<br>- Empaque / Recursos: $________<br>- Mano de obra / Guianza: $________<br>- <b>PRECIO DE VENTA SUGERIDO AL TURISTA:</b> $________<br><br>✍️ <i>¡Colorea con esmero y utiliza regla!</i>", "icon": "ph-pencil-line", "timer": 300, "customHtml": ""},
            {"title": "El Poder del Empaque Ecológico (Packaging Verde)", "sub": "6/10 - Tendencia Mundial", "content": "Los turistas de hoy rechazan el plástico de un solo uso y prefieren empaques de papel kraft, fique, hojas de plátano o vidrio reciclable. ¿Qué material ecológico usará tu producto?", "icon": "ph-leaf", "timer": 300, "customHtml": ""},
            {"title": "Taller en Parejas: Prueba de Usabilidad", "sub": "7/10 - Dinámica de Testeo", "content": "Intercambia el cuaderno con tu compañero:<br>• ¿La etiqueta es legible y atractiva?<br>• ¿El precio de venta parece justo y razonable para un turista?<br>Escríbanse una estrella ⭐ y una sugerencia de mejora.", "icon": "ph-arrows-clockwise", "timer": 300, "customHtml": ""},
            {"title": "Pregunta de Pensamiento Emprendedor", "sub": "8/10 - Razonamiento", "content": "Si producir tu paquete de galletas artesanales cuesta $2.000 y decides venderlo a $2.100, ¿por qué tu negocio no prosperará a largo plazo? ¿Cuál debería ser un precio saludable?", "icon": "ph-trend-up", "timer": 300, "customHtml": ""},
            {"title": "Plenaria: Ajustes Técnicos del Prototipo", "sub": "9/10 - Socialización", "content": "Revisión grupal de prototipos. El docente orienta los últimos detalles antes de la gran presentación comercial de la Semana 3.", "icon": "ph-presentation", "timer": 300, "customHtml": ""},
            {"title": "Síntesis y Sello de Avance (Fase 2/3)", "sub": "10/10 - Cierre de Clase", "content": "✔️ <b>Prototipo Fabricado:</b> Diseño gráfico del bien o mapa de ruta del servicio terminado.<br>✔️ <b>Evidencia Sellada:</b> Plano del producto y tabla de costeo sellada en el cuaderno.<br><br>🌟 ¡Fase 2 completada! En la Semana 3 realizaremos el Lanzamiento y Pitch Comercial.", "icon": "ph-check-circle", "timer": 300, "customHtml": ""}
        ]
    ],
    "3": [
        [
            {"title": "Turismo: Lanzamiento y Pitch Comercial (Semana 3)", "sub": "1/10 - Bitácora y Gran Estreno", "content": "📅 <b>Fecha:</b> Hoy<br>📌 <b>Título:</b> 'Lanzamiento Comercial, Storytelling y Venta en Vivo'<br>🎯 <b>Meta:</b> Presentar el producto turístico ante el salón utilizando un discurso de venta persuasivo (Pitch de 1 minuto) y un folleto/catálogo promocional.", "icon": "ph-megaphone", "timer": 300, "customHtml": ""},
            {"title": "¡El Día del Lanzamiento Oficial!", "sub": "2/10 - El Momento de la Verdad", "content": "<b>Tu producto ya tiene concepto, diseño y precio:</b><br>Hoy lo presentamos al mercado. Para que los turistas compren tu bien o reserven tu servicio, necesitas dos armas poderosas:<br>1. 📢 <b>Un Folleto / Catálogo Visual:</b> Que enamore a primera vista.<br>2. 🎙️ <b>Un Pitch de Venta Emocional (Elevator Pitch):</b> Un discurso claro de 60 segundos.", "icon": "ph-sparkle", "timer": 300, "customHtml": ""},
            {"title": "La Estructura del Pitch de 1 Minuto", "sub": "3/10 - El Guion de Oro", "content": "• 1️⃣ <b>El Gancho (10 s):</b> Una pregunta que capte la atención (<i>'¿Alguna vez soñaste con probar el secreto de nuestras abuelas...?'</i>).<br>• 2️⃣ <b>La Solución / Producto (20 s):</b> Presentas tu bien o servicio y qué lo hace único.<br>• 3️⃣ <b>La Emoción / Experiencia (20 s):</b> Qué va a sentir el turista al tenerlo.<br>• 4️⃣ <b>Llamado a la Acción (10 s):</b> Precio especial de lanzamiento y dónde adquirirlo.", "icon": "ph-microphone", "timer": 300, "customHtml": ""},
            {"title": "Esquema del Folleto Tríptico Comercial", "sub": "4/10 - Modelo Publicitario", "content": "<div style='display:grid; grid-template-columns:1fr 1fr 1fr; gap:8px; margin-top:10px; font-size:0.9rem;'><div style='background:#FDF2F8; padding:8px; border-radius:6px; border:1px solid #EC4899;'><b>1. Portada:</b><br>Logo, foto/dibujo del producto y eslogan pegajoso.</div><div style='background:#EFF6FF; padding:8px; border-radius:6px; border:1px solid #3B82F6;'><b>2. Beneficios:</b><br>3 razones para comprarlo y proceso artesanal.</div><div style='background:#ECFDF5; padding:8px; border-radius:6px; border:1px solid #10B981;'><b>3. Contacto & Precio:</b><br>Precio oficial, WhatsApp y redes sociales.</div></div>", "icon": "ph-newspaper", "timer": 300, "customHtml": ""},
            {"title": "⏱️ Reto en el Cuaderno: Folleto Promocional y Guion del Pitch", "sub": "5/10 - Creación Integral", "content": "<b>Diseña en tu cuaderno la campaña de lanzamiento:</b><br><br>• 📄 <b>Lado Izquierdo: Folleto Publicitario (Afiche/Catálogo):</b><br>- Título en letras grandes y decoradas.<br>- Dibujo estrella del producto en acción.<br>- 3 viñetas con beneficios clave.<br>- Caja destacada con el <b>PRECIO DE LANZAMIENTO</b> y contacto de WhatsApp.<br><br>• 🎙️ <b>Lado Derecho: Guion del Pitch (60 segundos):</b><br>- Escribe las 4 frases exactas que dirás para vender tu producto al público.<br><br>✍️ <i>¡Decora con colores llamativos para que parezca un anuncio real!</i>", "icon": "ph-pencil-line", "timer": 300, "customHtml": ""},
            {"title": "Feria de Negocios en Vivo en el Salón", "sub": "6/10 - Dinámica Práctica", "content": "<b>Simulación de Venta en el Aula:</b><br>La mitad del salón actúa como turistas con presupuesto para comprar, y la otra mitad expone su producto en su pupitre. Luego rotamos los roles.", "icon": "ph-storefront", "timer": 300, "customHtml": ""},
            {"title": "Taller en Parejas: Negociación y Cierre de Venta", "sub": "7/10 - Práctica de Comunicación", "content": "Un estudiante hace una objeción de turista (<i>'Está un poco caro'</i> o <i>'¿Por qué debería elegir este tour?'</i>) y el creador responde con amabilidad resaltando el valor artesanal del producto.", "icon": "ph-handshake", "timer": 300, "customHtml": ""},
            {"title": "Pregunta de Evaluación Comercial", "sub": "8/10 - Pensamiento Crítico", "content": "¿Qué aprendiste al escuchar a los turistas reales del salón? ¿Qué fue lo que más les gustó y qué deberías ajustar en tu producto?", "icon": "ph-chat-circle-dots", "timer": 300, "customHtml": ""},
            {"title": "Plenaria: La Gran Rueda de Emprendedores", "sub": "9/10 - Socialización", "content": "Votación simbólica de los 3 productos turísticos más creativos, mejor presentados y más viables del curso.", "icon": "ph-trophy", "timer": 300, "customHtml": ""},
            {"title": "Síntesis y Sello de Lanzamiento Exitoso (Fase 3/3)", "sub": "10/10 - Cierre del Ciclo de 3 Semanas", "content": "✔️ <b>Producto Lanzado al Mercado:</b> Proyecto completado desde la idea hasta la venta real.<br>✔️ <b>Evidencia Sellada:</b> Folleto comercial y guion del Pitch aprobados en el cuaderno.<br>✔️ <b>Reconocimiento:</b> ¡Certificación de Producto Turístico Innovador Peidagogos!<br><br>🌟 ¡FELICITACIONES! Has creado y defendido tu propio producto turístico.", "icon": "ph-seal-check", "timer": 300, "customHtml": ""}
        ]
    ],
    "4": [
        [
            {"title": "Turismo: Hospitalidad y Calidad en el Servicio", "sub": "1/10 - Bitácora y Protocolo", "content": "📅 <b>Fecha:</b> Hoy<br>📌 <b>Título:</b> 'Momentos de la Verdad y Protocolo de Atención 5 Estrellas'<br>🎯 <b>Meta:</b> Aprender a entregar el producto o servicio turístico con estándares de excelencia, calidez humana y resolución efectiva de quejas.", "icon": "ph-heart-handshake", "timer": 300, "customHtml": ""},
            {"title": "El Turista Recuerda Cómo lo Hiciste Sentir", "sub": "2/10 - Caso Real", "content": "Un hotel con habitaciones lujosas puede quebrar si sus recepcionistas atienden con cara seria y de mala gana. En cambio, una posada campesina humilde se llena de clientes si el trato es cálido, respetuoso y sonriente.", "icon": "ph-smiley", "timer": 300, "customHtml": ""},
            {"title": "Los 'Momentos de la Verdad' en tu Producto", "sub": "3/10 - Los 3 Puntos de Contacto", "content": "1. <b>El Saludo Inicial:</b> La primera impresión en los primeros 10 segundos.<br>2. <b>La Entrega / Experiencia:</b> Cumplir exactamente lo prometido sin demoras.<br>3. <b>La Despedida y Agradecimiento:</b> Dejar una huella que invite a volver.", "icon": "ph-clock-countdown", "timer": 300, "customHtml": ""},
            {"title": "El Protocolo L.A.S.T. para Resolver Quejas", "sub": "4/10 - Manejo de Clientes Difíciles", "content": "• 👂 <b>L (Listen - Escuchar):</b> Deja que el turista hable sin interrumpirlo.<br>• 🤝 <b>A (Apologize - Disculparse):</b> <i>'Lamento mucho este inconveniente'</i>.<br>• 💡 <b>S (Solve - Solucionar):</b> Ofrece una solución rápida y positiva.<br>• ❤️ <b>T (Thank - Agradecer):</b> <i>'Gracias por avisarnos para mejorar'</i>.", "icon": "ph-lifebuoy", "timer": 300, "customHtml": ""},
            {"title": "⏱️ Reto en el Cuaderno: El Decálogo de Atención de mi Negocio", "sub": "5/10 - Creación de Normas", "content": "<b>Escribe en tu cuaderno el Decálogo de Calidad para tu Producto Turístico:</b><br><br>1. 🌟 <b>Saludo Oficial:</b> Escribe las palabras exactas de bienvenida a tu cliente.<br>2. 🧼 <b>Normas de Higiene y Presentación:</b> (Uniforme, pulcritud, sonrisa).<br>3. 🎁 <b>Valor Agregado Sorpresa:</b> ¿Qué detalle inesperado le regalarás al cliente? (Una muestra extra, un dulce regional, una foto de recuerdo).<br>4. 💬 <b>Guion L.A.S.T. para Quejas:</b> Una respuesta modelo ante un reclamo.<br><br>✍️ <i>¡Decora con borde dorado de servicio 5 estrellas!</i>", "icon": "ph-pencil-line", "timer": 300, "customHtml": ""},
            {"title": "Role-Playing: El Turista Enojado y el Emprendedor Sabio", "sub": "6/10 - Práctica en Vivo", "content": "Un estudiante actúa como un turista impaciente cuyo tour se retrasó por lluvia, y su compañero aplica el protocolo L.A.S.T. con calma y empatía.", "icon": "ph-chats", "timer": 300, "customHtml": ""},
            {"title": "Taller en Parejas: Encuesta de Satisfacción (NPS)", "sub": "7/10 - Medición de Calidad", "content": "Diseñen 3 preguntas con caritas felices 😊 😐 🙁 para que los turistas califiquen la experiencia de su producto turístico.", "icon": "ph-star", "timer": 300, "customHtml": ""},
            {"title": "Pregunta de Razonamiento", "sub": "8/10 - Pensamiento Ético", "content": "¿Por qué un cliente que tuvo una queja pero fue atendido con amabilidad y rapidez suele volverse el cliente más fiel y leal del negocio?", "icon": "ph-thumbs-up", "timer": 300, "customHtml": ""},
            {"title": "Plenaria: La Cultura de la Amabilidad Colombiana", "sub": "9/10 - Socialización", "content": "¿Cómo la calidez natural de nuestra gente es la mayor ventaja competitiva turística de Colombia en el mundo?", "icon": "ph-globe", "timer": 300, "customHtml": ""},
            {"title": "Síntesis y Sello en el Cuaderno", "sub": "10/10 - Cierre de Clase", "content": "✔️ <b>Concepto Aprendido:</b> Momentos de la verdad, protocolo L.A.S.T. y entrega con calidez.<br>✔️ <b>Evidencia Sellada:</b> Decálogo de Servicio 5 estrellas completado en el cuaderno.<br><br>🌟 ¡Atención de categoría mundial para tu producto!", "icon": "ph-check-circle", "timer": 300, "customHtml": ""}
        ]
    ],
    "5": [
        [
            {"title": "Turismo: Sostenibilidad y Sello Verde", "sub": "1/10 - Bitácora y Medio Ambiente", "content": "📅 <b>Fecha:</b> Hoy<br>📌 <b>Título:</b> 'Turismo Sostenible y Economía Circular'<br>🎯 <b>Meta:</b> Adaptar el producto turístico a los 7 principios de 'No Deje Rastro', eliminando residuos y beneficiando a la comunidad local.", "icon": "ph-plant", "timer": 300, "customHtml": ""},
            {"title": "El Turismo que Cuida vs. El Turismo que Destruye", "sub": "2/10 - Problema Real", "content": "El turismo masivo descontrolado llena los ríos de botellas plásticas, tala bosques para construir y desplaza a las familias campesinas. Nuestro objetivo es el <b>Turismo Regenerativo</b>: dejar el lugar mejor de lo que lo encontramos.", "icon": "ph-recycle", "timer": 300, "customHtml": ""},
            {"title": "Las 3 Patas de la Sostenibilidad", "sub": "3/10 - Triple Impacto", "content": "• 🌿 <b>Ambiental:</b> Cero plásticos, ahorro de agua y protección de fauna/flora.<br>• 👥 <b>Social:</b> Respeto a las costumbres campesinas y pago de precios justos a los artesanos.<br>• 💼 <b>Económico:</b> El dinero se queda circulando en el pueblo y no en multinacionales extranjeras.", "icon": "ph-shield-check", "timer": 300, "customHtml": ""},
            {"title": "Productos Km 0 (Kilómetro Cero)", "sub": "4/10 - Modelo Local", "content": "Consiste en utilizar materias primas cosechadas o fabricadas a menos de 50 km a la redonda. Apoya al agricultor vecino y evita la contaminación de transportar comida en camiones lejanos.", "icon": "ph-map-pin-line", "timer": 300, "customHtml": ""},
            {"title": "⏱️ Reto en el Cuaderno: El Certificado de Sello Verde de mi Producto", "sub": "5/10 - Esquema Ecológico", "content": "<b>Dibuja en tu cuaderno una medalla o sello ecológico con 3 compromisos reales:</b><br><br>• 🏅 <b>Diseño de la Medalla:</b> Dibuja un círculo verde con hojas y el nombre de tu producto.<br>• 💧 <b>Compromiso Ambiental:</b> ¿Cómo reduces o eliminas los residuos plásticos en tu bien o tour?<br>• 🌾 <b>Compromiso Km 0:</b> ¿Qué insumo o ingrediente local le compras a los campesinos de tu zona?<br>• 🤝 <b>Compromiso Comunitario:</b> ¿Cómo tu negocio apoya a las familias vecinas?<br><br>✍️ <i>¡Colorea con tonos verdes y tierra!</i>", "icon": "ph-pencil-line", "timer": 300, "customHtml": ""},
            {"title": "Ejemplo Inspirador: La Reserva Natural Comunitaria", "sub": "6/10 - Caso Exitoso", "content": "Una vereda que antes cazaba osos de anteojos se unió para crear senderos de avistamiento guiados por los mismos campesinos. ¡Ahora el oso vivo genera ingresos para toda la comunidad!", "icon": "ph-binoculars", "timer": 300, "customHtml": ""},
            {"title": "Taller en Parejas: Auditoría Ambiental Cruzada", "sub": "7/10 - Coevaluación", "content": "Revisa el producto de tu compañero: ¿Hay algún detalle que genere basura? ¿Cómo podrían reemplazarlo por materiales biodegradables o reutilizables?", "icon": "ph-tree", "timer": 300, "customHtml": ""},
            {"title": "Pregunta de Razonamiento", "sub": "8/10 - Pensamiento Crítico", "content": "¿Por qué un turista consciente prefiere comprar una artesanía hecha a mano en fique por una madre cabeza de hogar que un souvenir de plástico importado?", "icon": "ph-sparkle", "timer": 300, "customHtml": ""},
            {"title": "Plenaria: El Futuro del Planeta y el Turismo", "sub": "9/10 - Socialización", "content": "Conclusiones sobre cómo los jóvenes son los líderes del cambio hacia un turismo regenerativo y consciente.", "icon": "ph-globe-hemisphere-west", "timer": 300, "customHtml": ""},
            {"title": "Síntesis y Sello en el Cuaderno", "sub": "10/10 - Cierre de Clase", "content": "✔️ <b>Concepto Aprendido:</b> Triple impacto, cadena de valor Km 0 y principios de No Deje Rastro.<br>✔️ <b>Evidencia Sellada:</b> Sello Verde y compromisos ecológicos en el cuaderno.<br><br>🌟 ¡Tu producto ahora es un referente de sostenibilidad!", "icon": "ph-check-circle", "timer": 300, "customHtml": ""}
        ]
    ],
    "6": [
        [
            {"title": "Turismo: Marketing Digital y Redes Sociales", "sub": "1/10 - Bitácora y Promoción", "content": "📅 <b>Fecha:</b> Hoy<br>📌 <b>Título:</b> 'Marketing Digital, TikTok, Instagram y Storytelling'<br>🎯 <b>Meta:</b> Diseñar una campaña digital creativa para dar a conocer el producto turístico a miles de personas a través de internet.", "icon": "ph-device-mobile-camera", "timer": 300, "customHtml": ""},
            {"title": "El Turista Elige su Viaje por la Pantalla", "sub": "2/10 - Realidad Digital", "content": "Hoy en día, más del 85% de los viajeros deciden qué tour comprar o qué café visitar después de ver un video corto en TikTok o una foto espectacular en Instagram.", "icon": "ph-instagram-logo", "timer": 300, "customHtml": ""},
            {"title": "Los 3 Pilares del Marketing Turístico Digital", "sub": "3/10 - Estrategia Básica", "content": "1. 📱 <b>Contenido Visual Emocionante:</b> Videos verticales mostrando paisajes, texturas y sonrisas.<br>2. 📍 <b>Ubicación en Google Maps:</b> Para que el turista pueda llegar con su GPS sin perderse.<br>3. 💬 <b>Canal Directo de WhatsApp Business:</b> Respuestas automáticas amables y catálogo de fotos.", "icon": "ph-broadcast", "timer": 300, "customHtml": ""},
            {"title": "La Fórmula de un Video Viral (Reel de 30 Segundos)", "sub": "4/10 - Estructura de Video", "content": "• 🪝 <b>Gancho (Segundos 0-3):</b> Una toma impactante o pregunta sorpresa.<br>• 🎬 <b>Cuerpo (Segundos 4-22):</b> La experiencia en acción (preparando el producto o caminando por el mirador).<br>• 📢 <b>Llamado a la Acción (Segundos 23-30):</b> <i>'¡Comenta VIAJE para enviarte la ubicación por DM!'</i>", "icon": "ph-video-camera", "timer": 300, "customHtml": ""},
            {"title": "⏱️ Reto en el Cuaderno: Storyboard de Reel Publicitario", "sub": "5/10 - Esquema Gráfico", "content": "<b>Dibuja en tu cuaderno el guion gráfico (Storyboard) de tu video de TikTok/Reel:</b><br><br>• 📱 <b>Dibuja 3 marcos de pantalla de celular verticales:</b><br>- <b>Marco 1 (El Gancho):</b> Dibuja la escena inicial con el texto que aparecerá en pantalla.<br>- <b>Marco 2 (La Experiencia):</b> Dibuja el producto o el tour en su mejor momento.<br>- <b>Marco 3 (Llamado a la Acción):</b> Dibuja el botón de WhatsApp y la frase final.<br><br>• 🎵 <b>Música de Fondo:</b> Escribe qué tipo de música campesina, instrumental o moderna sonará.<br><br>✍️ <i>¡Usa colores vivos y escribe los textos promocionales!</i>", "icon": "ph-pencil-line", "timer": 300, "customHtml": ""},
            {"title": "El Perfil de Google Maps que Atrae Clientes", "sub": "6/10 - Herramienta Gratuita", "content": "Anotamos los 4 elementos obligatorios en un perfil de Google Maps: Nombre comercial claro, fotos de alta calidad, horario de atención y reseñas de 5 estrellas con comentarios de clientes felices.", "icon": "ph-map-pin", "timer": 300, "customHtml": ""},
            {"title": "Taller en Parejas: Redacción de Mensaje de WhatsApp", "sub": "7/10 - Atención Digital", "content": "Redacta el mensaje de bienvenida automático que recibirá un turista extranjero cuando escriba a tu WhatsApp pidiendo información de tu producto.", "icon": "ph-whatsapp-logo", "timer": 300, "customHtml": ""},
            {"title": "Pregunta de Razonamiento", "sub": "8/10 - Pensamiento Crítico", "content": "¿Por qué mostrar el proceso artesanal real de elaboración de un producto en un video genera muchas más ventas que colocar solo una foto fija con el precio?", "icon": "ph-camera", "timer": 300, "customHtml": ""},
            {"title": "Plenaria: La Ética en las Redes Sociales", "sub": "9/10 - Responsabilidad Digital", "content": "Hablamos sobre la importancia de no hacer publicidad engañosa: lo que mostramos en redes debe ser exactamente lo que el turista vivirá en persona.", "icon": "ph-shield", "timer": 300, "customHtml": ""},
            {"title": "Síntesis y Sello en el Cuaderno", "sub": "10/10 - Cierre de Clase", "content": "✔️ <b>Concepto Aprendido:</b> Storyboard para redes sociales, WhatsApp Business y presencia en Google Maps.<br>✔️ <b>Evidencia Sellada:</b> Guion gráfico de 3 pantallas de celular en el cuaderno.<br><br>🌟 ¡Campaña digital lista para conquistar turistas!", "icon": "ph-check-circle", "timer": 300, "customHtml": ""}
        ]
    ],
    "7": [
        [
            {"title": "Turismo: Alianzas y Cadena de Valor", "sub": "1/10 - Bitácora y Redes de Negocios", "content": "📅 <b>Fecha:</b> Hoy<br>📌 <b>Título:</b> 'Alianzas Estratégicas y Ecosistema Turístico'<br>🎯 <b>Meta:</b> Aprender a asociarse con hoteles, restaurantes, transportadores y tiendas locales para vender el producto en múltiples vitrinas.", "icon": "ph-tree-structure", "timer": 300, "customHtml": ""},
            {"title": "Nadie Crece Solo en el Turismo", "sub": "2/10 - Caso Real", "content": "Si vendes café empacado o mermeladas, no te quedes esperando en tu casa a que el turista pase: ¡haz un convenio con el mejor hotel del pueblo para colocar tus productos en el minibar o en la recepción!", "icon": "ph-handshake", "timer": 300, "customHtml": ""},
            {"title": "Los 4 Eslabones de la Cadena Turística", "sub": "3/10 - Red de Colaboración", "content": "1. 🚕 <b>Transporte:</b> Taxis y chivas que traen y llevan a los turistas.<br>2. 🏨 <b>Alojamiento:</b> Hoteles, hostales y glampings.<br>3. 🍲 <b>Alimentación:</b> Restaurantes, fondas típicas y cafeterías.<br>4. 🎁 <b>Atractivos y Souvenirs:</b> Tu producto o servicio innovador.", "icon": "ph-circles-three-plus", "timer": 300, "customHtml": ""},
            {"title": "El Modelo de Ganar-Ganar (Comisión Comercial)", "sub": "4/10 - Acuerdo Justo", "content": "Le ofreces a una agencia de viajes un 10% de comisión por cada turista que envíen a tu tour o por cada producto que vendan en su vitrina. Ellos ganan dinero extra sin esfuerzo y tú ganas muchos clientes nuevos.", "icon": "ph-percent", "timer": 300, "customHtml": ""},
            {"title": "⏱️ Reto en el Cuaderno: El Mapa de Alianzas de mi Negocio", "sub": "5/10 - Esquema Estratégico", "content": "<b>Dibuja en tu cuaderno el Mapa de Redes de tu Producto:</b><br><br>• 🏢 <b>Centro (Tu Producto Turístico):</b> Dibuja un círculo grande con tu logo.<br>• 🏨 <b>Nodo 1 (Hotel / Hostal Aliado):</b> Dibuja el hotel y describe la alianza (ej: <i>'Folleto en recepción y muestra gratis'</i>).<br>• 🍴 <b>Nodo 2 (Restaurante Típico):</b> Alianza para ofrecer tu postre/souvenir en la carta.<br>• 🚐 <b>Nodo 3 (Guía / Transportador):</b> Alianza para traer grupos al sendero.<br><br>✍️ <i>¡Conecta todos los nodos con flechas de colores bidireccionales!</i>", "icon": "ph-pencil-line", "timer": 300, "customHtml": ""},
            {"title": "Caso de Éxito: La Ruta de los Sabores Unidos", "sub": "6/10 - Trabajo en Equipo", "content": "Cinco pequeños campesinos con productos diferentes (queso, café, miel, arepas y artesanías) crearon un pasaporte turístico conjunto. ¡Los turistas visitan los 5 negocios en un solo día!", "icon": "ph-users-three", "timer": 300, "customHtml": ""},
            {"title": "Taller en Parejas: Negociación de una Alianza", "sub": "7/10 - Práctica de Negocios", "content": "Un estudiante representa al dueño de un hotel prestigioso y el otro al creador del producto turístico. Negocian un acuerdo de comisión justo en 2 minutos.", "icon": "ph-chats-circle", "timer": 300, "customHtml": ""},
            {"title": "Pregunta de Razonamiento", "sub": "8/10 - Pensamiento Estratégico", "content": "¿Por qué competir de manera egoísta y destructiva arruina a los pueblos turísticos, mientras que cooperar en red hace que todos ganen más?", "icon": "ph-brain", "timer": 300, "customHtml": ""},
            {"title": "Plenaria: La Fuerza del Cooperativismo Rural", "sub": "9/10 - Socialización", "content": "Debate guiado sobre cómo las asociaciones comunitarias han transformado el campo colombiano.", "icon": "ph-chalkboard-teacher", "timer": 300, "customHtml": ""},
            {"title": "Síntesis y Sello en el Cuaderno", "sub": "10/10 - Cierre de Clase", "content": "✔️ <b>Concepto Aprendido:</b> Cadena de valor turística, acuerdos de comisión y mapa de alianzas.<br>✔️ <b>Evidencia Sellada:</b> Mapa de red de aliados completado en el cuaderno.<br><br>🌟 ¡Tu producto ahora cuenta con una red de apoyo comercial!", "icon": "ph-check-circle", "timer": 300, "customHtml": ""}
        ]
    ],
    "8": [
        [
            {"title": "Turismo: Gran Feria de Emprendimiento y Cierre", "sub": "1/10 - Bitácora y Graduación", "content": "📅 <b>Fecha:</b> Hoy<br>📌 <b>Título:</b> 'Gran Feria de Emprendimiento y Sello de Oro'<br>🎯 <b>Meta:</b> Presentar el Modelo de Negocio Integral (Canvas Turístico), evaluar el impacto del proyecto y recibir la acreditación final como Emprendedor Turístico.", "icon": "ph-trophy", "timer": 300, "customHtml": ""},
            {"title": "El Gran Cierre de 8 Semanas de Innovación", "sub": "2/10 - Mirada Retrospectiva", "content": "Comenzaste con una idea simple en la Semana 1, diseñaste tu prototipo en la Semana 2, hiciste tu lanzamiento en la Semana 3 y consolidaste calidad, sostenibilidad, marketing y alianzas en las siguientes semanas. ¡Hoy eres un verdadero creador de valor!", "icon": "ph-star-four", "timer": 300, "customHtml": ""},
            {"title": "El Lienzo de Negocio Turístico (Canvas Simplificado)", "sub": "3/10 - Síntesis Maestra", "content": "• 1. <b>Propuesta de Valor:</b> ¿Qué experiencia mágica ofrecemos?<br>• 2. <b>Clientes:</b> ¿Quién nos compra?<br>• 3. <b>Canales:</b> ¿Cómo nos encuentran (Redes, Alianzas)?<br>• 4. <b>Ingresos:</b> ¿Cómo ganamos dinero?<br>• 5. <b>Impacto Verde:</b> ¿Cómo cuidamos el planeta?", "icon": "ph-squares-four", "timer": 300, "customHtml": ""},
            {"title": "La Evaluación de Impacto Comunitario", "sub": "4/10 - Huella Positiva", "content": "Un negocio no solo se mide por cuánto dinero gana, sino por cuántas sonrisas genera, cuántos empleos locales crea y cuánto cuida las tradiciones de nuestra tierra.", "icon": "ph-heart", "timer": 300, "customHtml": ""},
            {"title": "⏱️ Reto en el Cuaderno: El Lienzo Canvas y el Sello de Oro", "sub": "5/10 - Cuadro Maestro Final", "content": "<b>Dibuja en tu cuaderno el Lienzo Final de tu Negocio en 4 cuadrantes:</b><br><br><div style='display:grid; grid-template-columns:1fr 1fr; gap:8px; font-size:0.9rem;'><div style='background:#EFF6FF; padding:8px; border-radius:6px;'><b>1. MI PRODUCTO & VALOR:</b><br>Nombre, bien/servicio y qué lo hace único.</div><div style='background:#ECFDF5; padding:8px; border-radius:6px;'><b>2. MIS CLIENTES & PRECIO:</b><br>A quién va dirigido y precio de venta.</div><div style='background:#FEF3C7; padding:8px; border-radius:6px;'><b>3. CANALES & REDES:</b><br>Instagram, WhatsApp y aliados clave.</div><div style='background:#FDF2F8; padding:8px; border-radius:6px;'><b>4. IMPACTO SOSTENIBLE:</b><br>Cero plástico y apoyo a la comunidad.</div></div><br>✍️ <i>¡Dibuja en el centro el Sello de Oro de Emprendedor Turístico!</i>", "icon": "ph-pencil-line", "timer": 300, "customHtml": ""},
            {"title": "Presentación 'Shark Tank' Final", "sub": "6/10 - Exposición Magistral", "content": "Cada equipo tiene 90 segundos para exponer su lienzo final ante el jurado de la clase y responder una pregunta del público.", "icon": "ph-podium", "timer": 300, "customHtml": ""},
            {"title": "Coevaluación y Entrega de Medallas Simbólicas", "sub": "7/10 - Reconocimiento entre Pares", "content": "Los compañeros entregan votos al: 1) Producto más sostenible, 2) Producto más innovador, 3) Mejor presentación y oratoria.", "icon": "ph-medal", "timer": 300, "customHtml": ""},
            {"title": "Compromiso con el Territorio", "sub": "8/10 - Juramento Emprendedor", "content": "Escribe en tu cuaderno una promesa personal: <i>'Me comprometo a proteger la riqueza natural y cultural de mi región a través de proyectos éticos e innovadores'</i>.", "icon": "ph-handshake", "timer": 300, "customHtml": ""},
            {"title": "Plenaria: Clausura del Curso de Turismo", "sub": "9/10 - Reflexión y Futuro", "content": "El docente hace el balance de los proyectos creados y motiva a los estudiantes a llevar estas ideas a la realidad con sus familias.", "icon": "ph-sparkle", "timer": 300, "customHtml": ""},
            {"title": "Síntesis y Graduación Oficial en el Cuaderno", "sub": "10/10 - Cierre del Periodo", "content": "✔️ <b>Proyecto Culminado:</b> Producto turístico desarrollado, testeado, comercializado y validado.<br>✔️ <b>Evidencia Sellada:</b> Lienzo Canvas final con Sello de Oro aprobado en el cuaderno.<br><br>🌟 ¡FELICITACIONES! Has culminado con honores el curso de Turismo Sostenible.", "icon": "ph-seal-check", "timer": 300, "customHtml": ""}
        ]
    ]
}

db["clases"]["turismo"] = turismo_data

with open("proyectorData.json", "w", encoding="utf-8") as f:
    json.dump(db, f, ensure_ascii=False, indent=2)

print("¡TURISMO ACTUALIZADO CON ÉXITO! Orientado al desarrollo de un producto (bien o servicio) con ciclo inicial de 3 semanas (Ideación -> Prototipado -> Lanzamiento y Venta), 8 semanas x 10 diapositivas x 300s.")
