import json

with open("proyectorData.json", "r", encoding="utf-8") as f:
    db = json.load(f)

# FÍSICA 6° - Conceptos Cotidianos, Cero Fórmulas Matemáticas, Instrucciones para Dibujos y Esquemas en Cuaderno
# 8 Semanas x 10 Diapositivas x 300s
fisica6_data = {
    "1": [
        [
            {"title": "Física 6°: ¿Qué es el Movimiento?", "sub": "1/10 - Preparación y Bitácora", "content": "📅 <b>Fecha:</b> Hoy<br>📌 <b>Título:</b> 'El Movimiento y el Punto de Referencia'<br>🎯 <b>Meta:</b> Comprender que el movimiento depende de los ojos de quien mira (Punto de Referencia) a través de ejemplos cotidianos.", "icon": "ph-trend-up", "timer": 300, "customHtml": ""},
            {"title": "¿Quién se Mueve Realmente?", "sub": "2/10 - Situación Cotidiana", "content": "<b>Imagina esta escena de tu vida:</b><br>Vas sentado en un autobús escolar mirando por la ventana. Ves que los postes y los árboles pasan a toda velocidad hacia atrás. Tu amigo sentado al lado te dice: <i>'¡Estamos completamente quietos!'</i>. ¿Quién tiene la razón?", "icon": "ph-bus", "timer": 300, "customHtml": ""},
            {"title": "El Concepto Clave: El Punto de Referencia", "sub": "3/10 - Idea Fundamental", "content": "En la naturaleza <b>NADA está quieto por sí solo</b>:<br>• Para tu compañero de asiento: estás en <b>reposo</b> (quieto).<br>• Para una persona parada en la calle: estás en <b>movimiento</b> junto con el bus.<br>• ¡Para un astronauta en la Luna, todos nos movemos a miles de km/h porque la Tierra gira!", "icon": "ph-eye", "timer": 300, "customHtml": ""},
            {"title": "Esquema Visual: El Observador y el Paisaje", "sub": "4/10 - Modelo Gráfico", "content": "Observa cómo cambia la percepción según el observador:<br><div style='background:#F1F5F9; border-left:4px solid #3B82F6; padding:12px; border-radius:8px; margin-top:10px;'>🧍 <b>Observador A (En la acera):</b> Ve pasar el bus con sus pasajeros.<br>🪑 <b>Observador B (En el bus):</b> Ve la acera y los árboles correr hacia atrás.</div>", "icon": "ph-arrows-left-right", "timer": 300, "customHtml": ""},
            {"title": "⏱️ Reto de Dibujo en tu Cuaderno: El Pasajero y la Acera", "sub": "5/10 - Esquema Creativo", "content": "<b>Dibuja en tu cuaderno una escena dividida en 2 partes:</b><br>• 🚌 <b>Dibujo 1 (Dentro del Bus):</b> Dibuja a dos amigos sentados uno al lado del otro. Escribe al lado: <i>'En reposo mutuo'</i>.<br>• 🌳 <b>Dibujo 2 (Visto desde la Calle):</b> Dibuja el bus avanzando con una flecha verde y un árbol fijo en la acera. Escribe: <i>'En movimiento respecto a la acera'</i>.<br><br>✍️ <i>¡Colorea el bus y utiliza tu regla para trazar la calle!</i>", "icon": "ph-pencil-line", "timer": 300, "customHtml": ""},
            {"title": "Ejemplo Cotidiano: El Tren y la Luna", "sub": "6/10 - Pensamiento Crítico", "content": "¿Por qué cuando caminas de noche parece que la Luna te estuviera persiguiendo a todos lados?<br><br>Escribe en tu cuaderno una explicación sencilla con tus propias palabras.", "icon": "ph-moon", "timer": 300, "customHtml": ""},
            {"title": "Taller en Parejas: ¿Quién se Mueve?", "sub": "7/10 - Diálogo de Clase", "content": "Ponte de acuerdo con tu compañero:<br>Si caminas hacia adelante dentro de un avión en pleno vuelo, ¿te estás moviendo más rápido que el avión o a la misma velocidad? Argumenten su respuesta.", "icon": "ph-airplane-takeoff", "timer": 300, "customHtml": ""},
            {"title": "Desafío de Observación", "sub": "8/10 - Pregunta Desafío", "content": "Si dejas caer una moneda mientras vas en una patineta en movimiento recto y suave:<br>¿La moneda caerá en tus pies, más adelante o más atrás?<br><br>Anota tu predicción en el cuaderno con una frase.", "icon": "ph-question", "timer": 300, "customHtml": ""},
            {"title": "Plenaria: La Relatividad del Movimiento", "sub": "9/10 - Socialización", "content": "¿Por qué es imposible decir que algo se mueve sin aclarar primero respecto a qué objeto lo estamos comparando? Conclusiones en el tablero.", "icon": "ph-chalkboard-teacher", "timer": 300, "customHtml": ""},
            {"title": "Síntesis y Sello en el Cuaderno", "sub": "10/10 - Cierre de Clase", "content": "✔️ <b>Concepto Aprendido:</b> El movimiento siempre es relativo al punto de referencia.<br>✔️ <b>Evidencia Sellada:</b> Dibujo comparativo del bus y la acera en el cuaderno.<br><br>🌟 ¡Gran inicio en la comprensión del mundo físico!", "icon": "ph-check-circle", "timer": 300, "customHtml": ""}
        ]
    ],
    "2": [
        [
            {"title": "Física 6°: Trayectorias y Caminos", "sub": "1/10 - Preparación y Bitácora", "content": "📅 <b>Fecha:</b> Hoy<br>📌 <b>Título:</b> 'Trayectorias Curvas, Rectas y Desplazamiento'<br>🎯 <b>Meta:</b> Reconocer las diferentes formas en que los objetos viajan en el espacio y diferenciar el camino recorrido de la línea directa.", "icon": "ph-path", "timer": 300, "customHtml": ""},
            {"title": "¿Qué Huella Deja el Movimiento?", "sub": "2/10 - Pregunta Cotidiana", "content": "<b>Observa estos ejemplos:</b><br>• El esquí sobre la nieve deja una línea tallada.<br>• Un avión en el cielo deja una estela blanca.<br>• Una mariposa vuela de flor en flor dando vueltas en el aire.<br>Esa línea invisible o visible que dibuja un cuerpo al viajar se llama <b>Trayectoria</b>.", "icon": "ph-butterfly", "timer": 300, "customHtml": ""},
            {"title": "Los 3 Tipos Principales de Trayectorias", "sub": "3/10 - Concepto Fundamental", "content": "1. <b>Rectilínea:</b> Una manzana cayendo en línea recta del árbol.<br>2. <b>Curvilínea o Zigzag:</b> El vuelo juguetón de una abeja o un río serpenteante.<br>3. <b>Circular:</b> La rueda de la fortuna o las manecillas de un reloj.", "icon": "ph-arrows-split", "timer": 300, "customHtml": ""},
            {"title": "Diferencia Vital: Camino Recorrido vs Línea Directa", "sub": "4/10 - Esquema Explicativo", "content": "• <b>Camino Recorrido:</b> Toda la distancia que caminaste dando vueltas por los pasillos.<br>• <b>Desplazamiento:</b> La flecha recta desde donde empezaste hasta donde terminaste.<br>¡Si das una vuelta completa al parque y vuelves a tu casa, tu desplazamiento final es CERO!", "icon": "ph-arrow-bend-right-down", "timer": 300, "customHtml": ""},
            {"title": "⏱️ Reto de Dibujo en tu Cuaderno: El Vuelo de la Abeja", "sub": "5/10 - Esquema Creativo", "content": "<b>Dibuja en tu cuaderno una página ilustrada con:</b><br>• 🌸 <b>Flor de Inicio y Flor de Llegada:</b> En extremos opuestos de la página.<br>• 🐝 <b>Línea Curva y con Espirales (Azul):</b> Dibuja el vuelo juguetón de la abeja dando vueltas. Rotula: <i>'Trayectoria / Camino Recorrido'</i>.<br>• 🏹 <b>Flecha Recta con Regla (Roja):</b> Desde la flor inicial hasta la flor final. Rotula: <i>'Desplazamiento Directo'</i>.<br><br>✍️ <i>¡Utiliza dos colores bien contrastantes para que se note la diferencia!</i>", "icon": "ph-pencil-line", "timer": 300, "customHtml": ""},
            {"title": "Ejemplo en el Deporte: El Tiro con Arco y el Balón", "sub": "6/10 - Aplicación Cotidiana", "content": "¿Qué tipo de trayectoria describe un balón de fútbol cuando el arquero hace un saque largo hacia el medio campo? (Trayectoria parabólica/curva). Escríbelo en tu cuaderno.", "icon": "ph-soccer-ball", "timer": 300, "customHtml": ""},
            {"title": "Reto en Parejas: El Laberinto de la Escuela", "sub": "7/10 - Dinámica de Observación", "content": "Piensen en el camino desde la puerta del colegio hasta su salón:<br>¿Cuántas curvas y escaleras tiene la trayectoria real? ¿Cómo sería la flecha recta si pudiéramos atravesar las paredes?", "icon": "ph-buildings", "timer": 300, "customHtml": ""},
            {"title": "Pregunta de Pensamiento Científico", "sub": "8/10 - Razonamiento", "content": "Un atleta da 4 vueltas completas a la pista olímpica de atletismo (recorrió 1.600 metros) y termina exactamente en la línea de meta donde empezó. ¿Cuánto fue su desplazamiento?", "icon": "ph-medal", "timer": 300, "customHtml": ""},
            {"title": "Plenaria: La Forma del Espacio", "sub": "9/10 - Socialización", "content": "¿Por qué los barcos y los aviones no viajan en líneas totalmente rectas en los mapas planos? Diálogo grupal guiado por el profesor.", "icon": "ph-globe-hemisphere-west", "timer": 300, "customHtml": ""},
            {"title": "Síntesis y Sello en el Cuaderno", "sub": "10/10 - Cierre de Clase", "content": "✔️ <b>Concepto Aprendido:</b> Trayectoria (camino real) vs Desplazamiento (línea recta inicio-fin).<br>✔️ <b>Evidencia Sellada:</b> Esquema de la abeja y las flores con colores en el cuaderno.<br><br>🌟 ¡Excelente trabajo gráfico y conceptual!", "icon": "ph-check-circle", "timer": 300, "customHtml": ""}
        ]
    ],
    "3": [
        [
            {"title": "Física 6°: La Rapidez en la Naturaleza", "sub": "1/10 - Preparación y Bitácora", "content": "📅 <b>Fecha:</b> Hoy<br>📌 <b>Título:</b> '¿Qué Significa ser Rápido? Comparando Velocidades'<br>🎯 <b>Meta:</b> Comprender el concepto intuitivo de rapidez a través de seres vivos y medios de transporte.", "icon": "ph-gauge", "timer": 300, "customHtml": ""},
            {"title": "¿Quién Tarda Menos en Llegar?", "sub": "2/10 - Pregunta Cotidiana", "content": "<b>Piensa en esta carrera:</b><br>Un caracol, una tortuga, un perro, una bicicleta y un avión salen al mismo tiempo para llegar a la tienda del pueblo.<br>¿Quién recorre más distancia en un solo segundo? ¿Quién necesita más tiempo para avanzar un solo metro?", "icon": "ph-sneaker-move", "timer": 300, "customHtml": ""},
            {"title": "El Concepto Clave: Rapidez Intuitiva", "sub": "3/10 - Idea Fundamental", "content": "La <b>Rapidez</b> es la cualidad que nos dice:<br>• Cuán aprisa cambia de lugar un cuerpo.<br>• <b>Mayor rapidez:</b> Recorrer mucha distancia en muy poco tiempo.<br>• <b>Menor rapidez:</b> Tardar mucho tiempo para avanzar una pequeña distancia.", "icon": "ph-lightning", "timer": 300, "customHtml": ""},
            {"title": "La Escala de Rapideces del Mundo Real", "sub": "4/10 - Comparativa Visual", "content": "• 🐌 <b>Caracol de jardín:</b> Muy lento (apenas unos milímetros por segundo).<br>• 🚶 <b>Persona caminando con calma:</b> Paso moderado.<br>• 🐆 <b>Guepardo / Chita:</b> El animal terrestre más veloz en persecución.<br>• 🦅 <b>Halcón Peregrino:</b> Cae en picada como una flecha.<br>• 🚀 <b>Cohete Espacial:</b> Sale de la atmósfera terrestre en segundos.", "icon": "ph-chart-line-up", "timer": 300, "customHtml": ""},
            {"title": "⏱️ Reto de Dibujo en tu Cuaderno: La Pista de Carreras de la Vida", "sub": "5/10 - Esquema Creativo", "content": "<b>Dibuja en tu cuaderno una pista con 4 carriles horizontales:</b><br>• 🐌 <b>Carril 1 (Súper Lento):</b> Dibuja un caracol con una línea corta.<br>• 🚲 <b>Carril 2 (Moderado):</b> Dibuja una bicicleta con una línea media.<br>• 🚗 <b>Carril 3 (Rápido):</b> Dibuja un carro de carreras con líneas de viento.<br>• ✈️ <b>Carril 4 (Ultra Rápido):</b> Dibuja un avión a reacción cruzando toda la hoja.<br><br>✍️ <i>¡Escribe debajo de cada uno una frase explicando por qué tiene esa rapidez!</i>", "icon": "ph-pencil-line", "timer": 300, "customHtml": ""},
            {"title": "Ejemplo en Casa: El Ventilador y las Manecillas", "sub": "6/10 - Observación Cotidiana", "content": "¿Por qué las aspas de un ventilador apagado se ven claramente, pero cuando lo pones en velocidad máxima se vuelven un círculo borroso invisible a los ojos?", "icon": "ph-fan", "timer": 300, "customHtml": ""},
            {"title": "Debate en Parejas: Rapidez vs Cuidado", "sub": "7/10 - Reflexión Ciudadana", "content": "¿Por qué cerca de los colegios y parques los carros deben bajar obligatoriamente su rapidez a paso lento? Anoten 2 razones en su cuaderno.", "icon": "ph-traffic-signal", "timer": 300, "customHtml": ""},
            {"title": "Pregunta de Razonamiento", "sub": "8/10 - Pensamiento Lógico", "content": "Si dos personas salen de la misma casa a las 7:00 AM hacia el colegio, pero una llega a las 7:15 AM y la otra a las 7:40 AM:<br>¿Cuál de las dos caminó con mayor rapidez? ¿Por qué?", "icon": "ph-clock", "timer": 300, "customHtml": ""},
            {"title": "Plenaria: La Rapidez en la Vida Cotidiana", "sub": "9/10 - Socialización", "content": "¿En qué momentos de la vida es bueno ser rápidos y en qué momentos es mejor ir con calma y paciencia? Puesta en común con el profesor.", "icon": "ph-users", "timer": 300, "customHtml": ""},
            {"title": "Síntesis y Sello en el Cuaderno", "sub": "10/10 - Cierre de Clase", "content": "✔️ <b>Concepto Aprendido:</b> La rapidez como relación intuitiva entre distancia recorrida y tiempo empleado.<br>✔️ <b>Evidencia Sellada:</b> Pista de 4 carriles ilustrada y coloreada en el cuaderno.<br><br>🌟 ¡Gran comprensión conceptual!", "icon": "ph-check-circle", "timer": 300, "customHtml": ""}
        ]
    ],
    "4": [
        [
            {"title": "Física 6°: Fuerzas de Contacto y a Distancia", "sub": "1/10 - Preparación y Bitácora", "content": "📅 <b>Fecha:</b> Hoy<br>📌 <b>Título:</b> 'Fuerzas: Empujones, Tirones y Fuerzas Invisibles'<br>🎯 <b>Meta:</b> Identificar cómo las fuerzas cambian la forma, inician el movimiento o frenan los objetos en nuestro entorno.", "icon": "ph-hand-fist", "timer": 300, "customHtml": ""},
            {"title": "¿Qué Hace que las Cosas se Muevan o se Deformen?", "sub": "2/10 - Pregunta Cotidiana", "content": "<b>Observa estos hechos:</b><br>• Si pateas un balón, sale volando.<br>• Si aprietas una bola de plastilina, cambia de forma.<br>• Si acercas un imán a la nevera, se pega solo sin tocarlo.<br>En todos estos casos hay una <b>Fuerza</b> actuando.", "icon": "ph-hand-grabbing", "timer": 300, "customHtml": ""},
            {"title": "Los Dos Grandes Tipos de Fuerzas", "sub": "3/10 - Concepto Fundamental", "content": "1. <b>Fuerzas de Contacto:</b> Los cuerpos deben tocarse físicamente (empujar un carro, patear, halar una cuerda).<br>2. <b>Fuerzas a Distancia (Invisibles):</b> Actúan a través del espacio sin tocarse (la Gravedad de la Tierra, la atracción magnética de un imán).", "icon": "ph-magnet", "timer": 300, "customHtml": ""},
            {"title": "Las 3 Cosas que Puede Hacer una Fuerza", "sub": "4/10 - Esquema Explicativo", "content": "Una fuerza puede:<br>• 🚀 <b>Poner en movimiento</b> algo que estaba quieto.<br>• 🛑 <b>Frenar o desviar</b> algo que ya se movía.<br>• 🍞 <b>Deformar o aplastar</b> la materia (como amasar pan).", "icon": "ph-arrows-clockwise", "timer": 300, "customHtml": ""},
            {"title": "⏱️ Reto de Dibujo en tu Cuaderno: El Mapa de las Fuerzas", "sub": "5/10 - Esquema Creativo", "content": "<b>Dibuja en tu cuaderno dos cuadros comparativos:</b><br>• ⚽ <b>Cuadro A (Fuerza de Contacto):</b> Dibuja un pie pateando un balón de fútbol. Traza una flecha amarilla señalando el punto exacto de contacto.<br>• 🧲 <b>Cuadro B (Fuerza a Distancia):</b> Dibuja una herradura de imán atrayendo clips de papel que vuelan por el aire hacia él sin tocarlo todavía. Dibuja líneas punteadas invisibles.<br><br>✍️ <i>¡Escribe el título con marcador y colorea ambos dibujos!</i>", "icon": "ph-pencil-line", "timer": 300, "customHtml": ""},
            {"title": "Ejemplo en Casa: La Gravedad Invisible", "sub": "6/10 - Observación Cotidiana", "content": "¿Por qué cuando se te resbala un vaso de las manos SIEMPRE cae hacia el piso y nunca se queda flotando en el aire? Escribe qué fuerza invisible actúa.", "icon": "ph-drop", "timer": 300, "customHtml": ""},
            {"title": "Experimento Mental en Parejas", "sub": "7/10 - Dinámica de Clase", "content": "Tomen una hoja de papel usada y arrúguenla fuertemente hasta hacerla una bolita compacta:<br>¿Qué tipo de fuerza aplicaron con sus manos? ¿Fue de contacto o a distancia? ¿Qué le ocurrió a la forma del papel?", "icon": "ph-sparkle", "timer": 300, "customHtml": ""},
            {"title": "Desafío de Clasificación", "sub": "8/10 - Pregunta de Razonamiento", "content": "Clasifica en tu cuaderno como (Contacto) o (A Distancia):<br>1. Abrir la puerta de la nevera.<br>2. La Luna girando alrededor de la Tierra.<br>3. Tu cabello atraído por un globo frotado con lana.", "icon": "ph-list-checks", "timer": 300, "customHtml": ""},
            {"title": "Plenaria: Las Fuerzas que Mueven el Universo", "sub": "9/10 - Socialización", "content": "¿Qué pasaría en el mundo si de un momento a otro desaparecieran todas las fuerzas de atracción a distancia? Conclusiones en el tablero.", "icon": "ph-globe", "timer": 300, "customHtml": ""},
            {"title": "Síntesis y Sello en el Cuaderno", "sub": "10/10 - Cierre de Clase", "content": "✔️ <b>Concepto Aprendido:</b> Diferenciación clara entre fuerzas de contacto y fuerzas a distancia.<br>✔️ <b>Evidencia Sellada:</b> Cuadro comparativo ilustrado del balón y el imán en el cuaderno.<br><br>🌟 ¡Gran dominio conceptual de las fuerzas!", "icon": "ph-check-circle", "timer": 300, "customHtml": ""}
        ]
    ],
    "5": [
        [
            {"title": "Física 6°: La Inercia en el Diario Vivir", "sub": "1/10 - Preparación y Bitácora", "content": "📅 <b>Fecha:</b> Hoy<br>📌 <b>Título:</b> 'La Inercia: La Pereza Natural de los Cuerpos'<br>🎯 <b>Meta:</b> Comprender por qué las cosas quieren seguir quietas o seguir moviéndose y la importancia vital del cinturón de seguridad.", "icon": "ph-shield-check", "timer": 300, "customHtml": ""},
            {"title": "¿Por qué te Vas de Bruces al Frenar?", "sub": "2/10 - Pregunta Cotidiana", "content": "<b>Seguro has vivido esto:</b><br>Vas de pie en el bus. De repente, un perro se cruza y el chofer frena en seco. ¡Todo tu cuerpo sale disparado hacia adelante sin que nadie te empuje!<br>¿Por qué tu cuerpo intentó seguir avanzando?", "icon": "ph-warning-octagon", "timer": 300, "customHtml": ""},
            {"title": "El Concepto Clave: La Inercia", "sub": "3/10 - Idea Fundamental", "content": "La <b>Inercia</b> es la tendencia natural de todo objeto a mantener su estado:<br>• Si estás <b>quieto</b>, tu cuerpo quiere seguir quieto.<br>• Si vas <b>en movimiento</b>, tu cuerpo quiere seguir avanzando a la misma velocidad en línea recta hasta que una fuerza externa te detenga.", "icon": "ph-person-simple-throw", "timer": 300, "customHtml": ""},
            {"title": "El Truco del Mago y el Mantel", "sub": "4/10 - Ejemplo Fascinante", "content": "Los magos retiran un mantel de un tirón seco y los platos llenos de comida se quedan en su sitio sobre la mesa sin caerse. ¿Magia? ¡No, pura inercia!", "icon": "ph-magic-wand", "timer": 300, "customHtml": ""},
            {"title": "⏱️ Reto de Dibujo en tu Cuaderno: El Experimento de la Moneda y el Vaso", "sub": "5/10 - Esquema Creativo", "content": "<b>Dibuja en tu cuaderno el clásico experimento casero:</b><br>• 🥛 <b>Paso 1:</b> Dibuja un vaso de vidrio transparente con una tarjeta de cartón encima.<br>• 🪙 <b>Paso 2:</b> Dibuja una moneda pesada descansando sobre la tarjeta.<br>• 👆 <b>Paso 3:</b> Dibuja un dedo golpeando la tarjeta hacia un lado y una flecha punteada hacia abajo mostrando que la moneda cae DENTRO del vaso por inercia.<br><br>✍️ <i>¡Escribe al lado: 'La moneda quiere quedarse quieta por inercia'!</i>", "icon": "ph-pencil-line", "timer": 300, "customHtml": ""},
            {"title": "Seguridad Vial: El Cinturón de Seguridad", "sub": "6/10 - Aplicación que Salva Vidas", "content": "Explica en tu cuaderno por qué el cinturón de seguridad es la herramienta más importante de un vehículo, usando la palabra <b>Inercia</b>.", "icon": "ph-car-profile", "timer": 300, "customHtml": ""},
            {"title": "Taller en Parejas: La Inercia en la Bicicleta", "sub": "7/10 - Análisis de Caso", "content": "¿Qué ocurre si vas rápido en tu bicicleta y presionas con fuerza únicamente el freno de la llanta delantera? ¿Por qué la inercia te hace levantar la rueda trasera?", "icon": "ph-bicycle", "timer": 300, "customHtml": ""},
            {"title": "Pregunta de Pensamiento Crítico", "sub": "8/10 - Razonamiento", "content": "¿Quién tiene mayor inercia (mayor resistencia a frenar): un camión cargado de papas o un carrito de juguete? ¿Por qué la cantidad de masa influye en la inercia?", "icon": "ph-truck", "timer": 300, "customHtml": ""},
            {"title": "Plenaria: La Primera Ley de la Naturaleza", "sub": "9/10 - Socialización", "content": "Comentamos cómo Isaac Newton descubrió esta ley observando las cosas más sencillas de la vida diaria.", "icon": "ph-lightbulb", "timer": 300, "customHtml": ""},
            {"title": "Síntesis y Sello en el Cuaderno", "sub": "10/10 - Cierre de Clase", "content": "✔️ <b>Concepto Aprendido:</b> Principio de inercia y su aplicación en la seguridad cotidiana.<br>✔️ <b>Evidencia Sellada:</b> Esquema paso a paso de la moneda y el vaso en el cuaderno.<br><br>🌟 ¡Comprendes una de las leyes más famosas del universo!", "icon": "ph-check-circle", "timer": 300, "customHtml": ""}
        ]
    ],
    "6": [
        [
            {"title": "Física 6°: La Fricción o Rozamiento", "sub": "1/10 - Preparación y Bitácora", "content": "📅 <b>Fecha:</b> Hoy<br>📌 <b>Título:</b> 'La Fricción: El Freno Invisible del Mundo'<br>🎯 <b>Meta:</b> Comprender cómo la rugosidad de las superficies frena los objetos, nos permite caminar y genera calor.", "icon": "ph-hand-pointing", "timer": 300, "customHtml": ""},
            {"title": "¿Por qué se Detiene el Balón?", "sub": "2/10 - Pregunta Cotidiana", "content": "<b>Piensa en esto:</b><br>Pateas un balón de fútbol sobre el césped. Nadie lo toca, pero poco a poco se va frenando hasta quedar completamente quieto.<br>¿Qué fuerza lo detuvo? Si el piso fuera de hielo liso, ¿llegaría más lejos?", "icon": "ph-soccer-ball", "timer": 300, "customHtml": ""},
            {"title": "El Concepto Clave: La Fricción", "sub": "3/10 - Idea Fundamental", "content": "La <b>Fricción o Rozamiento</b> es la fuerza que se opone al movimiento cuando dos superficies se frotan entre sí:<br>• Todas las superficies tienen asperezas y dientes microscópicos que se traban entre sí.<br>• <b>Superficies rugosas (cemento, lija):</b> Mucha fricción.<br>• <b>Superficies lisas (hielo, jabón):</b> Poca fricción.", "icon": "ph-waves", "timer": 300, "customHtml": ""},
            {"title": "¿La Fricción es Buena o Mala?", "sub": "4/10 - El Dilema de la Fricción", "content": "• 🟢 <b>¡La necesitamos!</b> Gracias a la fricción podemos caminar sin caernos, frenar carros, encender fósforos y escribir con lápiz.<br>• 🔴 <b>A veces estorba:</b> Desgasta las llantas, calienta los motores y hace que las puertas chirríen (por eso les ponemos aceite).", "icon": "ph-thumbs-up", "timer": 300, "customHtml": ""},
            {"title": "⏱️ Reto de Dibujo en tu Cuaderno: Suela con Agarre vs Piso Resbaloso", "sub": "5/10 - Esquema Creativo", "content": "<b>Dibuja en tu cuaderno dos situaciones comparativas:</b><br>• 👟 <b>Dibujo 1 (Mucha Fricción / Seguro):</b> Dibuja la suela de una bota de montaña con grabados profundos agarrándose al asfalto rugoso. Dibuja una lupa que haga zoom a las asperezas trabadas.<br>• 🧼 <b>Dibujo 2 (Poca Fricción / Resbaladizo):</b> Dibuja un pie resbalando sobre un piso con agua y jabón.<br><br>✍️ <i>¡Colorea ambos dibujos y rotula: 'Agarre seguro' vs 'Peligro de caída'!</i>", "icon": "ph-pencil-line", "timer": 300, "customHtml": ""},
            {"title": "Experimento en Vivo: Frotarse las Manos", "sub": "6/10 - Sensación Térmica", "content": "Frota tus dos palmas de las manos rápidamente durante 15 segundos. ¿Qué sientes? (Calor). Escribe en tu cuaderno por qué la fricción siempre produce calor.", "icon": "ph-fire", "timer": 300, "customHtml": ""},
            {"title": "Taller en Parejas: El Aceite en la Cadena", "sub": "7/10 - Aplicación Práctica", "content": "¿Por qué cuando la cadena de la bicicleta suena chirriante y se siente pesada, le agregamos unas gotas de aceite lubricante? ¿Qué le hace el aceite a la fricción?", "icon": "ph-drop", "timer": 300, "customHtml": ""},
            {"title": "Pregunta Desafío de Pensamiento", "sub": "8/10 - Razonamiento", "content": "¿Cómo sería el mundo si de repente la fricción desapareciera por completo durante 5 minutos? (Nadie podría dar un paso, los carros no podrían frenar).", "icon": "ph-brain", "timer": 300, "customHtml": ""},
            {"title": "Plenaria: La Fricción en los Deportes", "sub": "9/10 - Socialización", "content": "Comparamos los zapatos de tacos para fútbol, los patines sobre hielo y la cera que se pone a las tablas de surf.", "icon": "ph-trophy", "timer": 300, "customHtml": ""},
            {"title": "Síntesis y Sello en el Cuaderno", "sub": "10/10 - Cierre de Clase", "content": "✔️ <b>Concepto Aprendido:</b> La fricción como fuerza que frena el movimiento y genera calor.<br>✔️ <b>Evidencia Sellada:</b> Dibujo comparativo de la suela de bota y el piso con jabón en el cuaderno.<br><br>🌟 ¡Gran entendimiento del rozamiento cotidiano!", "icon": "ph-check-circle", "timer": 300, "customHtml": ""}
        ]
    ],
    "7": [
        [
            {"title": "Física 6°: Máquinas Simples en la Casa", "sub": "1/10 - Preparación y Bitácora", "content": "📅 <b>Fecha:</b> Hoy<br>📌 <b>Título:</b> 'Palancas, Rampas y Poleas: Multiplicando Nuestra Fuerza'<br>🎯 <b>Meta:</b> Reconocer cómo herramientas sencillas de uso diario nos permiten levantar grandes pesos con poco esfuerzo.", "icon": "ph-wrench", "timer": 300, "customHtml": ""},
            {"title": "¿Cómo Levantamos Cosas Pesadas?", "sub": "2/10 - Pregunta Cotidiana", "content": "<b>Imagina este reto:</b><br>Quieres subir una nevera pesada al platón de un camión. A pulso vertical es imposible para dos personas. Pero si colocas una tabla larga inclinada (Rampa), ¡la suben rodando fácilmente!<br>¿Cómo nos ayudan las máquinas simples?", "icon": "ph-package", "timer": 300, "customHtml": ""},
            {"title": "Las 3 Máquinas Simples más Famosas", "sub": "3/10 - Concepto Fundamental", "content": "1. <b>La Palanca:</b> Una barra rígida que gira sobre un punto de apoyo (tijeras, cortaúñas, balancín).<br>2. <b>El Plano Inclinado (Rampa):</b> Reduce el esfuerzo a cambio de recorrer un camino más largo.<br>3. <b>La Polea:</b> Una rueda con cuerda que cambia la dirección de la fuerza para subir baldes.", "icon": "ph-gear", "timer": 300, "customHtml": ""},
            {"title": "La Ley Mágica de las Palancas", "sub": "4/10 - Principio Básico", "content": "<i>'Dame un punto de apoyo y moveré el mundo'</i> (Arquímedes).<br>Entre más lejos del punto de apoyo empujes la barra, ¡menos fuerza necesitas hacer con tus manos para levantar el objeto pesado!", "icon": "ph-arrows-out-line-horizontal", "timer": 300, "customHtml": ""},
            {"title": "⏱️ Reto de Dibujo en tu Cuaderno: El Balancín y la Rampa", "sub": "5/10 - Esquema Creativo", "content": "<b>Dibuja en tu cuaderno dos herramientas esenciales:</b><br>• 🎠 <b>Dibujo 1 (La Palanca del Parque):</b> Dibuja un subibaja o balancín. Señala con flechas: 1) Punto de Apoyo (el centro), 2) Esfuerzo (el niño que empuja), 3) Carga (el niño que sube).<br>• 📦 <b>Dibujo 2 (El Plano Inclinado):</b> Dibuja un camión y una tabla inclinada larga subiendo una caja pesada con ruedas.<br><br>✍️ <i>¡Utiliza tu regla para trazar la barra recta y la rampa!</i>", "icon": "ph-pencil-line", "timer": 300, "customHtml": ""},
            {"title": "Detectives de Máquinas Simples en la Cocina", "sub": "6/10 - Aplicación Cotidiana", "content": "Escribe en tu cuaderno <b>3 máquinas simples que haya en tu casa</b> (ej: el destapador de botellas, la carretilla, el cascanueces o el exprimidor de limones).", "icon": "ph-cooking-pot", "timer": 300, "customHtml": ""},
            {"title": "Taller en Parejas: ¿Por qué la Manija está al Extremo?", "sub": "7/10 - Observación Práctica", "content": "Miren la puerta del salón: ¿Por qué la manija para abrirla está en el extremo más alejado de las bisagras y nunca en el centro ni pegada a la bisagra?", "icon": "ph-door", "timer": 300, "customHtml": ""},
            {"title": "Pregunta de Razonamiento", "sub": "8/10 - Pensamiento Lógico", "content": "Para subir a la cima de una montaña muy alta en carro, ¿por qué la carretera no sube en línea recta empinada, sino que da muchas curvas suaves en zigzag?", "icon": "ph-mountain", "timer": 300, "customHtml": ""},
            {"title": "Plenaria: La Tecnología de los Antiguos", "sub": "9/10 - Historia y Cultura", "content": "¿Cómo lograron los antiguos egipcios e indígenas construir pirámides y templos gigantescos sin motores ni electricidad? (Usando palancas, rampas y rodillos).", "icon": "ph-bank", "timer": 300, "customHtml": ""},
            {"title": "Síntesis y Sello en el Cuaderno", "sub": "10/10 - Cierre de Clase", "content": "✔️ <b>Concepto Aprendido:</b> Las máquinas simples facilitan el trabajo ahorrando esfuerzo humano.<br>✔️ <b>Evidencia Sellada:</b> Esquema rotulado del balancín y la rampa en el cuaderno.<br><br>🌟 ¡Gran comprensión del ingenio mecánico!", "icon": "ph-check-circle", "timer": 300, "customHtml": ""}
        ]
    ],
    "8": [
        [
            {"title": "Física 6°: La Gravedad y el Peso", "sub": "1/10 - Preparación y Bitácora", "content": "📅 <b>Fecha:</b> Hoy<br>📌 <b>Título:</b> 'La Gravedad: El Abrazo Invisible de la Tierra'<br>🎯 <b>Meta:</b> Comprender por qué los objetos caen hacia el centro del planeta y por qué la Tierra mantiene a la atmósfera y a nosotros en su lugar.", "icon": "ph-planet", "timer": 300, "customHtml": ""},
            {"title": "¿Por qué las Personas del Polo Sur no se Caen?", "sub": "2/10 - Pregunta Cotidiana", "content": "<b>Piénsalo un segundo:</b><br>La Tierra es una esfera redonda que flota en el espacio. Si hay gente viviendo en Colombia, en Japón y en el Polo Sur... ¿por qué los que están 'abajo' no se caen al vacío del espacio?", "icon": "ph-globe-hemisphere-east", "timer": 300, "customHtml": ""},
            {"title": "El Concepto Clave: La Atracción Gravitacional", "sub": "3/10 - Idea Fundamental", "content": "La <b>Gravedad</b> es la fuerza con la que la Tierra hala TODO hacia su mismísimo centro:<br>• No existe 'arriba' o 'abajo' en el espacio exterior.<br>• 'Abajo' para cualquier persona del planeta significa <b>'hacia el centro de la Tierra'</b>.<br>• La gravedad también mantiene pegada la capa de aire (atmósfera) para que podamos respirar.", "icon": "ph-arrows-in-cardinal", "timer": 300, "customHtml": ""},
            {"title": "Diferencia Vital: Tu Masa vs Tu Peso", "sub": "4/10 - Concepto sin Fórmulas", "content": "• <b>Masa:</b> La cantidad de carne, huesos y materia que tiene tu cuerpo (es la misma aquí, en la Luna o flotando en Marte).<br>• <b>Peso:</b> La fuerza con que el planeta te hala hacia su suelo. ¡En la Luna pesarías 6 veces menos porque la Luna es más pequeña y hala con menos fuerza!", "icon": "ph-scales", "timer": 300, "customHtml": ""},
            {"title": "⏱️ Reto de Dibujo en tu Cuaderno: El Planeta y la Gravedad", "sub": "5/10 - Esquema Creativo", "content": "<b>Dibuja en tu cuaderno un esquema cósmico:</b><br>• 🌍 <b>Planeta Tierra Redondo:</b> Dibuja un círculo grande en el centro con los continentes y marca un punto rojo en el centro rotulado: <i>'Centro de la Tierra'</i>.<br>• 🧍 <b>4 Personas:</b> Dibuja a una persona en el Polo Norte, una en el Polo Sur, una a la izquierda y una a la derecha.<br>• ⬇️ <b>Flechas de Gravedad (Rojas):</b> Traza flechas desde los pies de cada persona apuntando directo hacia el centro del planeta.<br><br>✍️ <i>¡Escribe al lado: 'Para todos en el planeta, abajo es hacia el centro'!</i>", "icon": "ph-pencil-line", "timer": 300, "customHtml": ""},
            {"title": "Ejemplo en el Espacio: Los Astronautas Flotando", "sub": "6/10 - Exploración Espacial", "content": "¿Por qué los astronautas en la Estación Espacial dan saltos gigantescos o flotan al soltar una cuchara? Escribe en tu cuaderno qué ocurre cuando no hay suelo que los empuje.", "icon": "ph-rocket", "timer": 300, "customHtml": ""},
            {"title": "Experimento Mental en Parejas", "sub": "7/10 - Dinámica de Clase", "content": "Si dejas caer al mismo tiempo una piedra pesada y una pelota de goma pequeña:<br>¿Cuál toca el piso primero si las sueltas exactamente a la misma altura? ¡Sorpréndete al saber que caen al mismo tiempo!", "icon": "ph-sparkle", "timer": 300, "customHtml": ""},
            {"title": "Pregunta de Razonamiento", "sub": "8/10 - Pensamiento Científico", "content": "¿Por qué la Luna no se va volando perdida en el espacio infinito y se queda siempre dando vueltas alrededor de la Tierra?", "icon": "ph-moon-stars", "timer": 300, "customHtml": ""},
            {"title": "Plenaria: La Fuerza que Mantiene Unido el Universo", "sub": "9/10 - Socialización", "content": "Reflexión final sobre cómo la gravedad forma las estrellas, hace llover el agua de las nubes y mantiene a los océanos en su lugar.", "icon": "ph-sun", "timer": 300, "customHtml": ""},
            {"title": "Síntesis y Sello en el Cuaderno", "sub": "10/10 - Cierre de Periodo", "content": "✔️ <b>Concepto Aprendido:</b> La gravedad como fuerza de atracción universal hacia el centro de los planetas.<br>✔️ <b>Evidencia Sellada:</b> Esquema de la Tierra esférica y las 4 personas con flechas al centro en el cuaderno.<br><br>🌟 ¡FELICITACIONES! Has culminado con éxito las 8 Semanas de Física 6°.", "icon": "ph-trophy", "timer": 300, "customHtml": ""}
        ]
    ]
}

# FÍSICA 7° - Conceptos Cotidianos, Cero Fórmulas Matemáticas, Instrucciones para Dibujos y Esquemas en Cuaderno
# 8 Semanas x 10 Diapositivas x 300s
fisica7_data = {
    "1": [
        [
            {"title": "Física 7°: Los Estados de la Materia", "sub": "1/10 - Preparación y Bitácora", "content": "📅 <b>Fecha:</b> Hoy<br>📌 <b>Título:</b> 'El Baile de las Moléculas: Sólido, Líquido y Gas'<br>🎯 <b>Meta:</b> Comprender cómo el movimiento y la energía de las moléculas determinan si algo es duro como una roca, fluye como agua o se expande como humo.", "icon": "ph-atom", "timer": 300, "customHtml": ""},
            {"title": "¿Qué Pasa Dentro de un Cubo de Hielo?", "sub": "2/10 - Pregunta Cotidiana", "content": "<b>Observa en tu cocina:</b><br>Un cubo de hielo es duro y mantiene su forma. Si lo dejas al sol, se derrite en agua que toma la forma del vaso. Si lo calientas en una olla, ¡se convierte en vapor invisible y desaparece en el aire!<br>¿Cómo es posible que sea la misma sustancia en 3 formas tan distintas?", "icon": "ph-snowflake", "timer": 300, "customHtml": ""},
            {"title": "El Baile Molecular en los 3 Estados", "sub": "3/10 - Concepto Fundamental", "content": "• 🧊 <b>Sólido:</b> Moléculas muy unidas, abrazadas fuertemente; solo vibran en su puesto.<br>• 💧 <b>Líquido:</b> Moléculas con más energía, resbalan y se mueven unas sobre otras como personas en una fiesta.<br>• 💨 <b>Gas:</b> Moléculas llenas de energía, vuelan libres y chocan por todo el espacio disponible.", "icon": "ph-circles-three-plus", "timer": 300, "customHtml": ""},
            {"title": "El Cuarto Estado: El Plasma", "sub": "4/10 - Más Allá de los Gases", "content": "Cuando un gas se calienta a temperaturas extremas, se convierte en <b>Plasma</b>: el estado brillante de los rayos en una tormenta, los avisos de neón y el fuego ardiente del Sol.", "icon": "ph-lightning", "timer": 300, "customHtml": ""},
            {"title": "⏱️ Reto de Dibujo en tu Cuaderno: Los 3 Vasos Moleculares", "sub": "5/10 - Esquema Creativo", "content": "<b>Dibuja en tu cuaderno 3 vasos transparentes con sus bolitas moleculares:</b><br>• 1️⃣ <b>Vaso Sólido (Hielo):</b> Dibuja bolitas perfectamente ordenadas en filas apretadas. Escribe: <i>'Unidas y vibrando'</i>.<br>• 2️⃣ <b>Vaso Líquido (Agua):</b> Dibuja bolitas desordenadas en el fondo con pequeñas flechas de deslizamiento. Escribe: <i>'Fluyen y toman la forma del recipiente'</i>.<br>• 3️⃣ <b>Vaso Gas (Vapor):</b> Dibuja bolitas muy separadas escapando del vaso con flechas rápidas en todas direcciones. Escribe: <i>'Libres y expandidas'</i>.<br><br>✍️ <i>¡Colorea cada estado con azul claro, azul oscuro y gris!</i>", "icon": "ph-pencil-line", "timer": 300, "customHtml": ""},
            {"title": "Ejemplo en Casa: La Olla a Presión", "sub": "6/10 - Aplicación Cotidiana", "content": "¿Por qué la tapa de una olla con agua hirviendo empieza a saltar y a sonar? (Porque las moléculas de vapor empujan con fuerza para salir). Escríbelo en tu cuaderno.", "icon": "ph-cooking-pot", "timer": 300, "customHtml": ""},
            {"title": "Taller en Parejas: El Perfume en la Habitación", "sub": "7/10 - Fenómeno Cotidiano", "content": "Si alguien destapa un frasco de perfume en una esquina del salón, ¿por qué segundos después todos podemos olerlo al otro extremo? Explíquenlo con el movimiento de las moléculas de gas.", "icon": "ph-sparkle", "timer": 300, "customHtml": ""},
            {"title": "Pregunta de Razonamiento", "sub": "8/10 - Pensamiento Científico", "content": "¿Por qué no podemos atravesar una pared de concreto con la mano, pero sí podemos meter la mano fácilmente dentro de un balde con agua?", "icon": "ph-wall", "timer": 300, "customHtml": ""},
            {"title": "Plenaria: La Materia en el Universo", "sub": "9/10 - Socialización", "content": "¿Sabías que más del 99% de la materia visible en todo el universo está en estado de plasma en las estrellas? Conclusiones en el tablero.", "icon": "ph-sun", "timer": 300, "customHtml": ""},
            {"title": "Síntesis y Sello en el Cuaderno", "sub": "10/10 - Cierre de Clase", "content": "✔️ <b>Concepto Aprendido:</b> Estados de la materia explicados a través del movimiento molecular.<br>✔️ <b>Evidencia Sellada:</b> Esquema de los 3 vasos moleculares rotulado en el cuaderno.<br><br>🌟 ¡Gran inicio en la física molecular!", "icon": "ph-check-circle", "timer": 300, "customHtml": ""}
        ]
    ],
    "2": [
        [
            {"title": "Física 7°: Temperatura vs. Calor", "sub": "1/10 - Preparación y Bitácora", "content": "📅 <b>Fecha:</b> Hoy<br>📌 <b>Título:</b> 'El Calor es Energía en Viaje: Desmintiendo Mitos'<br>🎯 <b>Meta:</b> Diferenciar la temperatura (agitación) del calor (energía que viaja) y entender por qué el 'frío' no entra, sino que el calor se escapa.", "icon": "ph-thermometer", "timer": 300, "customHtml": ""},
            {"title": "El Gran Error del Lenguaje Cotidiano", "sub": "2/10 - Mito Científico", "content": "<b>¿Has escuchado esto en casa?</b><br><i>'¡Cierra la nevera que se le entra el frío!'</i> o <i>'¡Ponte un saco para que no te entre el frío!'</i>.<br>Científicamente, el 'frío' como energía NO EXISTE: lo que realmente ocurre es que <b>el calor se está escapando</b>.", "icon": "ph-warning", "timer": 300, "customHtml": ""},
            {"title": "La Diferencia Fundamental", "sub": "3/10 - Concepto Clave", "content": "• 🌡️ <b>Temperatura:</b> Es el termómetro que mide qué tan rápido se están moviendo y chocando las moléculas por dentro.<br>• 🔥 <b>Calor:</b> Es la energía térmica que <b>SIEMPRE viaja desde el cuerpo más caliente hacia el cuerpo más frío</b> de forma natural.", "icon": "ph-arrows-left-right", "timer": 300, "customHtml": ""},
            {"title": "¿Qué Hace un Saco de Lana en un Día Frío?", "sub": "4/10 - Ejemplo Real", "content": "Un saco de lana no tiene un motor caliente adentro: simplemente es un aislante que <b>atrapa tu propio calor corporal</b> para que no se escape hacia el aire frío de la calle.", "icon": "ph-t-shirt", "timer": 300, "customHtml": ""},
            {"title": "⏱️ Reto de Dibujo en tu Cuaderno: El Café Caliente y el Hielo", "sub": "5/10 - Esquema Creativo", "content": "<b>Dibuja en tu cuaderno dos escenas con flechas de calor:</b><br>• ☕ <b>Escena 1 (Taza de Chocolate Caliente):</b> Dibuja la taza humeante y traza flechas rojas saliendo del chocolate hacia el aire frío del cuarto. Escribe: <i>'El calor se escapa al ambiente'</i>.<br>• 🧊 <b>Escena 2 (Cubo de Hielo en la Mesa):</b> Dibuja el hielo y traza flechas rojas del aire del cuarto ENTRANDO al hielo para derretirlo. Escribe: <i>'El calor del ambiente entra al hielo'</i>.<br><br>✍️ <i>¡Recuerda la regla de oro: El calor siempre viaja de lo caliente a lo frío!</i>", "icon": "ph-pencil-line", "timer": 300, "customHtml": ""},
            {"title": "El Equilibrio Térmico en la Tina de Baño", "sub": "6/10 - Aplicación Cotidiana", "content": "Si mezclas un balde de agua hirviendo con un balde de agua helada, ¿qué temperatura final obtienes? (Agua tibia: alcanzaron el <b>Equilibrio Térmico</b>). Escríbelo en tu cuaderno.", "icon": "ph-bathtub", "timer": 300, "customHtml": ""},
            {"title": "Taller en Parejas: Tocar la Madera vs el Metal", "sub": "7/10 - Experimento Sensorial", "content": "Toquen la superficie de madera del pupitre y luego toquen la pata de metal:<br>¿Por qué el metal se siente 'más frío' si ambos llevan horas en el mismo salón a la misma temperatura? (El metal roba el calor de tu mano mucho más rápido).", "icon": "ph-hand-palm", "timer": 300, "customHtml": ""},
            {"title": "Pregunta de Pensamiento Crítico", "sub": "8/10 - Razonamiento", "content": "Si dejas una cuchara de metal dentro de una sopa caliente, al cabo de unos minutos el mango de la cuchara te quema los dedos. ¿Por qué ocurrió esto?", "icon": "ph-soup", "timer": 300, "customHtml": ""},
            {"title": "Plenaria: La Dirección del Calor", "sub": "9/10 - Socialización", "content": "¿Por qué es imposible que un vaso de agua tibia se caliente solo espontáneamente enfriando la mesa? Comentamos la ley natural del calor.", "icon": "ph-chalkboard-teacher", "timer": 300, "customHtml": ""},
            {"title": "Síntesis y Sello en el Cuaderno", "sub": "10/10 - Cierre de Clase", "content": "✔️ <b>Concepto Aprendido:</b> El calor es energía en tránsito que viaja siempre de lo caliente a lo frío.<br>✔️ <b>Evidencia Sellada:</b> Esquema de la taza de chocolate y el hielo con flechas de calor en el cuaderno.<br><br>🌟 ¡Desmentiste con ciencia los mitos cotidianos!", "icon": "ph-check-circle", "timer": 300, "customHtml": ""}
        ]
    ],
    "3": [
        [
            {"title": "Física 7°: Las 3 Formas de Viajar del Calor", "sub": "1/10 - Preparación y Bitácora", "content": "📅 <b>Fecha:</b> Hoy<br>📌 <b>Título:</b> 'Conducción, Convección y Radiación en la Naturaleza'<br>🎯 <b>Meta:</b> Identificar cómo se propaga el calor en sólidos (contacto), fluidos (corrientes de aire/agua) y en el vacío del espacio (rayos de luz).", "icon": "ph-fire", "timer": 300, "customHtml": ""},
            {"title": "¿Cómo Llega el Calor del Sol a la Tierra?", "sub": "2/10 - Pregunta Cotidiana", "content": "<b>Piénsalo:</b><br>Entre el Sol y la Tierra hay 150 millones de kilómetros de espacio completamente vacío (sin aire, sin cables, sin metales).<br>¿Cómo hace el calor del Sol para llegar a nuestra piel y calentarnos en un día soleado?", "icon": "ph-sun-horizon", "timer": 300, "customHtml": ""},
            {"title": "Los 3 Caminos del Calor", "sub": "3/10 - Concepto Fundamental", "content": "1. <b>Conducción:</b> En sólidos por contacto directo de molécula a molécula (la sartén caliente).<br>2. <b>Convección:</b> En líquidos y gases mediante corrientes (el aire caliente sube y el frío baja).<br>3. <b>Radiación:</b> En forma de ondas invisibles que viajan incluso en el vacío (el Sol, una fogata).", "icon": "ph-arrows-split", "timer": 300, "customHtml": ""},
            {"title": "¿Por qué el Aire Caliente Sube?", "sub": "4/10 - El Globo Aerostático", "content": "Cuando el aire se calienta, sus moléculas se separan, se vuelve más liviano y sube flotando. Por eso los globos aerostáticos tienen un soplete de fuego para elevarse en el cielo.", "icon": "ph-balloon", "timer": 300, "customHtml": ""},
            {"title": "⏱️ Reto de Dibujo en tu Cuaderno: La Fogata Campesina con Olla", "sub": "5/10 - Esquema Creativo", "content": "<b>Dibuja en tu cuaderno una escena campestre completa con los 3 métodos:</b><br>• 🔥 <b>La Fogata:</b> Dibuja leños encendidos.<br>• 🍲 <b>La Olla de Metal:</b> Dibuja una olla sobre el fuego con una cuchara de metal adentro. Señala con una flecha roja: <i>'1. Conducción (Cuchara y olla caliente)'</i>.<br>• 🌪️ <b>El Humo y el Agua:</b> Dibuja el agua hirviendo en círculos y el humo subiendo al cielo. Señala: <i>'2. Convección (El fluido caliente sube)'</i>.<br>• 🖐️ <b>Unas Manos al Lado:</b> Dibuja unas manos calentándose a los lados sin tocar el fuego. Señala: <i>'3. Radiación (Ondas térmicas a distancia)'</i>.<br><br>✍️ <i>¡Usa colores vivos para diferenciar las 3 formas!</i>", "icon": "ph-pencil-line", "timer": 300, "customHtml": ""},
            {"title": "Ejemplo en la Casa: El Acondicionador de Aire", "sub": "6/10 - Aplicación Cotidiana", "content": "¿Por qué los aires acondicionados se instalan arriba cerca al techo y los calentadores se colocan abajo en el piso? (Por las corrientes de convección). Escríbelo en tu cuaderno.", "icon": "ph-fan", "timer": 300, "customHtml": ""},
            {"title": "Taller en Parejas: Los Mangos de Plástico de las Ollas", "sub": "7/10 - Seguridad en la Cocina", "content": "¿Por qué los mangos de las sartenes son de baquelita (plástico duro) o madera y nunca de cobre puro? ¿Qué propiedad de conducción térmica tienen esos materiales?", "icon": "ph-cooking-pot", "timer": 300, "customHtml": ""},
            {"title": "Pregunta de Razonamiento", "sub": "8/10 - Pensamiento Científico", "content": "En un día soleado en la playa, ¿por qué la arena de la orilla quema los pies intensamente mientras que el agua del mar se siente fresca?", "icon": "ph-umbrella", "timer": 300, "customHtml": ""},
            {"title": "Plenaria: La Brisa Marina y el Viento", "sub": "9/10 - Fenómenos del Planeta", "content": "Explicamos cómo las corrientes de convección gigantescas en la atmósfera crean los vientos, las tormentas y los huracanes en la Tierra.", "icon": "ph-wind", "timer": 300, "customHtml": ""},
            {"title": "Síntesis y Sello en el Cuaderno", "sub": "10/10 - Cierre de Clase", "content": "✔️ <b>Concepto Aprendido:</b> Identificación clara de Conducción, Convección y Radiación térmica.<br>✔️ <b>Evidencia Sellada:</b> Esquema de la fogata campesina y la olla en el cuaderno con colores.<br><br>🌟 ¡Gran comprensión de la energía térmica!", "icon": "ph-check-circle", "timer": 300, "customHtml": ""}
        ]
    ],
    "4": [
        [
            {"title": "Física 7°: ¿Qué es una Onda?", "sub": "1/10 - Preparación y Bitácora", "content": "📅 <b>Fecha:</b> Hoy<br>📌 <b>Título:</b> 'Ondas: Viajeras de Energía sin Llevar Materia'<br>🎯 <b>Meta:</b> Comprender cómo viaja la energía en cuerdas, agua, sonido y luz a través del concepto de onda.", "icon": "ph-waves", "timer": 300, "customHtml": ""},
            {"title": "La Ola en el Estadio de Fútbol", "sub": "2/10 - Analogía Cotidiana", "content": "<b>Imagina el estadio lleno de hinchas:</b><br>La gente se pone de pie, levanta los brazos y se vuelve a sentar en orden. La 'Ola' recorre todo el estadio a gran velocidad... ¡pero ninguna persona se movió de su asiento!<br>Así viaja exactamente una <b>Onda</b>.", "icon": "ph-users-three", "timer": 300, "customHtml": ""},
            {"title": "El Concepto Clave: ¿Qué Viaja en una Onda?", "sub": "3/10 - Idea Fundamental", "content": "Una <b>Onda</b> transporta <b>ENERGÍA</b>, pero <b>NO transporta materia</b>:<br>• Cuando lanzas una piedra a un estanque de agua, la piedra genera olas circulares.<br>• Si hay un patito de hule flotando, el patito solo sube y baja en su lugar, ¡no se va con la ola hasta la orilla!", "icon": "ph-drop", "timer": 300, "customHtml": ""},
            {"title": "Las Partes de una Onda Sencilla", "sub": "4/10 - Anatomía de la Onda", "content": "• 🏔️ <b>Cresta:</b> El punto más alto de la montaña de la onda.<br>• 🕳️ <b>Valle:</b> El punto más profundo del hueco de la onda.<br>• 📏 <b>Longitud de Onda:</b> La distancia entre cresta y cresta.<br>• ⏱️ <b>Frecuencia:</b> Cuántas olas pasan por segundo frente a ti.", "icon": "ph-chart-line-up", "timer": 300, "customHtml": ""},
            {"title": "⏱️ Reto de Dibujo en tu Cuaderno: La Piedra en el Estanque y la Cuerda", "sub": "5/10 - Esquema Creativo", "content": "<b>Dibuja en tu cuaderno una página con 2 esquemas:</b><br>• 🦆 <b>Dibujo 1 (El Patito en el Agua):</b> Dibuja círculos de ondas en el agua y un patito de hule con flechas verticales que muestren que solo sube y baja en su puesto.<br>• 〰️ <b>Dibujo 2 (La Cuerda Ondulante):</b> Traza con tu regla una línea ondulada perfecta y rotula con colores: 1) Cresta (arriba), 2) Valle (abajo), 3) Longitud de onda (distancia entre 2 crestas).<br><br>✍️ <i>¡Usa azul para el agua y rojo para señalar las crestas y valles!</i>", "icon": "ph-pencil-line", "timer": 300, "customHtml": ""},
            {"title": "Ejemplo en Casa: La Cuerda de Saltar", "sub": "6/10 - Observación Práctica", "content": "Amarras una cuerda a una reja y sacudes el extremo libre con tu brazo: ¿Cómo viaja la serpiente de ondas hasta la reja? Escríbelo en tu cuaderno.", "icon": "ph-hand-waving", "timer": 300, "customHtml": ""},
            {"title": "Taller en Parejas: Ondas Rápidas vs Ondas Lentas", "sub": "7/10 - Dinámica de Frecuencia", "content": "Si sacudes la cuerda despacio (baja frecuencia) las olas son anchas y largas. Si la sacudes muy rápido (alta frecuencia), las olas quedan pegaditas. ¿Qué relación hay entre frecuencia y tamaño de onda?", "icon": "ph-arrows-in-line-horizontal", "timer": 300, "customHtml": ""},
            {"title": "Pregunta de Pensamiento Científico", "sub": "8/10 - Razonamiento", "content": "¿Por qué los terremotos pueden destruir edificios a cientos de kilómetros del epicentro sin que la tierra viaje por el aire? (Por las ondas sísmicas).", "icon": "ph-activity", "timer": 300, "customHtml": ""},
            {"title": "Plenaria: Ondas en la Música y en la Luz", "sub": "9/10 - Socialización", "content": "Introducimos cómo nuestra voz y la música son ondas sonoras viajando por el aire que hacen vibrar nuestros tímpanos.", "icon": "ph-waveform", "timer": 300, "customHtml": ""},
            {"title": "Síntesis y Sello en el Cuaderno", "sub": "10/10 - Cierre de Clase", "content": "✔️ <b>Concepto Aprendido:</b> Una onda transmite energía sin transportar materia; partes de la onda.<br>✔️ <b>Evidencia Sellada:</b> Esquema rotulado del patito de hule y la cuerda ondulante en el cuaderno.<br><br>🌟 ¡Gran dominio visual y conceptual de las ondas!", "icon": "ph-check-circle", "timer": 300, "customHtml": ""}
        ]
    ],
    "5": [
        [
            {"title": "Física 7°: El Sonido y sus Misterios", "sub": "1/10 - Preparación y Bitácora", "content": "📅 <b>Fecha:</b> Hoy<br>📌 <b>Título:</b> 'El Sonido: Vibraciones del Aire, Tonos y el Eco'<br>🎯 <b>Meta:</b> Comprender cómo se produce el sonido, cómo viaja por diferentes medios y por qué se produce el eco en las montañas.", "icon": "ph-speaker-high", "timer": 300, "customHtml": ""},
            {"title": "¿Cómo Habla Nuestra Garganta?", "sub": "2/10 - Experimento en Vivo", "content": "<b>Ponte dos dedos suavemente sobre la garganta y haz un zumbido: <i>'¡Mmmmmmm!'</i>:</b><br>¿Qué sientes en las yemas de tus dedos? ¡Una vibración constante!<br>Todo sonido en el universo nace de algo que está <b>vibrando rápidamente</b>.", "icon": "ph-user-sound", "timer": 300, "customHtml": ""},
            {"title": "¿Por Dónde Puede Viajar el Sonido?", "sub": "3/10 - El Medio de Transporte", "content": "El sonido necesita un medio material para empujar moléculas:<br>• 💨 <b>En el Aire:</b> Viaja a velocidad normal (escuchamos las voces).<br>• 💧 <b>En el Agua:</b> Viaja 4 veces más rápido (las ballenas se comunican a cientos de km).<br>• 🪵 <b>En Sólidos (Madera/Metal):</b> ¡Viaja 15 veces más rápido!<br>• 🚀 <b>En el Espacio Vacío:</b> ¡SILENCIO TOTAL! No hay sonido en el espacio porque no hay aire que vibre.", "icon": "ph-waves", "timer": 300, "customHtml": ""},
            {"title": "Tonos Agudos vs Tonos Graves", "sub": "4/10 - Cualidades del Sonido", "content": "• 🐥 <b>Agudos:</b> Vibraciones muy rápidas y finas (canto de pajarito, silbato, flauta dulce).<br>• 🦁 <b>Graves:</b> Vibraciones lentas y profundas (rugido de león, trueno, bombo de percusión).", "icon": "ph-music-notes-simple", "timer": 300, "customHtml": ""},
            {"title": "⏱️ Reto de Dibujo en tu Cuaderno: El Grito y el Eco en el Cañón", "sub": "5/10 - Esquema Creativo", "content": "<b>Dibuja en tu cuaderno el fenómeno del Eco:</b><br>• 🗣️ <b>La Persona en la Montaña:</b> Dibuja a una persona gritando: <i>'¡HOLA!'</i>.<br>• 〰️ <b>Ondas que Salen (Líneas continuas rojas):</b> Viajando por el aire hacia una pared de roca lejana.<br>• 🪨 <b>La Pared de Roca:</b> Donde chocan las ondas.<br>• ↩️ <b>Ondas que Rebotan (Líneas punteadas azules):</b> Regresando al oído de la persona. Rotula: <i>'El Eco: Rebote del sonido'</i>.<br><br>✍️ <i>¡Colorea el paisaje montañoso y resalta el camino de ida y vuelta del sonido!</i>", "icon": "ph-pencil-line", "timer": 300, "customHtml": ""},
            {"title": "¿Por qué Vemos el Relámpago Antes de Oír el Trueno?", "sub": "6/10 - Fenómeno Natural", "content": "La luz viaja casi instantáneamente (300.000 km/s), pero el sonido viaja con calma (340 metros cada segundo). ¡Por eso primero ves la luz y segundos después oyes el retumbar!", "icon": "ph-lightning", "timer": 300, "customHtml": ""},
            {"title": "Taller en Parejas: El Teléfono de Vasos e Hilo", "sub": "7/10 - Experimento Clásico", "content": "¿Por qué al hablar por un vasito de plástico conectado por un hilo bien tensionado el compañero puede escuchar clarito en el otro extremo?", "icon": "ph-phone", "timer": 300, "customHtml": ""},
            {"title": "Pregunta de Pensamiento Científico", "sub": "8/10 - Razonamiento", "content": "En las películas de ciencia ficción en el espacio exterior se escuchan explosiones estruendosas con láseres. ¿Por qué esto es físicamente imposible en la vida real?", "icon": "ph-film-slate", "timer": 300, "customHtml": ""},
            {"title": "Plenaria: La Salud Auditiva y el Ruido", "sub": "9/10 - Cuidado Personal", "content": "Reflexionamos sobre el daño irreversible que causan los audífonos a volumen máximo en las delicadas células de nuestro oído interno.", "icon": "ph-headphones", "timer": 300, "customHtml": ""},
            {"title": "Síntesis y Sello en el Cuaderno", "sub": "10/10 - Cierre de Clase", "content": "✔️ <b>Concepto Aprendido:</b> El sonido como onda mecánica por vibración; medios de propagación y el eco.<br>✔️ <b>Evidencia Sellada:</b> Esquema del eco en el cañón con ondas de ida y vuelta en el cuaderno.<br><br>🌟 ¡Gran viaje por el mundo acústico!", "icon": "ph-check-circle", "timer": 300, "customHtml": ""}
        ]
    ],
    "6": [
        [
            {"title": "Física 7°: La Luz y la Reflexión en Espejos", "sub": "1/10 - Preparación y Bitácora", "content": "📅 <b>Fecha:</b> Hoy<br>📌 <b>Título:</b> 'La Luz Viaja en Línea Recta: Espejos y Reflexión'<br>🎯 <b>Meta:</b> Comprender cómo rebota la luz en superficies pulidas y por qué vemos imágenes reflejadas simétricamente.", "icon": "ph-sun", "timer": 300, "customHtml": ""},
            {"title": "¿Cómo Viaja la Luz en una Habitación Oscura?", "sub": "2/10 - Observación Cotidiana", "content": "<b>Piensa en esto:</b><br>Enciendes una linterna en un cuarto oscuro lleno de polvo o humo. Ves un rayo perfectamente recto como una espada.<br>La luz en medios homogéneos <b>SIEMPRE viaja en rigurosa línea recta</b>.", "icon": "ph-flashlight", "timer": 300, "customHtml": ""},
            {"title": "El Concepto Clave: La Reflexión de la Luz", "sub": "3/10 - Ley del Rebote", "content": "Cuando un rayo de luz choca contra un espejo plano o superficie pulida:<br>• Rebota exactamente como un balón de fútbol que rebota contra una pared lisa.<br>• <b>Ángulo de Entrada = Ángulo de Salida:</b> El rayo sale con la misma inclinación con la que entró.", "icon": "ph-arrows-clockwise", "timer": 300, "customHtml": ""},
            {"title": "Los Curiosos Espejos Curvos: La Cuchara", "sub": "4/10 - Experimento Casero", "content": "Toma una cuchara metálica brillante limpia:<br>• 🥄 <b>Por dentro (Cóncavo):</b> ¡Te ves de cabeza (invertido)!<br>• 🥄 <b>Por fuera (Convexo):</b> Te ves derecho y chiquito, como en los espejos de seguridad de las tiendas y parqueaderos.", "icon": "ph-magic-wand", "timer": 300, "customHtml": ""},
            {"title": "⏱️ Reto de Dibujo en tu Cuaderno: El Rayo Láser en el Espejo", "sub": "5/10 - Esquema Creativo", "content": "<b>Dibuja en tu cuaderno con regla el rebote perfecto de la luz:</b><br>• 🪞 <b>El Espejo Plano:</b> Dibuja una línea horizontal en el centro con rayitas diagonales debajo.<br>• 📏 <b>La Línea Normal (Punteada):</b> Traza una línea vertical punteada a 90° en el medio.<br>• 🔦 <b>Rayo que Entra (Rojo):</b> Dibuja un rayo inclinado bajando hacia el centro.<br>• ⚡ <b>Rayo que Sale (Verde):</b> Dibuja el rayo rebotando con la misma inclinación exacta hacia el otro lado.<br><br>✍️ <i>¡Escribe al lado: 'Ángulo de Incidencia = Ángulo de Reflexión'!</i>", "icon": "ph-pencil-line", "timer": 300, "customHtml": ""},
            {"title": "¿Por qué las Ambulancias Tienen Letras al Revés?", "sub": "6/10 - Curiosidad Vial", "content": "En el frente de las ambulancias dice <b>AICNALUBMA</b>: ¿Por qué? Para que el conductor de adelante lo lea al derecho por su espejo retrovisor. Escríbelo en tu cuaderno.", "icon": "ph-ambulance", "timer": 300, "customHtml": ""},
            {"title": "Taller en Parejas: El Espejo y la Mano Derecha", "sub": "7/10 - Ilusión de Simetría", "content": "Párense frente a un espejo y levanten la mano derecha: ¿Qué mano parece levantar el gemelo del espejo? Analicen la inversión lateral.", "icon": "ph-hand-palm", "timer": 300, "customHtml": ""},
            {"title": "Pregunta de Pensamiento Científico", "sub": "8/10 - Razonamiento", "content": "¿Por qué en un día soleado los vidrios de los edificios pueden deslumbrar a los conductores como si fueran linternas gigantes?", "icon": "ph-buildings", "timer": 300, "customHtml": ""},
            {"title": "Plenaria: La Luz como Mensajera del Cosmos", "sub": "9/10 - Socialización", "content": "Comentamos cómo los telescopios gigantes usan espejos curvos gigantescos para capturar la luz de galaxias lejanas.", "icon": "ph-telescope", "timer": 300, "customHtml": ""},
            {"title": "Síntesis y Sello en el Cuaderno", "sub": "10/10 - Cierre de Clase", "content": "✔️ <b>Concepto Aprendido:</b> La luz viaja en línea recta y se refleja cumpliendo la ley de simetría.<br>✔️ <b>Evidencia Sellada:</b> Esquema geométrico del rayo incidente y reflejado en el cuaderno con regla.<br><br>🌟 ¡Gran comprensión de la óptica geométrica!", "icon": "ph-check-circle", "timer": 300, "customHtml": ""}
        ]
    ],
    "7": [
        [
            {"title": "Física 7°: La Refracción de la Luz", "sub": "1/10 - Preparación y Bitácora", "content": "📅 <b>Fecha:</b> Hoy<br>📌 <b>Título:</b> 'El Lápiz Quebrado: La Luz se Dobla en el Agua'<br>🎯 <b>Meta:</b> Comprender cómo la luz cambia de velocidad y se desvía al pasar del aire al agua, creando ilusiones ópticas fascinantes.", "icon": "ph-eyedropper", "timer": 300, "customHtml": ""},
            {"title": "¿Por qué el Lápiz Parece Roto?", "sub": "2/10 - Experimento Casero", "content": "<b>Coloca un lápiz dentro de un vaso transparente con agua:</b><br>Míralo de lado: ¡parece mágicamente cortado en dos pedazos en el borde del agua!<br>Si sacas el lápiz, está completamente sano. ¿Por qué nuestros ojos ven esa ilusión?", "icon": "ph-pencil", "timer": 300, "customHtml": ""},
            {"title": "El Concepto Clave: La Refracción", "sub": "3/10 - La Luz se Frena y se Dobla", "content": "La <b>Refracción</b> es el cambio de dirección que sufre la luz cuando pasa de un medio a otro:<br>• En el aire, la luz viaja volando a máxima velocidad.<br>• Al entrar al agua o al vidrio (más densos), la luz <b>se frena un poco</b> y se tuerce de camino.<br>• Es como cuando una llanta de un carrito entra a la arena: se frena y gira el carro.", "icon": "ph-arrows-in-line-vertical", "timer": 300, "customHtml": ""},
            {"title": "La Ilusión de la Piscina Poco Profunda", "sub": "4/10 - Cuidado en el Agua", "content": "Cuando miras una piscina desde afuera, el fondo parece estar muy cerquita y poco profundo. ¡Pero al meterte te das cuenta de que es mucho más honda! La refracción engaña a nuestra vista.", "icon": "ph-swimming-pool", "timer": 300, "customHtml": ""},
            {"title": "⏱️ Reto de Dibujo en tu Cuaderno: El Vaso con el Lápiz Quebrado", "sub": "5/10 - Esquema Creativo", "content": "<b>Dibuja en tu cuaderno el vaso con agua y la desviación de la luz:</b><br>• 🥛 <b>El Vaso de Vidrio:</b> Con agua azul claro hasta la mitad.<br>• ✏️ <b>El Lápiz en el Aire (Recto):</b> La parte superior del lápiz entrando en diagonal.<br>• 📐 <b>El Lápiz en el Agua (Desviado):</b> Dibuja la parte sumergida desplazada hacia un lado como si estuviera cortada.<br>• 🔍 <b>Anotación Explicativa:</b> Traza flechas señalando: <i>'La luz se desvía al entrar al agua porque viaja más despacio'</i>.<br><br>✍️ <i>¡Colorea el agua con azul suave y el lápiz con amarillo brillante!</i>", "icon": "ph-pencil-line", "timer": 300, "customHtml": ""},
            {"title": "Los Lentes de Gafas y la Lupa", "sub": "6/10 - Aplicación Médica", "content": "¿Cómo ayudan las gafas a las personas que no ven bien? (Los lentes de vidrio doblan la luz por refracción para enfocarla exactamente en la retina del ojo). Escríbelo en tu cuaderno.", "icon": "ph-eyeglasses", "timer": 300, "customHtml": ""},
            {"title": "Taller en Parejas: El Pescador Indígena", "sub": "7/10 - Sabiduría Ancestral", "content": "Los pescadores que usan lanza en los ríos nunca apuntan exactamente donde ven al pez con sus ojos, sino un poco más abajo. ¿Por qué la refracción hace que el pez parezca estar en otro lugar?", "icon": "ph-fish", "timer": 300, "customHtml": ""},
            {"title": "Pregunta de Razonamiento", "sub": "8/10 - Pensamiento Crítico", "content": "¿Por qué un vaso de vidrio transparente lleno de agua puede actuar como una lupa gigante si colocas una letra pequeña detrás de él?", "icon": "ph-magnifying-glass-plus", "timer": 300, "customHtml": ""},
            {"title": "Plenaria: La Luz a Través de los Materiales", "sub": "9/10 - Socialización", "content": "Comentamos cómo la fibra óptica de internet transporta datos a la velocidad de la luz doblando los rayos dentro de hilos finos de vidrio.", "icon": "ph-broadcast", "timer": 300, "customHtml": ""},
            {"title": "Síntesis y Sello en el Cuaderno", "sub": "10/10 - Cierre de Clase", "content": "✔️ <b>Concepto Aprendido:</b> Refracción de la luz como cambio de velocidad y dirección entre medios distintos.<br>✔️ <b>Evidencia Sellada:</b> Dibujo del vaso con el lápiz desviado y explicado en el cuaderno.<br><br>🌟 ¡Gran comprensión de los secretos de la luz!", "icon": "ph-check-circle", "timer": 300, "customHtml": ""}
        ]
    ],
    "8": [
        [
            {"title": "Física 7°: Los Colores y el Arcoíris", "sub": "1/10 - Preparación y Bitácora", "content": "📅 <b>Fecha:</b> Hoy<br>📌 <b>Título:</b> 'El Arcoíris y la Magia de la Luz Blanca'<br>🎯 <b>Meta:</b> Comprender que la luz blanca del Sol es la mezcla de todos los colores y cómo las gotas de lluvia o un prisma la descomponen.", "icon": "ph-rainbow", "timer": 300, "customHtml": ""},
            {"title": "¿De Dónde Salen los Colores del Arcoíris?", "sub": "2/10 - Pregunta Cotidiana", "content": "<b>Observa este espectáculo del cielo:</b><br>Llueve mientras el Sol brilla. De pronto, en el cielo aparece un arco gigante con 7 colores brillantes en fila perfecta.<br>¿Quién pintó el cielo? ¿Dónde estaban escondidos esos colores antes de llover?", "icon": "ph-cloud-sun", "timer": 300, "customHtml": ""},
            {"title": "El Secreto de la Luz Blanca de Newton", "sub": "3/10 - Concepto Fundamental", "content": "Isaac Newton descubrió en 1666 que:<br>• La <b>luz blanca del Sol NO es pura</b>: ¡es una mezcla de todos los colores del arcoíris juntos!<br>• Cada color viaja a una velocidad ligeramente diferente dentro del vidrio o el agua.<br>• Al pasar por una gota o prisma, los colores se separan en abanico (<b>Dispersión de la Luz</b>).", "icon": "ph-palette", "timer": 300, "customHtml": ""},
            {"title": "Los 7 Colores del Espectro Visible", "sub": "4/10 - La Escala de Colores", "content": "En orden exacto desde el que menos se dobla hasta el que más se desvía:<br>🔴 <b>Rojo</b> ➔ 🟠 <b>Naranja</b> ➔ 🟡 <b>Amarillo</b> ➔ 🟢 <b>Verde</b> ➔ 🔵 <b>Azul</b> ➔ 🟣 <b>Añil / Índigo</b> ➔ 🔮 <b>Violeta</b>.", "icon": "ph-circles-four", "timer": 300, "customHtml": ""},
            {"title": "⏱️ Reto de Dibujo en tu Cuaderno: El Prisma de Newton y la Gota", "sub": "5/10 - Esquema Creativo", "content": "<b>Dibuja en tu cuaderno el nacimiento del arcoíris:</b><br>• 🔺 <b>El Prisma Triangular de Vidrio:</b> Dibuja un triángulo transparente grande.<br>• ☀️ <b>Rayo de Luz Blanca:</b> Entra por la izquierda como un solo haz amarillo/blanco.<br>• 🌈 <b>El Abanico de Colores:</b> Saliendo por el lado derecho dividido en los 7 colores bien coloreados con tus lápices: Rojo, Naranja, Amarillo, Verde, Azul y Violeta.<br><br>✍️ <i>¡Escribe al lado: 'La luz blanca se descompone en los 7 colores del arcoíris'!</i>", "icon": "ph-pencil-line", "timer": 300, "customHtml": ""},
            {"title": "¿Por qué las Plantas se Ven Verdes?", "sub": "6/10 - Los Colores de los Objetos", "content": "Cuando la luz blanca alumbra una hoja de árbol, la hoja absorbe el rojo, azul y violeta, y <b>rebota únicamente el verde</b> hacia nuestros ojos. ¡Por eso la vemos verde! Escríbelo en tu cuaderno.", "icon": "ph-plant", "timer": 300, "customHtml": ""},
            {"title": "Taller en Parejas: El Disco de Newton Giratorio", "sub": "7/10 - Experimento Mental", "content": "Si pintas un círculo de cartón con los 7 colores del arcoíris y lo pones a girar rapidísimo con un trompo o motor... ¿de qué color se ve el círculo? (¡Se ve blanco!).", "icon": "ph-spinner", "timer": 300, "customHtml": ""},
            {"title": "Pregunta de Pensamiento Científico", "sub": "8/10 - Curiosidad del Cielo", "content": "¿Por qué el cielo durante el día se ve azul y en los atardeceres se tiñe de colores rojizos y anaranjados?", "icon": "ph-sun-dim", "timer": 300, "customHtml": ""},
            {"title": "Plenaria: La Belleza de la Física", "sub": "9/10 - Reflexión Final", "content": "¿Cómo la física nos permite descubrir la belleza oculta en cosas tan cotidianas como una gota de agua, un rayo de sol o el canto de las aves?", "icon": "ph-sparkle", "timer": 300, "customHtml": ""},
            {"title": "Síntesis y Sello en el Cuaderno", "sub": "10/10 - Cierre de Periodo", "content": "✔️ <b>Concepto Aprendido:</b> La luz blanca como mezcla de colores, dispersión de la luz y formación del arcoíris.<br>✔️ <b>Evidencia Sellada:</b> Esquema del prisma de Newton coloreado con los 7 colores en el cuaderno.<br><br>🌟 ¡FELICITACIONES! Has culminado con éxito las 8 Semanas de Física 7°.", "icon": "ph-trophy", "timer": 300, "customHtml": ""}
        ]
    ]
}

db["clases"]["fisica6"] = fisica6_data
db["clases"]["fisica7"] = fisica7_data

with open("proyectorData.json", "w", encoding="utf-8") as f:
    json.dump(db, f, ensure_ascii=False, indent=2)

print("¡FÍSICA 6° Y FÍSICA 7° ACTUALIZADAS EXITOSAMENTE! 100% conceptuales, cero fórmulas matemáticas, ejemplos de la vida cotidiana, instrucciones claras para dibujos y esquemas en el cuaderno, 10 diapositivas por semana y temporizadores de 5 minutos (300s).")
