import json

# Cargar base de datos actual para mantener estructuras personalizadas
with open("proyectorData.json", "r", encoding="utf-8") as f:
    db = json.load(f)

# Estructura maestra de 10 diapositivas con 300 segundos (5 min) por diapositiva

# 1. TURISMO SOSTENIBLE (8 Semanas x 10 Diapositivas x 300s)
turismo_semanas = {
    "1": [
        [
            {"title": "Turismo: Misión Innovadores y Cadena de Valor", "sub": "1/10 - Preparación y Bitácora Turística", "content": "📅 <b>Fecha:</b> Hoy<br>📌 <b>Título:</b> 'El Turismo Sostenible: Bienes vs Servicios'<br>🎯 <b>Meta:</b> Diferenciar bienes tangibles de servicios intangibles y diseñar un producto turístico con alto valor agregado.", "icon": "ph-suitcase", "timer": 300, "customHtml": ""},
            {"title": "Estudio de Caso: El Souvenir vs. La Guianza", "sub": "2/10 - Análisis de Mercado", "content": "<b>Dilema de la experiencia:</b><br>Un turista compra una artesanía de $10.000 (Bien Tangible). Otro paga $80.000 por una caminata guiada con historias ancestrales (Servicio Intangible). ¿Por qué las personas pagan hasta 8 veces más por una experiencia inolvidable que por un objeto físico?", "icon": "ph-scales", "timer": 300, "customHtml": ""},
            {"title": "La Cadena de Valor en el Turismo", "sub": "3/10 - Ecosistema Económico", "content": "<b>Los 4 Eslabones Turísticos:</b><br>1. <b>Transporte:</b> Conexión segura hacia el destino.<br>2. <b>Hospedaje:</b> Comodidad, calidez y descanso.<br>3. <b>Gastronomía:</b> Sabores autóctonos y tradición.<br>4. <b>Actividades y Guianza:</b> La emoción y el aprendizaje del viaje.", "icon": "ph-link", "timer": 300, "customHtml": ""},
            {"title": "Gráfico Interactivo: Valor Agregado", "sub": "4/10 - Percepción de Valor", "content": "El 'Valor Agregado' es lo que eleva tu producto turístico por encima de la competencia básica:", "icon": "ph-chart-bar", "timer": 300, "customHtml": "<div style=\"background:#FFFFFF; padding:15px; border-radius:12px; border:2px solid #E2E8F0; margin-top:10px;\"><h4 style=\"text-align:center; color:#1E293B; margin:0 0 10px 0;\">Comparativa de Percepción de Valor</h4><div style=\"display:flex; align-items:flex-end; justify-content:space-around; height:100px; border-bottom:2px solid #CBD5E1; padding-bottom:5px;\"><div style=\"width:35%; display:flex; flex-direction:column; align-items:center;\"><div style=\"width:100%; height:40px; background:#94A3B8; border-radius:6px 6px 0 0; display:flex; justify-content:center; align-items:center; color:white; font-weight:bold;\">$ Básico</div><span style=\"font-size:0.75rem; color:#64748B; font-weight:bold; margin-top:4px;\">Competencia</span></div><div style=\"width:45%; display:flex; flex-direction:column; align-items:center;\"><div style=\"width:100%; height:90px; background:linear-gradient(0deg, #10B981, #34D399); border-radius:6px 6px 0 0; display:flex; justify-content:center; align-items:center; color:white; font-weight:bold; font-size:1.2rem;\">$$$ Experiencia</div><span style=\"font-size:0.8rem; color:#059669; font-weight:bold; margin-top:4px;\">+ VALOR AGREGADO</span></div></div></div>"},
            {"title": "⏱️ Reto en tu Cuaderno: Diseño de Marca Turística", "sub": "5/10 - Ideación y Creatividad", "content": "<b>Misión en tu bitácora:</b><br>1. Elige un problema turístico de tu municipio (ej: falta de mapas, no hay comida típica fácil de encontrar, sitios descuidados).<br>2. Inventa un <b>Producto o Servicio</b> que lo solucione.<br>3. Dale un <b>Nombre Comercial Atractivo</b> y dibuja su <b>Logotipo</b> con colores.<br><br>✍️ <i>¡Tienes 5 minutos cronometrados para diseñar tu marca!</i>", "icon": "ph-pencil-line", "timer": 300, "customHtml": ""},
            {"title": "Estructura de Costos y Presupuesto", "sub": "6/10 - Finanzas del Emprendedor", "content": "Anota en tu cuaderno una lista de <b>3 costos obligatorios</b> para poner a rodar tu idea:<br>• Costo de operación (permisos, seguros de viaje).<br>• Costo de materiales (ingredientes, equipos, transporte).<br>• Pago al personal y guías locales.", "icon": "ph-money", "timer": 300, "customHtml": ""},
            {"title": "El Eslogan de Venta Emocional", "sub": "7/10 - Marketing Turístico", "content": "Escribe en tu cuaderno una frase pegajosa de máximo 7 palabras que despierte emociones en el viajero (ej: <i>'Descubre el secreto que guardan nuestras montañas'</i>). Subráyala con marcador.", "icon": "ph-megaphone", "timer": 300, "customHtml": ""},
            {"title": "Pitch de 1 Minuto en Parejas", "sub": "8/10 - Venta Cruzada", "content": "Gírate hacia tu compañero:<br>Cada uno tiene 2 minutos para leerle su problema, su producto y su eslogan, intentando 'venderle' la experiencia turística.<br>El compañero dará una sugerencia constructiva para mejorar.", "icon": "ph-users-three", "timer": 300, "customHtml": ""},
            {"title": "Plenaria: Sostenibilidad e Impacto Comunitario", "sub": "9/10 - Reflexión Colectiva", "content": "¿Por qué un emprendimiento turístico debe proteger el medio ambiente y contratar a familias locales para ser verdaderamente sostenible?", "icon": "ph-tree", "timer": 300, "customHtml": ""},
            {"title": "Cierre y Evaluación: Mi Primera Ficha de Negocio", "sub": "10/10 - Firma de Avance", "content": "✔️ <b>Logro:</b> Comprensión de la cadena de valor turística, valor agregado y diseño de producto.<br>✔️ <b>Evidencia:</b> Logotipo, eslogan y pitch registrados en la bitácora.<br><br>🌟 ¡Gran inicio como futuro emprendedor turístico!", "icon": "ph-check-circle", "timer": 300, "customHtml": ""}
        ]
    ],
    "2": [
        [
            {"title": "Turismo: Paisaje Cultural Cafetero y UNESCO", "sub": "1/10 - Patrimonio Mundial Vivo", "content": "📅 <b>Fecha:</b> Hoy<br>📌 <b>Título:</b> 'El Paisaje Cultural Cafetero (PCC) como Destino UNESCO'<br>🎯 <b>Meta:</b> Valorar los atributos excepcionales del PCC y diseñar rutas de agroturismo sostenible.", "icon": "ph-coffee", "timer": 300, "customHtml": ""},
            {"title": "Estudio de Caso: Finca Tradicional vs. Turismo Masivo", "sub": "2/10 - Dilema de Conservación", "content": "<b>Caso real:</b><br>Una hacienda cafetera centenaria recibe una oferta para demoler sus casas de bahareque y construir cabañas modernas de plástico para atraer miles de turistas. ¿Qué se gana y qué patrimonio invaluable se pierde para siempre?", "icon": "ph-house-line", "timer": 300, "customHtml": ""},
            {"title": "Los 4 Atributos Excepcionales de la UNESCO", "sub": "3/10 - Criterios de Patrimonio", "content": "1. <b>Café de Cordillera:</b> Cultivo en laderas empinadas.<br>2. <b>Arquitectura del Bahareque:</b> Casas de guadua, madera y barro.<br>3. <b>Biodiversidad y Riqueza Hídrica:</b> Bosques de niebla y aves.<br>4. <b>Tradición Campesina:</b> La cultura del recolector y la chiva.", "icon": "ph-seal-check", "timer": 300, "customHtml": ""},
            {"title": "La Experiencia 'Del Grano a la Taza'", "sub": "4/10 - Agroturismo Vivencial", "content": "El turista moderno no quiere mirar de lejos: quiere ponerse el canasto, recolectar granos maduros, despulpary catar el café especial en origen.", "icon": "ph-plant", "timer": 300, "customHtml": ""},
            {"title": "⏱️ Reto en tu Cuaderno: Mapa de la Ruta del Café", "sub": "5/10 - Cartografía Ilustrada", "content": "<b>Dibuja en tu cuaderno un mapa con 4 estaciones:</b><br>• 1️⃣ <b>El Cafetal:</b> Recolección y avistamiento de aves.<br>• 2️⃣ <b>El Beneficiadero:</b> Despulpado ecológico y secado al sol.<br>• 3️⃣ <b>La Casa Típica:</b> Almuerzo campesino en plato de barro.<br>• 4️⃣ <b>Laboratorio de Catación:</b> Aromas y sabores del café.<br><br>✍️ <i>¡Ponle nombres llamativos a cada estación!</i>", "icon": "ph-pencil-line", "timer": 300, "customHtml": ""},
            {"title": "Capacidad de Carga y Turismo Responsable", "sub": "6/10 - Protección del Entorno", "content": "Escribe en tu cuaderno: ¿Qué es la <b>Capacidad de Carga</b>? (El número máximo de visitantes que un lugar puede recibir sin deteriorar la naturaleza ni molestar a los habitantes locales).", "icon": "ph-gauge", "timer": 300, "customHtml": ""},
            {"title": "Diseño del Paquete y Precio de la Experiencia", "sub": "7/10 - Comercialización", "content": "Define en tu cuaderno:<br>• Duración del tour (ej: 4 horas).<br>• Qué incluye (guianza, refrigerio típico, muestra de café).<br>• Precio justo por persona y descuentos para grupos.", "icon": "ph-ticket", "timer": 300, "customHtml": ""},
            {"title": "Debate en Parejas: ¿Cómo Preservar el Paisaje?", "sub": "8/10 - Discusión Guiada", "content": "¿Cómo podemos evitar que el turismo en pueblos como Salento, Filandia o Jericó destruya la tranquilidad y las tradiciones de sus campesinos?", "icon": "ph-chats-circle", "timer": 300, "customHtml": ""},
            {"title": "Plenaria: El Orgullo de Nuestras Raíces", "sub": "9/10 - Puesta en Común", "content": "¿Por qué el mundo entero admira el Paisaje Cultural Cafetero de Colombia? Socialicen qué elementos de su región merecen ser conocidos internacionalmente.", "icon": "ph-globe-hemisphere-west", "timer": 300, "customHtml": ""},
            {"title": "Cierre y Evaluación: Sello de Embajador del PCC", "sub": "10/10 - Firma de Avance", "content": "✔️ <b>Logro:</b> Comprensión del PCC UNESCO, capacidad de carga y diseño de rutas agroturísticas.<br>✔️ <b>Evidencia:</b> Mapa de la Ruta del Café y Ficha de Experiencia firmadas.<br><br>🌟 ¡Gran labor como guardián de nuestro patrimonio cultural!", "icon": "ph-check-circle", "timer": 300, "customHtml": ""}
        ]
    ],
    "3": [
        [
            {"title": "Turismo: Ecoturismo y Aviturismo (Birdwatching)", "sub": "1/10 - Colombia, País de las Aves", "content": "📅 <b>Fecha:</b> Hoy<br>📌 <b>Título:</b> 'Ecoturismo, Senderismo y Avistamiento de Aves'<br>🎯 <b>Meta:</b> Diseñar expediciones ecoturísticas bajo el protocolo de 'No Deje Rastro' y guianza de avifauna.", "icon": "ph-bird", "timer": 300, "customHtml": ""},
            {"title": "Estudio de Caso: El Sendero Erosionado", "sub": "2/10 - Impacto Ambiental", "content": "<b>Situación real:</b><br>Un sendero ecológico hacia una cascada secreta se volvió viral. Cientos de personas dejan botellas plásticas, hacen fogatas y espantan a las aves con música a alto volumen. ¿Cómo recuperar el sendero sin prohibir el ecoturismo?", "icon": "ph-warning-octagon", "timer": 300, "customHtml": ""},
            {"title": "Los 7 Principios de 'No Deje Rastro'", "sub": "3/10 - Ética del Ecoturista", "content": "1. Planifique con anticipación.<br>2. Camine sobre senderos firmes.<br>3. Regrese con toda su basura.<br>4. Deje lo que encuentre (no arranque flores).<br>5. Minimice el impacto de fogatas.<br>6. Respete la fauna silvestre.<br>7. Sea considerado con otros visitantes.", "icon": "ph-footprints", "timer": 300, "customHtml": ""},
            {"title": "El Potencial del Aviturismo en Colombia", "sub": "4/10 - Líder Mundial en Aves", "content": "Colombia es el país #1 del planeta en especies de aves (más de 1.950). Los observadores internacionales pagan altas tarifas por guías locales que sepan imitar cantos y ubicar especies endémicas.", "icon": "ph-binoculars", "timer": 300, "customHtml": ""},
            {"title": "⏱️ Reto en tu Cuaderno: Guía de Campo Ilustrada", "sub": "5/10 - Ficha de Aviturismo", "content": "<b>Dibuja en tu cuaderno una Ficha de Campo para 2 aves de tu región:</b><br>• 🦜 <b>Ave 1:</b> Nombre común, nombre científico, colores principales y tipo de canto.<br>• 🦅 <b>Ave 2:</b> Hábitat (árboles altos, matorrales), alimentación y estado de conservación.<br><br>✍️ <i>¡Dibuja las siluetas de las aves y resalta sus colores vivos!</i>", "icon": "ph-pencil-line", "timer": 300, "customHtml": ""},
            {"title": "Ficha Técnica de Senderismo y Seguridad", "sub": "6/10 - Gestión del Riesgo", "content": "Elabora en tu cuaderno la ficha técnica del recorrido:<br>• Distancia total (km) y Desnivel (+/- metros).<br>• Nivel de dificultad (Fácil / Medio / Exigente).<br>• Equipo obligatorio: Botiquín, impermeable, silbato, calzado con agarre.", "icon": "ph-first-aid-kit", "timer": 300, "customHtml": ""},
            {"title": "Simulación de Guianza de Naturaleza en Parejas", "sub": "7/10 - Práctica de Interpretación", "content": "Uno de los dos actuará como el guía ecoturista explicando un árbol nativo imaginario y el canto de un ave. El otro será el turista extranjero haciendo preguntas sobre la conservación del bosque.", "icon": "ph-microphone", "timer": 300, "customHtml": ""},
            {"title": "Diseño del Kit del Viajero Ecológico", "sub": "8/10 - Sostenibilidad", "content": "Haz una lista de 4 elementos que tu empresa de ecoturismo entregará a cada visitante (ej: termo reutilizable, bolsa de tela para residuos, libreta de campo, repelente natural biodegradable).", "icon": "ph-backpack", "timer": 300, "customHtml": ""},
            {"title": "Plenaria: Conservación y Riqueza Comunitaria", "sub": "9/10 - Debate Abierto", "content": "¿Por qué un campesino que antes talaba árboles gana más dinero hoy cuidando el bosque y guiando avistadores de aves internacionales?", "icon": "ph-hand-coins", "timer": 300, "customHtml": ""},
            {"title": "Cierre y Evaluación: Credencial de Guía Ecoturístico", "sub": "10/10 - Firma de Avance", "content": "✔️ <b>Logro:</b> Aplicación de principios 'No Deje Rastro', ficha de senderismo y aviturismo.<br>✔️ <b>Evidencia:</b> Ficha de Campo de Aves y Protocolo de Seguridad en la bitácora.<br><br>🌟 ¡Gran compromiso con la biodiversidad de Colombia!", "icon": "ph-check-circle", "timer": 300, "customHtml": ""}
        ]
    ],
    "4": [
        [
            {"title": "Turismo: Hospitalidad y Calidad en el Servicio", "sub": "1/10 - El Arte de la Calidez", "content": "📅 <b>Fecha:</b> Hoy<br>📌 <b>Título:</b> 'Hospitalidad, Protocolos y Manejo de Momentos de Verdad'<br>🎯 <b>Meta:</b> Diseñar estándares de atención al cliente '5 estrellas' y resolver quejas con asertividad profesional.", "icon": "ph-sparkle", "timer": 300, "customHtml": ""},
            {"title": "Estudio de Caso: El Restaurante que Perdió sus Clientes", "sub": "2/10 - El Costo del Mal Servicio", "content": "<b>Caso de estudio:</b><br>Un restaurante con comida deliciosa quebró en 6 meses. Los meseros atendían mirando el celular, traían pedidos equivocados y respondían con mala cara cuando alguien pedía la cuenta. ¿Por qué la comida rica no compensa un mal trato humano?", "icon": "ph-thumbs-down", "timer": 300, "customHtml": ""},
            {"title": "Los 'Momentos de la Verdad' del Viajero", "sub": "3/10 - El Ciclo de Atención", "content": "1. <b>Primer Contacto:</b> Saludo con sonrisa, contacto visual y bienvenida cálida.<br>2. <b>Durante la Estadía:</b> Anticiparse a las necesidades del huésped.<br>3. <b>La Despedida:</b> Agradecimiento sincero e invitación a regresar.", "icon": "ph-clock-countdown", "timer": 300, "customHtml": ""},
            {"title": "El Protocolo L.A.S.T. para Resolver Quejas", "sub": "4/10 - Resolución de Conflictos", "content": "• <b>L (Listen):</b> Escuchar sin interrumpir ni ponerse a la defensiva.<br>• <b>A (Apologize):</b> Disculparse con empatía por la molestia ocasionada.<br>• <b>S (Solve):</b> Resolver el problema de inmediato con una solución justa.<br>• <b>T (Thank):</b> Agradecer al cliente por darnos la oportunidad de mejorar.", "icon": "ph-shield-check", "timer": 300, "customHtml": ""},
            {"title": "⏱️ Reto en tu Cuaderno: Decálogo de Atención 5 Estrellas", "sub": "5/10 - Manual de Servicio", "content": "<b>Escribe en tu cuaderno tus 5 Mandamientos de Atención al Turista:</b><br>1. La frase exacta de bienvenida que usará todo el equipo.<br>2. Qué hacer si un turista llega cansado o de mal genio.<br>3. Cómo responder si no sabemos la respuesta a una pregunta.<br>4. El detalle de cortesía sorpresa (agua fresca, café caliente).<br>5. La frase de despedida memorable.<br><br>✍️ <i>¡Enmarca tu decálogo como si fuera para un hotel de lujo!</i>", "icon": "ph-pencil-line", "timer": 300, "customHtml": ""},
            {"title": "Comunicación Intercultural y Respeto", "sub": "6/10 - Diversidad Global", "content": "Anota en tu cuaderno <b>2 precauciones culturales</b> al atender turistas de otros países o regiones (respeto a dietas vegetarianas, modismos de lenguaje, espacio personal y costumbres religiosas).", "icon": "ph-translate", "timer": 300, "customHtml": ""},
            {"title": "Role-Playing en Parejas: Manejo de Cliente Difícil", "sub": "7/10 - Simulación en Vivo", "content": "• Estudiante A: Turista muy enojado porque su habitación no tiene agua caliente.<br>• Estudiante B: Recepcionista aplicando el protocolo L.A.S.T. para calmarlo y ofrecerle una solución inmediata.", "icon": "ph-users-three", "timer": 300, "customHtml": ""},
            {"title": "Diseño de la Encuesta de Satisfacción (NPS)", "sub": "8/10 - Medición de Calidad", "content": "Dibuja en tu cuaderno una tarjeta de calificación de 1 a 5 estrellas con 3 preguntas breves para el cliente antes de marcharse.", "icon": "ph-star", "timer": 300, "customHtml": ""},
            {"title": "Plenaria: La Calidez Colombiana como Marca País", "sub": "9/10 - Reflexión Grupal", "content": "¿Por qué los turistas extranjeros siempre dicen que lo mejor de Colombia es la sonrisa y amabilidad de su gente? ¿Cómo podemos cuidar esa reputación?", "icon": "ph-heart", "timer": 300, "customHtml": ""},
            {"title": "Cierre y Evaluación: Sello de Anfitrión de Excelencia", "sub": "10/10 - Firma de Avance", "content": "✔️ <b>Logro:</b> Dominio del protocolo L.A.S.T., momentos de la verdad y diseño de servicio 5 estrellas.<br>✔️ <b>Evidencia:</b> Decálogo de Atención y Encuesta de Satisfacción en el cuaderno.<br><br>🌟 ¡Tu amabilidad abre las puertas del mundo!", "icon": "ph-check-circle", "timer": 300, "customHtml": ""}
        ]
    ],
    "5": [
        [
            {"title": "Turismo: Gastronomía Tradicional y Storytelling", "sub": "1/10 - Los Sabores de Nuestra Tierra", "content": "📅 <b>Fecha:</b> Hoy<br>📌 <b>Título:</b> 'Turismo Gastronómico y Rescate Culinario'<br>🎯 <b>Meta:</b> Diseñar experiencias culinarias con ingredientes locales y técnicas de storytelling gastronómico.", "icon": "ph-fork-knife", "timer": 300, "customHtml": ""},
            {"title": "Estudio de Caso: El Plato Típico Olvidado", "sub": "2/10 - Memoria en el Fogón", "content": "<b>Caso:</b><br>Una abuela campesina prepara un dulce tradicional a base de frutas silvestres que ya nadie en el pueblo sabe hacer. Dos jóvenes deciden incluirlo como el postre insignia de su posada turística, convirtiéndolo en un éxito rotundo. ¿Cómo la cocina preserva la identidad?", "icon": "ph-cooking-pot", "timer": 300, "customHtml": ""},
            {"title": "La Cadena del Alimento Kilómetro Cero (Km 0)", "sub": "3/10 - Sostenibilidad Alimentaria", "content": "El turismo gastronómico responsable compra a los campesinos y pescadores locales (Km 0), garantizando frescura, reduciendo la huella de carbono y fortaleciendo la economía comunitaria.", "icon": "ph-arrows-clockwise", "timer": 300, "customHtml": ""},
            {"title": "¿Qué es el Storytelling Gastronómico?", "sub": "4/10 - La Historia en el Plato", "content": "No se trata de vender solo comida: se cuenta quién sembró el maíz, qué abuela inventó la receta y qué leyenda ancestral acompaña ese plato tradicional.", "icon": "ph-book-open", "timer": 300, "customHtml": ""},
            {"title": "⏱️ Reto en tu Cuaderno: Menú de Degustación Tradicional", "sub": "5/10 - Diseño de Carta Gourmet", "content": "<b>Diseña en tu cuaderno un Menú de 3 Tiempos:</b><br>• 🍲 <b>Entrada:</b> Sopa o amasijo típico con nombre evocador.<br>• 🥩 <b>Plato Fuerte:</b> Preparación tradicional con guarnición campesina.<br>• 🍧 <b>Postre y Bebida:</b> Dulce autóctono y jugo de fruta de la región.<br><br>✍️ <i>¡Escribe un párrafo corto debajo de cada plato contando su historia tradicional!</i>", "icon": "ph-pencil-line", "timer": 300, "customHtml": ""},
            {"title": "Higiene y Manipulación Segura de Alimentos", "sub": "6/10 - Buenas Prácticas (BPM)", "content": "Anota en tu cuaderno <b>3 reglas de oro de higiene</b> (lavado de manos, cadena de frío de carnes y desinfección de verduras) para proteger la salud del turista.", "icon": "ph-hand-soap", "timer": 300, "customHtml": ""},
            {"title": "Costeo del Plato y Margen de Ganancia", "sub": "7/10 - Finanzas Culinarias", "content": "Calcula en tu cuaderno:<br>• Costo de ingredientes por porción: $7.000<br>• Costo de preparación y energía: $3.000<br>• Precio de venta al público: $22.000 (Margen de ganancia: $12.000).", "icon": "ph-calculator", "timer": 300, "customHtml": ""},
            {"title": "Presentación al 'Crítico Culinario' en Parejas", "sub": "8/10 - Práctica de Venta", "content": "Describe a tu compañero tu plato estrella usando palabras sensoriales (crujiente, aromático, suave, ahumado) logrando que se le haga agua la boca.", "icon": "ph-chat-circle", "timer": 300, "customHtml": ""},
            {"title": "Plenaria: La Cocina como Patrimonio Cultural", "sub": "9/10 - Reflexión de Aula", "content": "¿Cuáles son los 3 platos más representativos de nuestro departamento que todo turista extranjero debería probar antes de morir?", "icon": "ph-fire", "timer": 300, "customHtml": ""},
            {"title": "Cierre y Evaluación: Sello de Chef Anfitrión", "sub": "10/10 - Firma de Avance", "content": "✔️ <b>Logro:</b> Diseño de menú turístico con storytelling, enfoque Km 0 y costeo básico.<br>✔️ <b>Evidencia:</b> Menú de 3 Tiempos y Ficha de Buenas Prácticas firmados en la bitácora.<br><br>🌟 ¡Los sabores de tu tierra conquistan paladares!", "icon": "ph-check-circle", "timer": 300, "customHtml": ""}
        ]
    ],
    "6": [
        [
            {"title": "Turismo: Marketing Digital y Redes Sociales", "sub": "1/10 - El Destino en la Era Digital", "content": "📅 <b>Fecha:</b> Hoy<br>📌 <b>Título:</b> 'Marketing Turístico Digital y Creación de Contenido'<br>🎯 <b>Meta:</b> Diseñar una campaña en redes sociales, Google Maps y plataformas para posicionar un destino turístico.", "icon": "ph-instagram-logo", "timer": 300, "customHtml": ""},
            {"title": "Estudio de Caso: El Glamping que se Llenó con TikTok", "sub": "2/10 - El Poder de las Redes", "content": "<b>Caso:</b><br>Un hospedaje rural en medio de la montaña no recibía clientes. Grabaron un video corto de 20 segundos mostrando el amanecer con una taza de café humeante y el canto de las aves. El video tuvo 2 millones de vistas y coparon reservas por 6 meses. ¿Por qué funcionó?", "icon": "ph-video-camera", "timer": 300, "customHtml": ""},
            {"title": "Definición del 'Buyer Persona' (El Viajero Ideal)", "sub": "3/10 - Segmentación de Mercado", "content": "• 🎒 <b>Mochilero / Aventurero:</b> Busca bajo costo, adrenalina y senderos.<br>• 👨‍👩‍👧 <b>Familia con Niños:</b> Busca seguridad, piscina, talleres y descanso.<br>• 💻 <b>Nómada Digital:</b> Requiere excelente internet, buen café y silencio.", "icon": "ph-user-circle", "timer": 300, "customHtml": ""},
            {"title": "Canales Digitales Clave para el Turismo", "sub": "4/10 - Ecosistema Web", "content": "1. <b>Google Maps / My Business:</b> Fotos, horarios y ubicación exacta con GPS.<br>2. <b>Instagram y TikTok:</b> Videos verticales (Reels) que transmitan sensaciones.<br>3. <b>WhatsApp Business:</b> Respuestas automáticas rápidas y catálogo de precios.", "icon": "ph-device-mobile", "timer": 300, "customHtml": ""},
            {"title": "⏱️ Reto en tu Cuaderno: Storyboard de un Reel Promocional", "sub": "5/10 - Guion Audiovisual", "content": "<b>Dibuja en tu cuaderno una tira cómica de 3 cuadros (Reel de 30 seg):</b><br>• 🎬 <b>Cuadro 1 (0-3 seg - Gancho):</b> Imagen impactante que atrape la atención.<br>• 🎬 <b>Cuadro 2 (4-20 seg - La Experiencia):</b> Muestra la comida, el paisaje o la actividad emocionante.<br>• 🎬 <b>Cuadro 3 (20-30 seg - Llamado a la Acción):</b> '¡Reserva hoy tu cupo por WhatsApp!'<br><br>✍️ <i>¡Escribe debajo los hashtags principales (#TurismoSostenible #ViajaPorColombia)!</i>", "icon": "ph-pencil-line", "timer": 300, "customHtml": ""},
            {"title": "Fotografía Turística: Iluminación y Puntos 'Instagrameables'", "sub": "6/10 - Estética Visual", "content": "Anota <b>2 consejos de fotografía</b> para un destino turístico (aprovechar la 'hora dorada' del amanecer/atardecer y crear un mirador o marco decorativo con flores para que la gente se tome fotos).", "icon": "ph-camera", "timer": 300, "customHtml": ""},
            {"title": "Taller de Redacción de un 'Copy' Persuasivo", "sub": "7/10 - Copywriting", "content": "Redacta el texto de publicación para tu post: título cautivador, 3 beneficios del tour y el enlace de contacto directo.", "icon": "ph-text-align-left", "timer": 300, "customHtml": ""},
            {"title": "Manejo de Reseñas en Línea y Reputación", "sub": "8/10 - Calificaciones en Google", "content": "Escribe una respuesta profesional y elegante para un cliente que dejó una calificación de 2 estrellas en internet porque llovió durante su tour.", "icon": "ph-chat-teardrop-dots", "timer": 300, "customHtml": ""},
            {"title": "Plenaria: Promoción vs. Cuidado del Destino", "sub": "9/10 - Ética Digital", "content": "¿Cómo promover lugares hermosos en redes sociales sin revelar ubicaciones secretas frágiles que podrían ser destruidas por el turismo masivo descontrolado?", "icon": "ph-shield-warning", "timer": 300, "customHtml": ""},
            {"title": "Cierre y Evaluación: Sello de Estratega Digital", "sub": "10/10 - Firma de Avance", "content": "✔️ <b>Logro:</b> Dominio del Storyboard audiovisual, segmentación de clientes y marketing turístico digital.<br>✔️ <b>Evidencia:</b> Guion de Reel y Copy publicitario registrados en la bitácora.<br><br>🌟 ¡Tu destino está listo para brillar en las pantallas del mundo!", "icon": "ph-check-circle", "timer": 300, "customHtml": ""}
        ]
    ],
    "7": [
        [
            {"title": "Turismo: Guianza Profesional y Storytelling", "sub": "1/10 - El Embajador Cultural", "content": "📅 <b>Fecha:</b> Hoy<br>📌 <b>Título:</b> 'Técnicas de Guianza Turística y Narración Oral'<br>🎯 <b>Meta:</b> Desarrollar habilidades de oratoria, manejo de grupos, primeros auxilios y storytelling en recorridos guiados.", "icon": "ph-megaphone", "timer": 300, "customHtml": ""},
            {"title": "Estudio de Caso: El Tour de Fechas vs. El Tour de Emociones", "sub": "2/10 - La Forma de Comunicar", "content": "<b>Comparación:</b><br>• <b>Guía A:</b> Lee un folleto lleno de fechas históricas y datos fríos mientras camina rápido.<br>• <b>Guía B:</b> Se detiene bajo la sombra de un árbol centenario, mira a los ojos a los turistas y les cuenta la leyenda del cacique que protegió ese valle sagrado.<br>¿Cuál de los dos tours recordará el viajero por el resto de su vida?", "icon": "ph-sparkle", "timer": 300, "customHtml": ""},
            {"title": "Herramientas del Guía Líder", "sub": "3/10 - Expresión y Liderazgo", "content": "1. <b>Voz y Modulación:</b> Tono claro, pausas dramáticas y volumen adecuado.<br>2. <b>Lenguaje Corporal:</b> Postura abierta, señalamiento con mano extendida y sonrisa.<br>3. <b>Control del Grupo:</b> Mantener al grupo unido sin dejar a nadie atrás.", "icon": "ph-person-simple-walk", "timer": 300, "customHtml": ""},
            {"title": "La Estructura de una Parada Guiada", "sub": "4/10 - Paso a Paso", "content": "• <b>Paso 1:</b> Ubicar al grupo en sombra y comprobar que todos escuchen.<br>• <b>Paso 2:</b> Pregunta introductoria que despierte curiosidad.<br>• <b>Paso 3:</b> Relato del hecho o misterio del lugar.<br>• <b>Paso 4:</b> Espacio para preguntas y fotos antes de continuar.", "icon": "ph-map-pin", "timer": 300, "customHtml": ""},
            {"title": "⏱️ Reto en tu Cuaderno: Libreto de Guianza Turística", "sub": "5/10 - Guion Profesional", "content": "<b>Escribe en tu cuaderno el libreto para una parada en un sitio histórico o natural:</b><br>• 🗣️ <b>Frase de Apertura:</b> <i>'Amigos viajeros, detengámonos aquí un momento...'</i><br>• 📜 <b>Historia / Anécdota Curiosa:</b> La leyenda, personaje o detalle que casi nadie conoce.<br>• ❓ <b>Pregunta al público:</b> Para hacerlos participar activamente.<br><br>✍️ <i>¡Escribe con signos de exclamación e indicaciones de pausas dramáticas!</i>", "icon": "ph-pencil-line", "timer": 300, "customHtml": ""},
            {"title": "Manejo de Emergencias y Botiquín de Campo", "sub": "6/10 - Seguridad del Turista", "content": "Anota en tu cuaderno <b>3 pasos inmediatos</b> si un turista se tuerce el tobillo en el camino (calmarlo, evaluar con el botiquín, llamar a apoyo y no dejarlo solo).", "icon": "ph-first-aid", "timer": 300, "customHtml": ""},
            {"title": "Taller en Vivo: Guianza de 2 Minutos", "sub": "7/10 - Práctica ante el Salón", "content": "Ponte de pie frente a tu compañero y léale tu libreto actuando como un guía profesional apasionado por su tierra.", "icon": "ph-microphone-stage", "timer": 300, "customHtml": ""},
            {"title": "Código Ético del Guía Turístico", "sub": "8/10 - Normativa y Respeto", "content": "Escribe en tu cuaderno: <i>'El guía turístico es la cara y el corazón de su país; jamás inventa información falsa y protege el patrimonio con su ejemplo.'</i>", "icon": "ph-certificate", "timer": 300, "customHtml": ""},
            {"title": "Plenaria: La Vocación de Servir e Inspirar", "sub": "9/10 - Reflexión Colectiva", "content": "¿Por qué un gran guía turístico puede cambiar la percepción que un extranjero tiene sobre todo un país?", "icon": "ph-globe-stand", "timer": 300, "customHtml": ""},
            {"title": "Cierre y Evaluación: Credencial de Guía Profesional", "sub": "10/10 - Firma de Avance", "content": "✔️ <b>Logro:</b> Dominio del libreto de guianza, técnicas de storytelling y liderazgo de grupos turísticos.<br>✔️ <b>Evidencia:</b> Libreto de Guianza y Protocolo de Seguridad en la bitácora.<br><br>🌟 ¡Tienes la elocuencia y el carisma de un gran líder turístico!", "icon": "ph-check-circle", "timer": 300, "customHtml": ""}
        ]
    ],
    "8": [
        [
            {"title": "Turismo: Emprendimiento Sostenible y Gran Feria", "sub": "1/10 - ¡Lanzamiento de Negocios!", "content": "📅 <b>Fecha:</b> Hoy<br>📌 <b>Título:</b> 'El Modelo Canvas Turístico y la Feria de Innovación'<br>🎯 <b>Meta:</b> Consolidar el plan de negocio turístico en el modelo Canvas y defender el proyecto en un Pitch ante inversionistas.", "icon": "ph-trophy", "timer": 300, "customHtml": ""},
            {"title": "Estudio de Caso: De la Idea a la Empresa Comunitaria", "sub": "2/10 - Emprendimiento Real", "content": "<b>Caso:</b><br>Cinco jóvenes de una vereda se unieron para ofrecer tours en balsa ecológica por el río. Comenzaron con dos chalecos prestados. Hoy tienen 12 balsas, restaurante flotante y dan empleo a 25 familias campesinas. ¿Cuál fue su secreto? Trabajo en equipo, calidad y constancia.", "icon": "ph-lightbulb-filament", "timer": 300, "customHtml": ""},
            {"title": "El Modelo Canvas Turístico en 4 Bloques", "sub": "3/10 - Estructura Empresarial", "content": "1. <b>Propuesta de Valor:</b> ¿Qué experiencia única e inolvidable ofreces?<br>2. <b>Clientes:</b> ¿Quién te compra y por qué canales llegan?<br>3. <b>Recursos y Alianzas Clave:</b> ¿Quiénes son tus socios estratégicos?<br>4. <b>Finanzas:</b> ¿Cuánto cuesta operar y cuánto dinero ingresará?", "icon": "ph-grid-four", "timer": 300, "customHtml": ""},
            {"title": "Medición del Triple Impacto", "sub": "4/10 - Empresas B y Sostenibilidad", "content": "• 💰 <b>Impacto Económico:</b> Ganancias sostenibles en el tiempo.<br>• 👥 <b>Impacto Social:</b> Beneficio directo para la comunidad y empleo digno.<br>• 🌿 <b>Impacto Ambiental:</b> Conservación de ríos, bosques y especies nativas.", "icon": "ph-recycle", "timer": 300, "customHtml": ""},
            {"title": "⏱️ Reto en tu Cuaderno: El Lienzo Canvas de mi Empresa", "sub": "5/10 - Plan de Negocio Completo", "content": "<b>Dibuja en tu cuaderno el Lienzo Canvas de tu Proyecto Turístico:</b><br>• 1️⃣ Nombre Comercial y Logotipo.<br>• 2️⃣ Propuesta de Valor Diferenciadora.<br>• 3️⃣ Clientes Objetivo (Familias, Jóvenes, Extranjeros).<br>• 4️⃣ Precio del Paquete y Costos Principales.<br><br>✍️ <i>¡Diseña la portada final de tu empresa turística con todos sus detalles!</i>", "icon": "ph-pencil-line", "timer": 300, "customHtml": ""},
            {"title": "Preparación del Stand y Material Publicitario", "sub": "6/10 - Exposición de Feria", "content": "Diseña en tu cuaderno el folleto promocional (Tríptico) con las fotos de la experiencia, el mapa de llegada y los teléfonos de reserva.", "icon": "ph-newspaper-clipping", "timer": 300, "customHtml": ""},
            {"title": "El Pitch de Inversión 'Shark Tank' de 2 Minutos", "sub": "7/10 - Presentación en Vivo", "content": "Presenta tu proyecto ante el salón respondiendo:<br>1. ¿Qué problema resuelve tu empresa?<br>2. ¿Por qué tu experiencia es la mejor de la región?<br>3. ¿Cuánto dinero necesitas para empezar?", "icon": "ph-microphone-stage", "timer": 300, "customHtml": ""},
            {"title": "Votación y Evaluación Cruzada de Proyectos", "sub": "8/10 - Retroalimentación", "content": "Cada estudiante votará por el proyecto más innovador, el más sostenible y el mejor presentado de la feria.", "icon": "ph-chart-line-up", "timer": 300, "customHtml": ""},
            {"title": "Plenaria: El Turismo como Motor de Paz y Desarrollo", "sub": "9/10 - Conclusión del Curso", "content": "¿Cómo el turismo bien gestionado reemplaza la violencia por oportunidades y llena de orgullo a las nuevas generaciones de Colombia?", "icon": "ph-hands-clapping", "timer": 300, "customHtml": ""},
            {"title": "🌟 Graduación de Emprendedores Turísticos", "sub": "10/10 - Clausura del Periodo", "content": "🏆 <b>¡FELICITACIONES! Has completado las 8 Semanas de Turismo Sostenible:</b><br>• Semana 1: Cadena de Valor y Bien vs Servicio.<br>• Semana 2: Paisaje Cultural Cafetero UNESCO.<br>• Semana 3: Ecoturismo y Aviturismo.<br>• Semana 4: Hospitalidad y Calidad 5 Estrellas.<br>• Semana 5: Turismo Gastronómico y Sabores Locales.<br>• Semana 6: Marketing Digital y Contenido Turístico.<br>• Semana 7: Guianza y Storytelling.<br>• Semana 8: Modelo Canvas y Pitch de Negocios.<br><br>📜 <i>¡Sello de Oro y Certificación de Emprendedor en la Bitácora!</i>", "icon": "ph-crown", "timer": 300, "customHtml": ""}
        ]
    ]
}

db["clases"]["turismo"] = turismo_semanas

# Función auxiliar para expandir cualquier materia a 10 diapositivas x 300 segundos
def expandir_materia_a_10_diapositivas(course_id, nombre_materia, curricula_temas):
    materia_dict = {}
    for sem_num, tema_info in curricula_temas.items():
        titulo_sem = tema_info["tema"]
        meta_sem = tema_info["meta"]
        concepto_sem = tema_info["concepto"]
        reto_sem = tema_info["reto"]
        pregunta_sem = tema_info["pregunta"]
        aplicacion_sem = tema_info.get("aplicacion", "Aplicación práctica en el entorno cotidiano y tecnológico.")
        custom_html = tema_info.get("customHtml", "")

        slides = [
            {
                "title": f"{nombre_materia} - Semana {sem_num}",
                "sub": "1/10 - Preparación y Bitácora de Clase",
                "content": f"📅 <b>Fecha:</b> Hoy<br>📌 <b>Título:</b> '{titulo_sem}'<br>🎯 <b>Meta Pedagógica:</b> {meta_sem}<br><br>✍️ <i>Alista tu cuaderno, regla, lápiz y colores. Marca la fecha y el título con excelente caligrafía.</i>",
                "icon": "ph-book-open",
                "timer": 300,
                "customHtml": ""
            },
            {
                "title": f"Pregunta Problematizadora: {titulo_sem}",
                "sub": "2/10 - Exploración y Desafío Inicial",
                "content": f"<b>Observemos el fenómeno:</b><br>{pregunta_sem}<br><br>💡 ¿Qué ideas o hipótesis previas tienes para explicar este hecho de la naturaleza o la sociedad?",
                "icon": "ph-question",
                "timer": 300,
                "customHtml": ""
            },
            {
                "title": f"Concepto Clave: {titulo_sem}",
                "sub": "3/10 - Fundamentación Científica y Teórica",
                "content": f"<b>Principios Fundamentales:</b><br>{concepto_sem}",
                "icon": "ph-lightbulb",
                "timer": 300,
                "customHtml": ""
            },
            {
                "title": "Esquema Visual y Análisis de Modelos",
                "sub": "4/10 - Comprensión Gráfica",
                "content": f"Observa la estructura y el comportamiento de las variables:<br><div style='background:#F8FAFC; border:1px solid #CBD5E1; border-radius:12px; padding:15px; margin-top:10px;'>🔍 <b>Análisis:</b> {aplicacion_sem}</div>",
                "icon": "ph-tree-structure",
                "timer": 300,
                "customHtml": custom_html
            },
            {
                "title": "⏱️ Reto Práctico Individual en el Cuaderno",
                "sub": "5/10 - Aplicación y Ejercicio Guiado",
                "content": f"<b>Actividad para desarrollar ahora:</b><br>{reto_sem}<br><br>✍️ <i>Escribe con letra clara, utiliza tu regla y encierra tu respuesta en un recuadro. Tienes 5 minutos en el temporizador.</i>",
                "icon": "ph-pencil-line",
                "timer": 300,
                "customHtml": "<div style='background:#FEF3C7; border:1px solid #FDE68A; border-radius:8px; padding:10px; font-size:0.9rem; color:#92400E;'>⏱️ 5 minutos cronometrados. ¡Concéntrate y haz tu mejor trabajo!</div>"
            },
            {
                "title": "Análisis Crítico y Casos del Entorno",
                "sub": "6/10 - Conexión con la Vida Real",
                "content": f"¿Cómo influye este concepto en los avances tecnológicos, en la salud, en la industria o en el medio ambiente de Colombia?<br><br>Escribe en tu cuaderno <b>2 ejemplos cotidianos</b> donde observes este principio en acción.",
                "icon": "ph-globe",
                "timer": 300,
                "customHtml": ""
            },
            {
                "title": "Trabajo Colaborativo en Parejas",
                "sub": "7/10 - Coevaluación y Debate",
                "content": "Intercambien sus cuadernos durante 2 minutos:<br>• Revisa si tu compañero justificó bien su procedimiento.<br>• Resalten aciertos y corrijan detalles con amabilidad.<br>• ¿Llegaron a la misma conclusión?",
                "icon": "ph-users-three",
                "timer": 300,
                "customHtml": ""
            },
            {
                "title": "Desafío Tipo Saber / ICFES de Clase",
                "sub": "8/10 - Pregunta de Razonamiento",
                "content": f"<b>Pregunta de Alta Exigencia:</b><br>Si modificamos una de las condiciones clave en <i>'{titulo_sem}'</i>, ¿qué cambio predecible ocurrirá en el sistema?<br><br>Anota tu opción y escribe la justificación científica en 2 renglones.",
                "icon": "ph-target",
                "timer": 300,
                "customHtml": ""
            },
            {
                "title": "Plenaria y Puesta en Común en el Tablero",
                "sub": "9/10 - Socialización Grupal",
                "content": "¿Quién desea compartir su resultado o modelo en el tablero?<br><br>Socializamos las dudas y consolidamos la conclusión oficial de la clase.",
                "icon": "ph-chalkboard-teacher",
                "timer": 300,
                "customHtml": ""
            },
            {
                "title": "Síntesis Oficial y Sello de Avance",
                "sub": "10/10 - Cierre y Firma",
                "content": f"✔️ <b>Aprendizaje Alcanzado:</b> Dominio conceptual y práctico de '{titulo_sem}'.<br>✔️ <b>Evidencia Sellada:</b> Ejercicios y esquemas completos en el cuaderno.<br><br>🌟 ¡Felicitaciones por tu esfuerzo y concentración en esta clase!",
                "icon": "ph-check-circle",
                "timer": 300,
                "customHtml": ""
            }
        ]
        materia_dict[str(sem_num)] = [slides]
    return materia_dict

# 2. FÍSICA 6° (8 Semanas)
fisica6_temas = {
    1: {"tema": "Cinemática: Movimiento vs Reposo", "meta": "Diferenciar movimiento y reposo según el punto de referencia.", "concepto": "1. El movimiento es relativo al observador.<br>2. Trayectoria: la forma del camino.<br>3. Desplazamiento: vector en línea recta entre inicio y fin.", "reto": "Dibuja en tu cuaderno dos trayectorias: una recta y una curva. Señala punto inicial, punto final y la flecha de desplazamiento.", "pregunta": "¿Puede un pasajero sentado en un autobús en marcha estar quieto y moviéndose al mismo tiempo?"},
    2: {"tema": "Rapidez y Velocidad Media", "meta": "Calcular rapidez como relación distancia/tiempo (v = d/t).", "concepto": "1. Rapidez = Distancia total dividida por el tiempo empleado.<br>2. Unidades del Sistema Internacional: metros por segundo (m/s) o km/h.<br>3. Diferencia: la rapidez es escalar y la velocidad indica dirección.", "reto": "Un ciclista recorre 150 metros en 30 segundos. Aplica la fórmula v = d / t, realiza la división en tu cuaderno y halla su rapidez en m/s.", "pregunta": "Si dos autos viajan a 80 km/h pero en sentidos contrarios, ¿tienen la misma rapidez? ¿Y la misma velocidad?"},
    3: {"tema": "Movimiento Rectilíneo Uniforme (MRU)", "meta": "Interpretar gráficas de posición vs tiempo en el MRU.", "concepto": "1. En el MRU la velocidad es constante en línea recta.<br>2. Distancias iguales en tiempos iguales.<br>3. La pendiente de la gráfica posición-tiempo representa la velocidad.", "reto": "Dibuja en tu cuaderno un plano cartesiano (Posición vs Tiempo) y traza una recta inclinada que muestre un objeto con velocidad constante de 5 m/s.", "pregunta": "¿Qué ocurre con la aceleración de un vehículo que se desplaza en MRU?"},
    4: {"tema": "Fuerzas y Leyes del Movimiento", "meta": "Identificar fuerzas de contacto y a distancia (Gravedad, Fricción).", "concepto": "1. Fuerza: toda interacción capaz de cambiar el estado de reposo o movimiento.<br>2. Primera Ley de Newton (Inercia): tendencia a conservar el estado.<br>3. Fuerza de rozamiento: se opone al deslizamiento.", "reto": "Dibuja un bloque sobre una mesa e indica con flechas de colores: Fuerza Normal, Peso (Gravedad), Fuerza de Empuje y Fuerza de Fricción.", "pregunta": "¿Por qué los pasajeros de un carro se van hacia adelante cuando el conductor frena bruscamente?"},
    5: {"tema": "Máquinas Simples y Ventaja Mecánica", "meta": "Explicar el funcionamiento de palancas, poleas y planos inclinados.", "concepto": "1. Máquinas simples: dispositivos que multiplican la fuerza aplicada.<br>2. Ley de la Palanca: Potencia x Brazo de Potencia = Resistencia x Brazo de Resistencia.<br>3. Tipos de palancas: 1°, 2° y 3° género.", "reto": "Dibuja una palanca de primer género (ej: balancín o tijeras), señalando Punto de Apoyo, Potencia y Resistencia.", "pregunta": "¿Por qué es mucho más fácil subir una carga pesada por una rampa que levantarla verticalmente a pulso?"},
    6: {"tema": "Masa, Volumen y Densidad", "meta": "Determinar la densidad de cuerpos sólidos y líquidos (d = m/V).", "concepto": "1. Masa: cantidad de materia (g o kg).<br>2. Volumen: espacio ocupado (cm³ o mL).<br>3. Densidad: compacidad de la materia (d = m / V).", "reto": "Un cubo de metal tiene una masa de 80 gramos y un volumen de 10 cm³. Calcula su densidad en g/cm³ y escribe si flotaría en agua (densidad del agua = 1 g/cm³).", "pregunta": "¿Por qué un barco gigante de acero flota en el mar mientras que una pequeña moneda de acero se hunde?"},
    7: {"tema": "Presión y Principio de Pascal", "meta": "Comprender la presión como fuerza distribuida en un área (P = F/A).", "concepto": "1. Presión = Fuerza dividida por Área de contacto.<br>2. A menor área de contacto, mayor es la presión ejercida.<br>3. Principio de Pascal: los líquidos transmiten la presión en todas las direcciones.", "reto": "Explica en tu cuaderno por qué un clavo puntiagudo entra fácil en la madera mientras que una barra plana no, usando la fórmula P = F / A.", "pregunta": "¿Por qué los zapatos para nieve son anchos y las agujas de inyección son extremadamente finas?"},
    8: {"tema": "Energía y sus Transformaciones", "meta": "Identificar energía cinética, potencial y la ley de conservación.", "concepto": "1. Energía: capacidad de realizar trabajo.<br>2. Energía Cinética (movimiento) y Energía Potencial Gravitatoria (altura).<br>3. Ley de Conservación: 'La energía no se crea ni se destruye, solo se transforma'.", "reto": "Dibuja una montaña rusa y señala los 2 puntos donde el carrito tiene: Máxima Energía Potencial y Máxima Energía Cinética.", "pregunta": "¿En qué tipos de energía se transforma la energía eléctrica de un bombillo o de un motor?"}
}
db["clases"]["fisica6"] = expandir_materia_a_10_diapositivas("fisica6", "Física 6°", fisica6_temas)

# 3. FÍSICA 7° (8 Semanas)
fisica7_temas = {
    1: {"tema": "Estados de la Materia y Modelo Cinético", "meta": "Explicar sólidos, líquidos y gases según la energía de sus moléculas.", "concepto": "1. Modelo Cinético: la materia está formada por partículas en constante movimiento.<br>2. Sólidos (fuerzas de atracción altas), Líquidos (fluyen), Gases (expansión total).<br>3. El Plasma como cuarto estado.", "reto": "Dibuja en tu cuaderno tres recipientes con la distribución de partículas para: Sólido (ordenadas), Líquido (semi-unidas) y Gas (dispersas).", "pregunta": "¿Qué ocurre con la velocidad de las moléculas de un gas cuando aumentamos su temperatura?"},
    2: {"tema": "Temperatura y Escalas Térmicas", "meta": "Diferenciar escalas Celsius, Fahrenheit y Kelvin.", "concepto": "1. Temperatura: medida de la energía cinética promedio de las moléculas.<br>2. Escala Celsius (°C): basada en el agua (0°C congelación, 100°C ebullición).<br>3. Escala Kelvin (K): escala absoluta (0 K = Cero Absoluto).", "reto": "Convierte 25 °C a escala Kelvin usando la fórmula K = °C + 273. Escribe el procedimiento completo en tu cuaderno.", "pregunta": "¿Por qué es científicamente incorrecto decir 'hace mucho calor' en lugar de 'la temperatura ambiental es alta'?"},
    3: {"tema": "Calor y Transferencia Térmica", "meta": "Diferenciar conducción, convección y radiación.", "concepto": "1. Calor: energía térmica en tránsito desde el cuerpo caliente al frío.<br>2. Conducción (contacto en sólidos), Convección (fluidos calientes suben), Radiación (ondas electromagnéticas).", "reto": "Dibuja una olla con agua sobre el fuego y señala con flechas dónde ocurre la conducción (mango), la convección (agua) y la radiación (fuego).", "pregunta": "¿Por qué las manijas de las ollas suelen ser de madera o plástico y no de metal?"},
    4: {"tema": "Ondas: Naturaleza y Clasificación", "meta": "Identificar longitud de onda, frecuencia, cresta y valle.", "concepto": "1. Onda: propagación de energía sin transporte de materia.<br>2. Ondas mecánicas (requieren medio, ej: sonido) y electromagnéticas (viajan en el vacío, ej: luz).<br>3. Longitud de onda (λ), Frecuencia (f) y Periodo (T).", "reto": "Dibuja una onda senoidal en tu cuaderno y rotula con colores: Cresta, Valle, Amplitud y Longitud de onda.", "pregunta": "¿Por qué en el espacio exterior no se escuchan explosiones aunque ocurran cerca de nosotros?"},
    5: {"tema": "Acústica y Propiedades del Sonido", "meta": "Analizar tono, timbre, intensidad y velocidad del sonido.", "concepto": "1. El sonido es una onda mecánica longitudinal.<br>2. Tono (frecuencia alta = agudo, baja = grave).<br>3. Intensidad (volumen en Decibeles) y Timbre (forma de la onda según el emisor).", "reto": "Escribe en tu cuaderno la velocidad del sonido en el aire (340 m/s) y calcula a qué distancia cayó un rayo si escuchaste el trueno 4 segundos después del relámpago.", "pregunta": "¿Por qué escuchamos primero el relámpago y segundos después el sonido del trueno durante una tormenta?"},
    6: {"tema": "Óptica: Reflexión y Espejos", "meta": "Aplicar la ley de reflexión en espejos planos y curvos.", "concepto": "1. La luz viaja en línea recta a 300.000 km/s en el vacío.<br>2. Ley de Reflexión: el ángulo de incidencia es igual al ángulo de reflexión (θi = θr).<br>3. Espejos planos forman imágenes virtuales y simétricas.", "reto": "Traza con tu regla un rayo de luz que incide a 45° sobre un espejo plano y dibuja el rayo reflejado cumpliendo la ley de reflexión.", "pregunta": "¿Por qué las letras de la palabra AMBULANCIA están escritas al revés en el frente de los vehículos de emergencia?"},
    7: {"tema": "Refracción de la Luz y Lentes", "meta": "Comprender la ley de Snell y el índice de refracción.", "concepto": "1. Refracción: cambio de dirección y velocidad de la luz al pasar de un medio a otro (ej: aire a agua).<br>2. Lentes convergentes (enfocan rayos) y divergentes (dispersan rayos).<br>3. Corrección de miopía e hipermetropía.", "reto": "Dibuja un vaso con agua y un lápiz adentro que se vea 'quebrado' debido a la refracción de la luz. Explica la razón en 2 renglones.", "pregunta": "¿Por qué cuando intentamos atrapar un pez en el agua no está exactamente donde nuestros ojos lo ven?"},
    8: {"tema": "El Espectro Electromagnético y Colores", "meta": "Identificar ondas de radio, microondas, luz visible y rayos X.", "concepto": "1. Espectro electromagnético: rango de todas las radiaciones posibles.<br>2. Luz visible: de 400 nm (violeta) a 700 nm (rojo).<br>3. Descomposición de la luz blanca en el prisma (Arcoíris).", "reto": "Dibuja un prisma triangular transparente donde entra un rayo de luz blanca y sale descompuesto en los 7 colores del arcoíris.", "pregunta": "¿Por qué las hojas de las plantas se ven verdes y el cielo durante el día se ve azul?"}
}
db["clases"]["fisica7"] = expandir_materia_a_10_diapositivas("fisica7", "Física 7°", fisica7_temas)

# 4. QUÍMICA PENSAR (8 Semanas)
quimica_temas = {
    1: {"tema": "Materia, Sustancias Puras y Mezclas", "meta": "Diferenciar sustancias puras (elementos/compuestos) de mezclas homogéneas y heterogéneas.", "concepto": "1. Elementos (un solo tipo de átomo) y Compuestos (unión química fija).<br>2. Mezclas homogéneas (soluciones de 1 sola fase) y heterogéneas (2 o más fases visibles).<br>3. Métodos físicos de separación: filtración, decantación, evaporación, destilación.", "reto": "Dibuja una tabla de 2 columnas en tu cuaderno y clasifica: Agua con sal, Ensalada de frutas, Aire, Hierro puro, Alcohol medicinal y Granito.", "pregunta": "¿Por qué el agua de mar es una mezcla homogénea y la leche es una mezcla coloidal heterogénea?"},
    2: {"tema": "El Átomo y Modelos Atómicos", "meta": "Identificar protones, neutrones, electrones y la evolución del modelo atómico.", "concepto": "1. Protones (+, núcleo), Neutrones (neutros, núcleo) y Electrones (-, corteza/orbitales).<br>2. Modelos históricos: Dalton, Thomson (pudín), Rutherford (núcleo), Bohr (órbitas) y Modelo Mecano-cuántico.", "reto": "Dibuja un átomo de Carbono (6 protones, 6 neutrones y 6 electrones en 2 niveles de energía) señalando el núcleo y la corteza.", "pregunta": "¿Por qué casi toda la masa del átomo está concentrada en su diminuto núcleo?"},
    3: {"tema": "La Tabla Periódica y Configuración Electrónica", "meta": "Ubicar grupos, periodos, metales, no metales y electrones de valencia.", "concepto": "1. Grupos (columnas verticales con propiedades químicas similares) y Periodos (filas horizontales = niveles de energía).<br>2. Metales (conductores, ceden electrones), No Metales (ganan electrones) y Gases Nobles (inertes).<br>3. Electrones de valencia y Regla del Octeto.", "reto": "Escribe la configuración electrónica del Sodio (Z=11): 1s² 2s² 2p⁶ 3s¹. ¿Cuántos electrones tiene en su último nivel?", "pregunta": "¿Por qué los elementos del Grupo 1 (Alcalinos) reaccionan de manera tan explosiva con el agua?"},
    4: {"tema": "Enlaces Químicos: Iónico, Covalente y Metálico", "meta": "Predecir el tipo de enlace según la electronegatividad de los átomos.", "concepto": "1. Enlace Iónico: transferencia de electrones entre metal y no metal (ej: NaCl sal de cocina).<br>2. Enlace Covalente: compartición de pares de electrones entre no metales (ej: H2O, CO2).<br>3. Enlace Metálico: mar de electrones libres.", "reto": "Dibuja la estructura de Lewis para la molécula de Agua (H2O) mostrando los enlaces covalentes y los electrones libres del Oxígeno.", "pregunta": "¿Por qué la sal disuelta en agua conduce electricidad mientras que el azúcar disuelto no la conduce?"},
    5: {"tema": "Nomenclatura y Funciones Químicas Inorgánicas", "meta": "Identificar Óxidos, Hidróxidos (Bases), Ácidos y Sales.", "concepto": "1. Óxidos básicos (Metal + O) y Óxidos ácidos (No metal + O).<br>2. Hidróxidos o Bases: contienen el grupo hidroxilo (OH)⁻.<br>3. Ácidos: liberan iones H⁺ (ej: HCl, H2SO4).<br>4. Sales: resultado de la neutralización Ácido + Base.", "reto": "Escribe la fórmula química y nombra: 1 Óxido (FeO o CO2), 1 Base (NaOH) y 1 Sal (NaCl).", "pregunta": "¿Qué producto se forma cuando el antiácido estomacal (base) reacciona con el ácido clorhídrico de nuestro estómago?"},
    6: {"tema": "Reacciones Químicas y Balanceo de Ecuaciones", "meta": "Aplicar la Ley de Conservación de la Masa y balancear por tanteo.", "concepto": "1. Reactivos ➔ Productos.<br>2. Ley de Lavoisier: 'La masa de los reactivos es igual a la masa de los productos'.<br>3. Tipos: Síntesis, Descomposición, Desplazamiento simple y Doble desplazamiento.", "reto": "Balancea por tanteo en tu cuaderno la ecuación de combustión del gas metano: CH4 + __ O2 ➔ CO2 + __ H2O.", "pregunta": "¿Por qué una fogata que consume un tronco de 10 kg parece dejar solo 1 kg de cenizas? ¿Dónde quedó la masa restante?"},
    7: {"tema": "Estequiometría y el Concepto de Mol", "meta": "Calcular masa molar y conversiones mol-gramo usando el número de Avogadro.", "concepto": "1. Mol: unidad de cantidad de sustancia (contiene 6,022 x 10²³ partículas).<br>2. Masa Molar (g/mol): suma de las masas atómicas de los elementos de la fórmula.<br>3. n = masa (g) / Masa Molar (g/mol).", "reto": "Calcula la masa molar del Dióxido de Carbono (CO2): C=12 g/mol, O=16 g/mol. ¿Cuántos gramos hay en 2 moles de CO2?", "pregunta": "¿Por qué los químicos necesitan contar las moléculas por 'moles' en lugar de pesarlas una por una?"},
    8: {"tema": "Soluciones Químicas, pH y Neutralización", "meta": "Calcular concentración (% m/v, Molaridad) y medir escala de pH de 0 a 14.", "concepto": "1. Soluto (menor proporción) + Solvente (mayor proporción).<br>2. Escala de pH: 0 a 6 (Ácido), 7 (Neutro como el agua pura), 8 a 14 (Básico/Alcalino).<br>3. Neutralización: Ácido + Base ➔ Sal + Agua.", "reto": "Dibuja una escala de pH de 0 a 14 y ubica: Jugo de limón (pH 2), Café (pH 5), Sangre humana (pH 7.4), Jabón (pH 10) y Blanqueador (pH 13).", "pregunta": "¿Por qué la lluvia ácida corroe estatuas de mármol y acidifica los lagos matando a los peces?"}
}
db["clases"]["quimica"] = expandir_materia_a_10_diapositivas("quimica", "Química PENSAR", quimica_temas)

# 5. MÚSICA (EDUCACIÓN ARTÍSTICA) - Expandir a 10 Diapositivas completas con 300s
# Mantener intactas las partituras ABCjs y los Pads interactivos ya creados
for sem_str in ["1", "2", "3", "4", "5", "6", "7", "8"]:
    if sem_str in db["clases"]["artistica"]:
        slides_orig = db["clases"]["artistica"][sem_str][0]
        # Asegurar timer de 300 en todas
        for s in slides_orig:
            s["timer"] = 300
        
        # Si tiene 6 diapositivas, expandir a 10 con fases musicales ricas
        if len(slides_orig) == 6:
            s1 = slides_orig[0]
            s2 = slides_orig[1]
            s3 = slides_orig[2]
            s4 = slides_orig[3]
            s5 = slides_orig[4]
            s6 = slides_orig[5]

            slides_10 = [
                {"title": s1["title"], "sub": "1/10 - Preparación y Bitácora Sonora", "content": s1["content"], "icon": s1.get("icon", "ph-music-notes"), "timer": 300, "customHtml": s1.get("customHtml", "")},
                {"title": "Audición Guiada y Paisaje Sonoro", "sub": "2/10 - Exploración Sensorial", "content": "Cierren los ojos durante 1 minuto y escuchen los sonidos del entorno. ¿Cuáles son rítmicos, cuáles continuos y cuáles repentinos? Anota 3 sonidos en tu cuaderno.", "icon": "ph-ear", "timer": 300, "customHtml": ""},
                {"title": s2["title"], "sub": "3/10 - Fundamentos Teóricos de la Música", "content": s2["content"], "icon": s2.get("icon", "ph-lightbulb"), "timer": 300, "customHtml": s2.get("customHtml", "")},
                {"title": s3["title"], "sub": "4/10 - Partitura y Simulación Interactiva", "content": s3["content"], "icon": s3.get("icon", "ph-chart-line-up"), "timer": 300, "customHtml": s3.get("customHtml", "")},
                {"title": s4["title"], "sub": "5/10 - ⏱️ Reto Individual en el Pentagrama", "content": s4["content"], "icon": s4.get("icon", "ph-pencil-line"), "timer": 300, "customHtml": s4.get("customHtml", "")},
                {"title": "Dictado y Lectoescritura Musical", "sub": "6/10 - Entrenamiento Auditivo", "content": "El profesor o líder de clase percutirá una secuencia rítmica/melódica de 4 compases. Escribe las figuras correspondientes en tu cuaderno.", "icon": "ph-waveform", "timer": 300, "customHtml": ""},
                {"title": s5["title"], "sub": "7/10 - Ensamble Colectivo por Secciones", "content": s5["content"], "icon": s5.get("icon", "ph-users-three"), "timer": 300, "customHtml": s5.get("customHtml", "")},
                {"title": "Apreciación de Grandes Obras Musicales", "sub": "8/10 - Cultura y Estética", "content": "Analicemos cómo los grandes maestros (desde la música barroca hasta el folclor colombiano) utilizan este elemento para transmitir emoción y mover el alma.", "icon": "ph-sparkle", "timer": 300, "customHtml": ""},
                {"title": "Plenaria: Afinación y Escucha Atenta", "sub": "9/10 - Puesta en Común", "content": "¿Cómo influye el silencio y la sincronización en el resultado final del coro o ensamble? Socialicen la experiencia.", "icon": "ph-microphone", "timer": 300, "customHtml": ""},
                {"title": s6["title"], "sub": "10/10 - Clausura y Sello Musical", "content": s6["content"], "icon": s6.get("icon", "ph-check-circle"), "timer": 300, "customHtml": s6.get("customHtml", "")}
            ]
            db["clases"]["artistica"][sem_str] = [slides_10]

# 6. CICLOS I, II, III, IV, V, VI (8 Semanas x 10 Diapositivas x 300s)
ciclos_info = {
    "ciclo1": ("Ciclo I (1°-3°)", {
        1: {"tema": "Los 5 Sentidos y el Cuidado del Cuerpo", "meta": "Identificar vista, oído, tacto, gusto y olfato.", "concepto": "Órganos de los sentidos y su función para protegernos.", "reto": "Dibuja los 5 órganos de los sentidos y al lado una acción para cuidarlos.", "pregunta": "¿Qué sentido nos avisa si un alimento está descompuesto?"},
        2: {"tema": "Hábitos Saludables y Nutrición", "meta": "Clasificar alimentos constructores, energéticos y reguladores.", "concepto": "La pirámide alimenticia y la importancia del agua y el deporte.", "reto": "Dibuja un plato saludable con verduras, proteína y fruta.", "pregunta": "¿Por qué tomar agua es mejor que tomar gaseosas?"},
        3: {"tema": "El Reino Vegetal: Partes de la Planta", "meta": "Reconocer raíz, tallo, hojas, flor y fruto.", "concepto": "Fotosíntesis básica: cómo las plantas fabrican su alimento.", "reto": "Dibuja una planta completa rotulando sus 5 partes.", "pregunta": "¿Por qué las plantas son los pulmones de nuestro planeta?"},
        4: {"tema": "El Reino Animal: Hábitats y Alimentación", "meta": "Clasificar herbívoros, carnívoros, omnívoros, terrestres y acuáticos.", "concepto": "Adaptaciones de los animales a su medio ambiente.", "reto": "Dibuja 2 animales y escribe su hábitat y qué comen.", "pregunta": "¿Por qué las aves tienen picos de diferentes formas?"},
        5: {"tema": "El Ciclo del Agua y su Cuidado", "meta": "Explicar evaporación, condensación, precipitación y recolección.", "concepto": "El agua como recurso vital no renovable en el hogar.", "reto": "Dibuja el ciclo del agua con nubes, lluvia, ríos y el sol.", "pregunta": "¿Por qué el agua que tomamos hoy es la misma de la época de los dinosaurios?"},
        6: {"tema": "El Suelo, los Minerales y el Reciclaje", "meta": "Diferenciar residuos orgánicos, plástico, papel y vidrio.", "concepto": "Las 3 R: Reducir, Reutilizar y Reciclar en la escuela.", "reto": "Dibuja 3 canecas de colores con los residuos correspondientes.", "pregunta": "¿Cuánto tiempo tarda una botella de plástico en degradarse en la tierra?"},
        7: {"tema": "El Sol, el Día y la Noche", "meta": "Comprender la rotación de la Tierra y la luz solar.", "concepto": "La Tierra gira sobre su eje generando el día y la noche.", "reto": "Dibuja la Tierra iluminada por el sol señalando el día y la noche.", "pregunta": "¿Por qué cuando aquí es de día, al otro lado del mundo es de noche?"},
        8: {"tema": "Mi Entorno Natural y el PRAE", "meta": "Elaborar un compromiso de protección ambiental escolar.", "concepto": "El cuidado de la huerta, las zonas verdes y la biodiversidad.", "reto": "Escribe y decora un lema ecológico para cuidar el colegio.", "pregunta": "¿Cómo podemos convertir nuestra escuela en un modelo ambiental?"}
    }),
    "ciclo2": ("Ciclo II (4°-5°)", {
        1: {"tema": "Ecosistemas y Cadenas Tróficas", "meta": "Identificar productores, consumidores y descomponedores.", "concepto": "Flujo de energía en redes alimentarias de páramos y selvas.", "reto": "Dibuja una cadena alimentaria con 4 eslabones de tu región.", "pregunta": "¿Qué pasaría en el bosque si desaparecieran todos los depredadores?"},
        2: {"tema": "Niveles de Organización Biológica", "meta": "Célula ➔ Tejido ➔ Órgano ➔ Sistema ➔ Organismo.", "concepto": "De lo microscópico al ser vivo completo.", "reto": "Dibuja la escalera de los 5 niveles con un ejemplo humano.", "pregunta": "¿Por qué un órgano no puede funcionar aislado del resto del cuerpo?"},
        3: {"tema": "Sistemas del Cuerpo Humano", "meta": "Integrar Digestivo, Respiratorio, Circulatorio y Excretor.", "concepto": "Cómo colaboran los sistemas para nutrir y oxigenar cada célula.", "reto": "Dibuja el recorrido de una molécula de oxígeno desde la nariz hasta la sangre.", "pregunta": "¿Por qué late más rápido el corazón cuando corremos?"},
        4: {"tema": "La Energía y sus Fuentes Renovables", "meta": "Diferenciar solar, eólica, hidráulica vs fósiles.", "concepto": "Transición energética y mitigación del cambio climático.", "reto": "Dibuja un aerogenerador o panel solar explicando su ventaja.", "pregunta": "¿Por qué el petróleo contamina y el sol es una fuente inagotable?"},
        5: {"tema": "Propiedades de la Materia y Cambios de Estado", "meta": "Analizar fusión, solidificación, evaporación y condensación.", "concepto": "Cambios físicos sin alterar la composición química.", "reto": "Dibuja un esquema de los cambios de estado con flechas de calor.", "pregunta": "¿Por qué el sudor en nuestra piel nos refresca cuando se evapora?"},
        6: {"tema": "Fuerzas, Movimiento y Gravedad", "meta": "Calcular rapidez y comprender la atracción gravitacional.", "concepto": "Masa vs Peso en la Tierra y en la Luna.", "reto": "Calcula cuánto pesaría un objeto de 60 kg en la Luna (gravedad = 1.6 m/s²).", "pregunta": "¿Por qué los astronautas flotan en la estación espacial?"},
        7: {"tema": "El Sistema Solar y la Luna", "meta": "Identificar los 8 planetas y las fases lunares.", "concepto": "Movimientos de rotación, traslación y mareas.", "reto": "Dibuja las 4 fases de la Luna (Nueva, Creciente, Llena, Menguante).", "pregunta": "¿Cómo influye la atracción de la Luna en las mareas de los océanos?"},
        8: {"tema": "Proyecto Ambiental PRAE: Cuidado del Agua", "meta": "Formular un plan de ahorro de agua en la comunidad.", "concepto": "Uso eficiente del recurso hídrico y reforestación de cuencas.", "reto": "Escribe un plan de 3 acciones para ahorrar 100 litros de agua al día en casa.", "pregunta": "¿Por qué los páramos de Colombia son las mayores fábricas de agua del mundo?"}
    }),
    "ciclo3": ("Ciclo III (6°-7°)", {
        1: {"tema": "La Célula Procariota y Eucariota", "meta": "Diferenciar organelos de células animales y vegetales.", "concepto": "Membrana, Núcleo, Mitocondrias, Cloroplastos y Pared Celular.", "reto": "Dibuja una célula vegetal y señala 3 organelos que no tiene la célula animal.", "pregunta": "¿Por qué la mitocondria es considerada la central energética celular?"},
        2: {"tema": "Transporte Celular: Ósmosis y Difusión", "meta": "Explicar el transporte pasivo y activo a través de la membrana.", "concepto": "Gradiente de concentración y bomba sodio-potasio.", "reto": "Dibuja qué le ocurre a un glóbulo rojo en solución hipertónica vs hipotónica.", "pregunta": "¿Por qué las pasas se hinchan cuando las dejamos sumergidas en agua toda la noche?"},
        3: {"tema": "Cinemática y Dinámica de Fuerzas", "meta": "Aplicar leyes de Newton y gráficas de MRU.", "concepto": "F = m x a y Tercera Ley de Newton (Acción y Reacción).", "reto": "Calcula la fuerza necesaria para acelerar un carro de 1000 kg a 3 m/s².", "pregunta": "¿Por qué al disparar un cañón este retrocede con fuerza hacia atrás?"},
        4: {"tema": "Estructura del Átomo y Tabla Periódica", "meta": "Identificar número atómico Z, masa atómica A y enlaces.", "concepto": "Electrones de valencia, grupos y periodos.", "reto": "Dibuja el átomo de Oxígeno (Z=8, A=16) indicando protones, neutrones y electrones.", "pregunta": "¿Por qué los elementos de un mismo grupo reaccionan de manera similar?"},
        5: {"tema": "Termodinámica y Calorimetría", "meta": "Diferenciar calor, temperatura y calor específico.", "concepto": "Q = m x c x ΔT y equilibrio térmico.", "reto": "Calcula el calor necesario para calentar 100 g de agua de 20°C a 80°C.", "pregunta": "¿Por qué el agua tarda tanto en calentarse y enfriarse en comparación con el metal?"},
        6: {"tema": "Los 5 Reinos Biológicos y Biodiversidad", "meta": "Clasificar Mónera, Protista, Fungi, Plantae y Animalia.", "concepto": "Taxonomía biológica y claves dicotómicas.", "reto": "Elabora un cuadro comparativo con las características de los 5 reinos.", "pregunta": "¿Por qué los hongos no son plantas aunque crezcan en el suelo?"},
        7: {"tema": "Reproducción Celular: Mitosis y Meiosis", "meta": "Diferenciar división somática vs gametogénesis.", "concepto": "Fases de la mitosis (Profase, Metafase, Anafase, Telofase) y recombinación.", "reto": "Dibuja las 4 fases de la mitosis con 4 cromosomas.", "pregunta": "¿Por qué la meiosis genera diversidad genética y la mitosis clones exactos?"},
        8: {"tema": "Ciencia, Tecnología y Sociedad en Colombia", "meta": "Analizar dilemas bioéticos y desarrollo sostenible regional.", "concepto": "Impacto de la minería, deforestación y energías limpias.", "reto": "Redacta una propuesta de solución para descontaminar un río local.", "pregunta": "¿Cómo puede la ciencia ayudar a los campesinos a producir más sin pesticidas dañinos?"}
    }),
    "ciclo4": ("Ciclo IV (8°-9°)", {
        1: {"tema": "Genética Mendeliana y Cuadros de Punnett", "meta": "Resolver cruces monohíbridos y dihidríbridos (Leyes de Mendel).", "concepto": "Genotipo, fenotipo, alelos dominantes y recesivos.", "reto": "Resuelve un cruce entre dos plantas heterocigotas (Aa x Aa) y calcula los porcentajes fenotípicos.", "pregunta": "¿Por qué dos padres de ojos oscuros pueden tener un hijo de ojos claros?"},
        2: {"tema": "Estructura del ADN y Síntesis de Proteínas", "meta": "Explicar replicación, transcripción a ARNm y traducción.", "concepto": "Bases nitrogenadas (A-T, C-G), codones y ribosomas.", "reto": "Traduce la hebra de ADN 'TAC-GGC-TTA' a ARNm y halla los aminoácidos.", "pregunta": "¿Qué ocurre en un organismo cuando ocurre una mutación puntual en el ADN?"},
        3: {"tema": "Teoría de la Evolución y Selección Natural", "meta": "Analizar la teoría de Darwin-Wallace y pruebas fósiles/anatómicas.", "concepto": "Variabilidad genética, presión ambiental y especiación.", "reto": "Explica la evolución del cuello de las jirafas según la selección natural.", "pregunta": "¿Por qué las bacterias se vuelven resistentes a los antibióticos si no completamos los tratamientos?"},
        4: {"tema": "Reacciones Químicas y Leyes Ponderales", "meta": "Balancear por tanteo y óxido-reducción (Redox).", "concepto": "Estados de oxidación, agente oxidante y reductor.", "reto": "Determina los estados de oxidación en el compuesto KMnO4 (Permanganato).", "pregunta": "¿Por qué se oxida un clavo de hierro a la intemperie y el oro nunca se oxida?"},
        5: {"tema": "El Espectro Electromagnético y Óptica Física", "meta": "Relacionar velocidad de la luz, frecuencia y energía fotónica.", "concepto": "E = h x f y dualidad onda-partícula.", "reto": "Calcula la frecuencia de una onda electromagnética de longitud λ = 500 nm.", "pregunta": "¿Por qué los rayos ultravioleta queman la piel y las ondas de radio no?"},
        6: {"tema": "Electricidad: Ley de Ohm y Circuitos", "meta": "Calcular V = I x R en circuitos serie y paralelo.", "concepto": "Voltaje, Corriente (Amperios) y Resistencia (Ohmios).", "reto": "Calcula la corriente que pasa por un foco de 60 Ω conectado a 120 V.", "pregunta": "¿Por qué en las casas los electrodomésticos están conectados en paralelo y no en serie?"},
        7: {"tema": "Biotecnología, Clonación y Transgénicos", "meta": "Evaluar aplicaciones de CRISPR, transgénicos y terapia génica.", "concepto": "Modificación genética en agricultura y medicina moderna.", "reto": "Elabora una tabla con 2 ventajas y 2 riesgos éticos de los alimentos transgénicos.", "pregunta": "¿Debería permitirse la edición genética en embriones humanos para evitar enfermedades?"},
        8: {"tema": "Simulacro Saber 9°: Competencias Científicas", "meta": "Resolver preguntas de indagación, explicación de fenómenos y uso del conocimiento.", "concepto": "Lectura de gráficas experimentales y variables controladas.", "reto": "Analiza una gráfica de crecimiento bacteriano con 3 antibióticos y justifica la opción correcta.", "pregunta": "¿Cómo identificar la variable independiente y dependiente en un experimento científico?"}
    }),
    "ciclo5": ("Ciclo V (10°)", {
        1: {"tema": "Mecánica Clásica: Cinemática Vectorial y Tiro Parabólico", "meta": "Descomponer vectores y calcular alcance máximo y altura máxima.", "concepto": "Ecuaciones paramétricas en eje X (MRU) y eje Y (MRUV/Caída libre).", "reto": "Calcula el tiempo de vuelo y alcance de un proyectil lanzado a 20 m/s a 30°.", "pregunta": "¿A qué ángulo de lanzamiento se obtiene el máximo alcance horizontal en un tiro parabólico?"},
        2: {"tema": "Dinámica: Leyes de Newton y Diagramas de Cuerpo Libre (DCL)", "meta": "Resolver planos inclinados con fricción y tensiones.", "concepto": "ΣF = m x a en ejes coordenados ortogonales.", "reto": "Dibuja el DCL de un bloque de 5 kg en un plano inclinado a 30° con coeficiente μ=0.2 y halla la aceleración.", "pregunta": "¿Por qué un objeto en reposo sobre una mesa tiene aceleración cero aunque la gravedad actúe sobre él?"},
        3: {"tema": "Trabajo, Energía y Conservación Mecánica", "meta": "Aplicar W = F x d x cos(θ) y Teorema Trabajo-Energía Cinética.", "concepto": "Fuerzas conservativas y no conservativas (disipación por calor).", "reto": "Calcula la velocidad con la que llega al suelo una masa de 2 kg que cae desde 20 metros de altura.", "pregunta": "¿Por qué en una montaña rusa la primera colina siempre debe ser la más alta de todo el recorrido?"},
        4: {"tema": "Estequiometría de Gases y Gases Ideales", "meta": "Aplicar P x V = n x R x T y Leyes de Boyle, Charles y Gay-Lussac.", "concepto": "Condiciones normales (1 atm, 273 K, 22.4 L/mol).", "reto": "Calcula el volumen que ocupan 3 moles de Oxígeno a 2 atm de presión y 300 K.", "pregunta": "¿Por qué un balón inflado en tierra caliente parece desinflarse cuando lo llevamos al páramo frío?"},
        5: {"tema": "Soluciones Químicas: Molaridad, Molalidad y Normalidad", "meta": "Calcular concentraciones y diluciones (C1 x V1 = C2 x V2).", "concepto": "Molaridad = moles soluto / Litros de solución.", "reto": "Calcula la Molaridad de una solución con 40 g de NaOH (Masa Molar = 40 g/mol) en 500 mL de agua.", "pregunta": "¿Cómo prepararías en el laboratorio 250 mL de ácido clorhídrico 0.1 M a partir de una botella concentrada 1 M?"},
        6: {"tema": "Termoquímica y Entalpía de Reacción", "meta": "Calcular ΔH mediante la Ley de Hess y diferenciar exotérmica/endotérmica.", "concepto": "Diagramas de energía de activación y estado de transición.", "reto": "Determina si una reacción con ΔH = -250 kJ/mol es exotérmica o endotérmica y dibuja su perfil de energía.", "pregunta": "¿Por qué la combustión de la gasolina libera energía y la fotosíntesis la absorbe?"},
        7: {"tema": "Fluidos: Principio de Arquímedes y Bernoulli", "meta": "Calcular empuje hidrostático y caudal en tuberías.", "concepto": "E = densidad x g x Vsumergido y Teorema de Bernoulli.", "reto": "Calcula el empuje que recibe una roca de 0.05 m³ totalmente sumergida en agua.", "pregunta": "¿Por qué las alas de los aviones generan sustentación gracias a la diferencia de velocidades del aire?"},
        8: {"tema": "Taller Saber 10°: Entrenamiento ICFES Ciencias Naturales", "meta": "Dominar preguntas de análisis de datos y control de variables.", "concepto": "Modelación matemática y falsación de hipótesis.", "reto": "Resuelve y justifica 2 preguntas tipo Saber 11 sobre planos inclinados y estequiometría.", "pregunta": "¿Cuál es la clave para descartar distractores en preguntas con tablas y gráficos del ICFES?"}
    }),
    "ciclo6": ("Ciclo VI (11°)", {
        1: {"tema": "Química Orgánica: Hidrocarburos e Isomería", "meta": "Nombrar y formular alcanos, alquenos, alquinos y aromáticos (Benceno).", "concepto": "Hibridación del carbono (sp³, sp², sp), tipos de enlaces y cadenas carbonadas.", "reto": "Dibuja la estructura y nombra los isómeros de cadena del Pentano (C5H12).", "pregunta": "¿Por qué el carbono es capaz de formar millones de compuestos diferentes mientras que el silicio no?"},
        2: {"tema": "Grupos Funcionales Oxigenados y Nitrogenados", "meta": "Identificar alcoholes, aldehídos, cetonas, ácidos carboxílicos, ésteres y aminas.", "concepto": "Propiedades físicas, puentes de hidrógeno y olores característicos.", "reto": "Identifica los 3 grupos funcionales presentes en la molécula de Ácido Acetilsalicílico (Aspirina).", "pregunta": "¿Por qué los ésteres son los responsables del aroma frutal de los perfumes y alimentos?"},
        3: {"tema": "Bioquímica: Carbohidratos, Lípidos y Proteínas", "meta": "Analizar la estructura de biomoléculas y el enlace peptídico.", "concepto": "Monómeros, polímeros biológicos, enzimas y desnaturalización proteica.", "reto": "Dibuja la formación de un enlace peptídico entre dos aminoácidos con liberación de agua.", "pregunta": "¿Por qué la clara de huevo cambia de transparente a blanca cuando la calentamos en el sartén?"},
        4: {"tema": "Electromagnetismo: Ley de Coulomb y Campo Eléctrico", "meta": "Calcular fuerza eléctrica (F = k x q1 x q2 / r²) y potencial eléctrico.", "concepto": "Cargas puntuales, líneas de campo eléctrico y Jaula de Faraday.", "reto": "Calcula la fuerza de repulsión entre dos cargas de +2 μC separadas 0.1 metros.", "pregunta": "¿Por qué el interior de un automóvil es el lugar más seguro durante una tormenta eléctrica?"},
        5: {"tema": "Inducción Electromagnética y Circuitos AC", "meta": "Aplicar Ley de Faraday y Ley de Lenz en generadores y transformadores.", "concepto": "Fuerza electromotriz inducida (FEM) y corriente alterna.", "reto": "Calcula el voltaje secundario de un transformador con N1=500 espiras, N2=100 espiras y V1=120 V.", "pregunta": "¿Cómo se genera la electricidad en una represa hidroeléctrica a partir del movimiento del agua?"},
        6: {"tema": "Física Moderna: Efecto Fotoeléctrico y Relatividad Especial", "meta": "Comprender E = m x c², dilatación temporal y cuántica de Planck.", "concepto": "Dualidad onda-partícula, fotones y contracción de longitud.", "reto": "Calcula la energía en Joules que se liberaría al convertir 1 gramo de materia pura en energía (c = 3x10⁸ m/s).", "pregunta": "¿Por qué el tiempo transcurre más lento para un astronauta que viaja cerca a la velocidad de la luz?"},
        7: {"tema": "Equilibrio Químico y Principio de Le Chatelier", "meta": "Calcular constantes de equilibrio Kc, Kp y predecir desplazamientos.", "concepto": "Factores que alteran el equilibrio: concentración, temperatura y presión.", "reto": "Predice hacia dónde se desplaza la reacción N2 + 3 H2 ⇌ 2 NH3 (exotérmica) si aumentamos la presión.", "pregunta": "¿Por qué en la síntesis industrial del amoníaco se trabaja a altas presiones para aumentar el rendimiento?"},
        8: {"tema": "Taller Final ICFES Saber 11: Graduación y Excelencia", "meta": "Consolidar el puntaje máximo en el componente de Ciencias Naturales.", "concepto": "Estrategias de descarte rápido, gestión del tiempo por pregunta y lectura crítica.", "reto": "Resuelve 3 problemas integrales tipo Saber 11 (Mecánica, Orgánica y Genética) con justificación técnica.", "pregunta": "¿Qué competencias científicas evaluadas por el ICFES garantizan tu éxito en la educación superior?"}
    })
}

for c_key, (c_name, c_temas) in ciclos_info.items():
    db["clases"][c_key] = expandir_materia_a_10_diapositivas(c_key, c_name, c_temas)

# Guardar base de datos consolidada
with open("proyectorData.json", "w", encoding="utf-8") as f:
    json.dump(db, f, ensure_ascii=False, indent=2)

print("¡CONSOLIDACIÓN EXITOSA! Todas las 12 materias tienen 8 semanas x 10 diapositivas = 80 diapositivas cada una, con temporizador de 5 minutos (300 segundos) en todas.")
